### ISSUE TITLE
/dev/dri getting used?

### ISSUE THREAD

**Issue by Uatschitchun** [photoview/photoview#1001]
**Describe the bug**
I set /dev/dri as device for my intel card. Although done that, processing vids uses a whole lotta cpu and ffmpeg is called like:
```
/usr/bin/ffmpeg -i /photos/fanny/!Vids/Montagskino #07 (2016)/Montagskino #07 (2016) 720p AAC Cam.MOV -vcodec h264 -acodec aac -vf scale='min(1080,iw)':'min(1080,ih)':force_original_aspect_ratio=decrease:force_divisible_by=2 -movflags +faststart+use_metadata_tags /home/photoview/media-cache/407/10682/web_video_Montagskino_#07_(2016)_720p_AAC_Cam_MOV_IBtJuc8r.mp4
```

**$ top**

> 1310367 999       20   0 1440,4m 365,3m  44,0m R **246,8**   2,3  23:19.85 ffmpeg                                                                                                                                                                
> 1312307 999       20   0 1056,8m 155,0m  43,8m S **165,8**   1,0   5:53.51 ffmpeg                                                                                                                                                                
> 1313202 999       20   0 1053,5m 152,4m  43,9m S **151,8**   1,0   2:15.44 ffmpeg

So my question is: Is /dev/dri (hw_accel) is being used?

**Expected behavior**
Being fast as when called like this:
`ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128  -i input.mov -vcodec h264_vaapi -q 20 -acodec aac -movflags +faststart+use_metadata_tags output.mp4`

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [yes]
 - Database [mariadb:lts]

**Comment by googollee** [comment]
No. It doesn't yet. I'm working on [a branch](https://github.com/googollee/photoview/tree/jellyfin-ffmpeg) to enable the hardware acceleration. You can run it with my image `ghcr.io/googollee/photoview:sha-fffd748` and set a new environment as `PHOTOVIEW_VIDEO_ENCODER=h264_vaapi` as well as mounting the device `/dev/dri` to see if it works well on your environment.

My branching image is built based on the head of the master repo. I verified it works well with Intel QSV with the environment `PHOTOVIEW_VIDEO_ENCODER=h264_qsv`.

From the encoder, you are running with AMD CPU, right?

I don't know when I will submit a PR for this feature. I still need to update the logs of `ffmpeg` and some docs before submitting it.

**Comment by kkovaletp** [comment]
@Uatschitchun, thanks for the report. Mapping the HW devices was implemented as a prerequisite to the task, we're working on now. 
There is the #652 to track the activity regarding the HW GPU acceleration, so I'll close this issue as a duplicate. I'd recommend to move the discussion to that issue, so that we keep all the related communication in 1 ticket
