### ISSUE TITLE
Update the AUR package

### ISSUE THREAD

**Issue by APT37** [photoview/photoview#1007]
The [AUR package](https://aur.archlinux.org/packages/photoview
) is still on version 2.3.13-1, so an update is required.

Thank you.

**Comment by kkovaletp** [comment]
@APT37 thanks for the report!
We missed this during our release process, as I don't use this OS and don't know how to update this package (I even didn't know, we push to some package repos)

@googollee, do you know how to update the AUR package? We probably need to include this in our build workflow for the tag processing case...

**Comment by googollee** [comment]
No, I don't have an account on AUR. I see that repo was created by `feinedsquirrel` and the current owner is `edpibu`. From the history comments, both of them have already dropped that repo. I'm not a good maintainer as I have never used Arch.

@APT37 I suggest you using docker or building from the repo.

**Comment by ChewingBever** [comment]
I emailed the AUR maintainer to see if they're interested in either maintaining or transfering the project.

**Comment by kkovaletp** [comment]
> Sadly building the 2.4.0 release and from the latest source both failed.

Are you sure that you were following the instructions and have all the required dependencies and build tools?
If yes, this might be another issue - please submit it with all the relevant details and environment description, so that we could look into it closer.

**Comment by kkovaletp** [comment]
> ```shell
> current: { node: 'v20.16.0'
> ```

I'd not recommend using Node versions higher than 18, as the frontend code was written a pretty long time ago with Node 16. The version 18 is the latest one with full backward compatibility to the version 16.

**Comment by ChewingBever** [comment]
The AUR package will have to be updated to use `nvm` instead then, I'm gonna look into updating the PKGBUILD file.

**Comment by kkovaletp** [comment]
this is not an error and it is unrelated to the frontend: it is a DB module of the backend and your DBMS

**Comment by ChewingBever** [comment]
The [AUR package](https://aur.archlinux.org/packages/photoview) has been updated to 2.4.0.
