### ISSUE TITLE
Make container work rootless

### ISSUE THREAD

**Issue by gardiol** [photoview/photoview#1013]
I am running PhotoView with podmal as rootless (non-root user) and all files created by it do belong to the wrong user. Per se is not a big deal, but it shouldn't take long to fix the issue in the container creation itself.

I am no expert and i don't know how, or i would make a pull request myself.

**Comment by googollee** [comment]
I don't know how you configure the Podman. [Podman rootless](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md#etcsubuid-and-etcsubgid-configuration) means it maps the user id in a container to a range of predefined uids. Those mapped uids are >100000 to avoid conflicting with normal IDs.

I think what you saw the wrong user is the right behavior if you configure the rootless. It's hard to see a user id >100000. 

In the other hand, the rootless is the feature of the container engine, like Podman or Docker. A container can't say anything about the rootless or not.

**Comment by kkovaletp** [comment]
@gardiol, thanks for your report.
From your description and the reply from @googollee, it looks like this is a configuration issue with your environment.
Taking into account that we don't support Podman officially, I'd close this ticket. This doesn't mean that it won't work in Podman, we just don't have the testing environment and experience to help you with the configuration.
