### ISSUE TITLE
gallery mode / slideshow

### ISSUE THREAD

**Issue by gardiol** [photoview/photoview#1019]
Would love to display a slideshow on a photo frame. I can open photoview in a browser, but how to rbadomly show images with a timeout?

**Comment by kkovaletp** [comment]
@gardiol, thanks for your question.
Currently, there is no slideshow functionality in the product, but we have the #931 PR and the #51 issue with this feature request.
So, I'll close this issue as a duplicate. Feel free to review those 2 tickets and add your thoughts to their discussions.
