### ISSUE TITLE
Docker image to read secrets from files to support the Docker Compose Secrets feature

### ISSUE THREAD

**Issue by kkovaletp** [photoview/photoview#1026]
**Is your feature request related to a problem? Please describe.**
Not a problem, but more like a security improvement:
Currently, we pass all the config as a set of environment variables, set in `.env` and `docker-compose.yml`. From the security perspective, this approach has a weak point: all the environment variables are accessible and easily dumped by all processes in that container. This means that if there is a vulnerable/hacked process, it can read and send all the secrets to the attacker.

**Describe the solution you'd like**
The solution is to implement the ability to read the predefined list of secrets from plain-text files inside the container, created and maintained by the Docker Engine in the scope of the [Docker Compose Secrets feature](https://docs.docker.com/compose/use-secrets/)
With the correct implementation (for instance, with no env variables, containing paths to those files), it will be not so obvious for attackers where to search those files. A research on this approach would be needed to find out the best way to implement it in Photoview.

**Describe alternatives you've considered**
An alternative would be to use a secret-manager solution (for example, HashiCloud Vault or something similar), but it would require a lot more skills and configuration efforts for users to set their environments up and make it work (at least with the mentioned Vault).

**Additional context**
Not much, just want to remind that we have a list of 3rd-party binaries, libs, and other packages, which are installed from repos, containing not the latest versions, so they contain some (even critical) known vulnerabilities, so the risk is not 0...

**Comment by kkovaletp** [comment]
@googollee, what do you think about this improvement?

**Comment by googollee** [comment]
I hope Docker Compose can fully copy the secret feature from [Kubernetes](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data). It's weird that they just copied half of it and didn't support env.

I don't want to support both file and env because it's hard to tell the priority order if both are provided. A workaround for Docker Compose is launching a preparing container and storing env to a file in a volume sharing with the target container.

In my opinion, it's always better to choose a single-node Kubernetes distribution (like k3s) than Docker Compose.

**Comment by kkovaletp** [comment]
Kubernetes supports secrets management out of the box, but it is not our default platform and even not officially supported, as it requires much more skills and effort from users to set up and make it work.

I think that there is no need to keep supporting both ways at the same time. If we decide to implement this feature, we could migrate the way we read those secrets from env to files. It is important to make sure that it will work for direct installations as well, because we have many users, not using Docker.

**Comment by googollee** [comment]
A workaround for Docker Compose now is customing the command:

```yaml
service:
  photoview:
    ...
    entrypoint: "" # remove pre-defined entrypoint
    command: |
      export PHOTOVIEW_MYSQL_URL=$(cat /run/secrets/mysql_user):$(cat /run/secrets/mysql_password)@tcp(mysql.address)/dbname
      /app/photoview
    secrets:
    - mysql_user
    - mysql_password
```

The config may not work directly. It shows the idea.

**Comment by kkovaletp** [comment]
The main idea of this change is to avoid putting secrets to env variables, as they are globally available inside the container.
Your w/a does exactly the same as the original implementation from this PoV.

**Comment by googollee** [comment]
A secret is also globally available inside the container. Every process in the container could access `/run/secrets/` without any more permission or more decrypting. As an env is limited inside a container, it doesn't break the secure model.

I didn't check the code of Docker Compose. In Kubernetes, a secret is a special volume, with a special encrypting/decrypting hook when mounting secrets to a container. By default, Kubernetes doesn't provide any encrypting when storing secrets, and cloud providers implement their hooks to decrypt from vaults.

**Comment by kkovaletp** [comment]
Well, in that case, there is no real difference from the security perspective between the standard way and the secrets: if secret files are always located in the same well-known folder in the plain-text format, accessible by all container's processes, then I don't see the real difference with env vars - an attacker can easily read all the files in the `/run/secrets/*` to get the same data, as by dumping all the env vars.

If my understanding is correct, I don't see a reason to invest our time into this topic...
Please confirm or provide your thoughts)

**Comment by kkovaletp** [comment]
Closing the ticket with no plans to implement
