### ISSUE TITLE
`debian:testing` base image is too unstable for us, as it gets corrupted from time to time

### ISSUE THREAD

**Issue by kkovaletp** [photoview/photoview#1031]
**Describe the bug**
Recently we've migrated to the `debian:testing` base image, however, from yesterday evening it has been corrupted (this time the package repo for the `testing` distro's branch contains corrupted packages, which cannot be installed). This means that this branch is used for testing and we cannot rely on it.

**To Reproduce**
Try to build the PROD image locally without the cache while the Debian repo isn't fixed. Or check the log of the CI job: https://github.com/photoview/photoview/actions/runs/10643539201/job/29507209980?pr=1028

**Expected behavior**
We have to migrate to another base image, stable enough to rely on it. Maybe that will be Alpine, but we need to try it 1st.

 - Are you using Docker? yes 
 - Version `master`

**Additional context**
https://github.com/photoview/photoview/pull/1028

**Comment by googollee** [comment]
> Try to build the PROD image locally without the cache while the Debian repo isn't fixed.

I didn't see this before. Do you have any log?

**Comment by googollee** [comment]
Debian testing may update a library at any time, which may break the build scripts.

One possible way to fix this is by switching to a stable distribution. Debian currently cuts a new stable [every 2 years](https://wiki.debian.org/DebianReleases#Production_Releases), which we think is too slow. Alpine cuts a new stable [every half year](https://alpinelinux.org/releases/), which means we could catch up dependencies in the half year, but it also could break the build every half year if we want to switch to a new stable release.

Another possible way is to build every dependency while building and copy them to the image. It will increase the building time and the complexity of the building script.

**Comment by googollee** [comment]
> Try to build the PROD image locally without the cache while the Debian repo isn't fixed. Or check the log of the CI job: https://github.com/photoview/photoview/actions/runs/10643539201/job/29507209980?pr=1028

After reproducing, both of them are caused by a mix using `stable` (golang:1.22-bookworm) and `testing`. There is a 3rd way to go now, building API under Debian testing. It requires installing golang from Debian testing. It's not a big problem as it's already 1.22.

**Comment by kkovaletp** [comment]
> Debian testing may update a library at any time, which may break the build scripts

This is the main problem here, as they don't track the `testing` branch as PROD, so they don't care much about not breaking anything there. This time they broke dependencies in the package repo. Next time it could be the image...

> After reproducing, both of them are caused by a mix using stable (golang:1.22-bookworm) and testing. There is a 3rd way to go now, building API under Debian testing. It requires installing golang from Debian testing. It's not a big problem as it's already 1.22.

It will fix the current issue, but tomorrow (or the next week) they might break something else... BTW, I think that the same problem exists when using the `debian:testing` and installing those deps there - I've tried this case and got a similar issue.

> Alpine cuts a new stable [every half year](https://alpinelinux.org/releases/), which means we could catch up dependencies in the half year, but it also could break the build every half year if we want to switch to a new stable release.

I think that in this case, it is manageable, as we have predefined release dates, and the distro team tracks the branch as PROD and does better testing before the release, if it is broken, we could always easily switch to the previous release (as there is the tag for each release).

> Another possible way is to build every dependency while building and copy them to the image. It will increase the building time and the complexity of the building script.

I, personally, don't want to go this way, as we'd take all the responsibility for all the dependencies building and the build pipeline would be too complex and difficult for maintenance.

> which, or how many, environments the build script should support.

As far as we have them: CI (build PROD image, tests, code analysis (if needed)), local build of the PROD image, dev-env. Also, we have to support the direct deployment to hosts, but it can be done another way than the scripts for the Docker build.

> We could switch back to Debian stable too, and drop to catch the latest dependencies.

That would mean that we gave up on it and lose the opportunity to get the latest stable versions of our dependencies, meaning we also won't have access to the latest features and media formats(

**Comment by googollee** [comment]
> As far as we have them: CI (build PROD image, tests, code analysis (if needed)), local build of the PROD image, dev-env. Also, we have to support the direct deployment to hosts, but it can be done another way than the scripts for the Docker build.

These are not enough. For example, if we switch to Alpine as the base image of the PROD image, the build script will be based on Alpine, and it won't work on Debian locally. As far as I know, no one uses Alpine as dev-env or daily env. Then, should we provide another script for dev-env, like Debian or Ubuntu?

**Comment by kkovaletp** [comment]
Do you see some real negative aspects of using the same Alpine base image for dev env?

> As far as I know, no one uses Alpine as dev-env or daily env.

My team used it in the dev-server scenario for backend, when the prod image was based on Alpine. The active development was performed on dev laptops with code mounted inside the dev image and served by the dev server to auto-restart on code changes. Also, unit tests were executed inside it.

The benefit is that we develop on the same platform, so if there is some bug, we catch it earlier. Also, we don't need to support 2 different versions of build scripts for different platforms.

However, in theory, there might be a lack of dev-libs and other necessary dependencies on Alpine. In this case, we'd need to keep 2 envs and support them in parallel.

Another question: how critical is the need to build the code on the same base image, as the final image is based on? I'm asking, because I know that it is not the case for Frontend: it is totally fine to build the Frontend code in a standard Node image and then copy static files to the final web-server image, based on any other image, and it will work fine. If this would work in a similar way for the Backend too, we could keep things simple. However, I'd assume that it won't work, as the Backend code is not static and has deeper dependencies to the system, it runs on.

**Comment by googollee** [comment]
If building with docker or docker-compose is also considered dev-env, then it's fine.

> Another question: how critical is the need to build the code on the same base image, as the final image is based on?

It's better to build api with alpine, because alpine use libmusl instead of glibc. There are a lot of unexpected behaviors if mix-use libmusl and glibc. UI compiles code to static files, and it should be fine.

I pr https://github.com/photoview/photoview/pull/1033 to switch to alpine. As node and golang image provide alpine version, use them too.
