### ISSUE TITLE
Proper Escaping of PostgreSQL Password

### ISSUE THREAD

**Issue by arauin** [photoview/photoview#1038]
## Problem Description
The current example .env does not properly escape the PostgreSQL password in the connection string. This leads to parsing failures when users attempt to use secure passwords containing special characters.

## Proposed Solution
1. Update the example in the documentation to demonstrate proper password escaping.
2. Add a note in the `.env` file to inform users about the need for proper password escaping.

### Implementation Details

 Add a comment in the `.env` file:
   ```
   # Note: If your PostgreSQL password contains special characters, make sure to URL-encode them.
   # For example: my!password@123 should be entered as my%21password%40123
   DATABASE_URL=postgresql://username:your_encoded_password_here@localhost:5432/database_name
   ```

**Comment by googollee** [comment]
Thanks for pointing it out. I think MySQL also requires a URL-encoding password.

**Comment by kkovaletp** [comment]
@arauin Thanks for the report!
I guess that it is related not only to the Docker deployment but also to Direct deployment as well.
Also, I'd add tho the explanation comment a link to 1 of online URL encoders to better explain what has to be done to those users, not familiar with it at all.

Would you like to prepare a PR with the fix?

**Comment by arauin** [comment]
https://github.com/photoview/photoview/pull/1041
