### ISSUE TITLE
Suggestion: simple EXIF date editor for better timeline organization

### ISSUE THREAD

**Issue by raptyk** [photoview/photoview#1060]
Some photos **don't have the date saved in their EXIF data**, and in these cases, PhotoView uses the file's save date from the disk instead. In my workflow, I copy files to a server, and photos without EXIF data are displayed incorrectly on the timeline.

My suggestion for improving the program is to **add a simple editor that would allow users to edit the date taken or created in the EXIF data**. This feature would help keep the timeline organized, especially for files
![wrong_dates](https://github.com/user-attachments/assets/6c920176-f3c2-42e9-b9c0-df90100c9428)
 that are missing this information.

**Comment by kkovaletp** [comment]
@raptyk, thanks for your suggestion.
But, unfortunately, it can't be implemented, as Photoview's architecture is built as a read-only product for the source media files. This means that we rely on the data, provided to us in those media files and can't change anything.

You might propose this editor to change the data in the Photoview DB, but this is also not a good idea, as in this case, we introduce a difference between the source media and the representation inside Photoview.

So, for all such cases, our recommendation is to edit your source media files using some other editors and make all needed changes in the 1st place. We have a bug with rescanning previously scanned files (#860), so you'd need to rename it a bit to trigger media replacement in the Photoview's cache.

With this, I'm closing the issue as not planned
