### ISSUE TITLE
Browsing videos, only play 2'nd click, sometime don't play at all

### ISSUE THREAD

**Issue by Luis-Lourenco** [photoview/photoview#1068]
**Describe the bug**
Videos most don't open on first click, usually have move to another video, then get back, and click, and most times the video is played well.

This bug don't affect images, only videos.

**To Reproduce**
1. Go to album
2. Select a video or a photo
3. navigate to a video
4. click for play (wait a lot, or just don't play) sometimes show video length
5. navigate back or forward
6. back to video and click play (mostly they play well)

On the first click, I see GET 200 domain.com/.../video.mp4
on the second click I see GET 206 domain.com/../video.mp4

Another info, on first click, background is always black.
on the second click the background is the video thumb, and after a few seconds or less the video play.

Some videos never GET 206, and I don't know why,

As my setup test. I container Photoprism and import same directory. I have no problems delivery the photos or the video.

The photo library is not user 1000, its another user, but is mapped and permissions to all users read, write and execute.

**Expected behavior**
Play the video.

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? yes
 - Database [e.g. mariadb 10.5]
 - Browser: Safaria / Firefox, on Mac intel x64 [e.g. chrome, safari]
 - Version no version showing ( but its latest from Ago 2024
**Additional context**
I have check, and there is no error about slow sql.
File system is mounted via NFS (data library) 6 hdd on raid 5, config, sql and thumbs on SSD mirror local drive.
the setup is a container on proxmox.

**Comment by kkovaletp** [comment]
@Luis-Lourenco, thanks for the report.
Just to make sure:
- You've tried this case in Safari, Chrome, and Firefox with exactly the same behavior, right?
- Are you sure that there are no network-related issues and the reason is not in slow media downloading?
- Do you see a correlation between source video type and ability to play it (video container, video/audio codecs, compression, a device, the video was shot on, etc.)?

We have similar issues: #866 #606 
Also, we have the #886 PR, which might fix the issue. It is waiting for review and some small fixes (I hope).

@googollee, when you have time, could you please double-check this issue from the code perspective and review the PR?
- Does Photoview recode every source video when scanning it for the 1st time or might some videos be used "as is" with no recoding?
- Is the final format fully compatible with the player on the UI side?
- When there is a request from UI to API to stream the video, is there a protection/retry functionality to handle network packet loss issues?

**Comment by Luis-Lourenco** [comment]
Hello @kkovaletp 

1. I just try on Safari and Firefox, Mac Intel and windows 10. 

2. I only have 2 types of vídeo, mp4 from my son phone, and mov from my phone and my wife. 

3. I see on mov it re-encode to mp4, I check on the cache directory all mp4 related to album ID. The original mp4 are not encoded. 

The last 2 points I don’t know. 

If I use VPN or at home access via nfs ti my phone, I have no issues. 

yesterday I was debugging using docker logs, sometimes I get slow sql, usually less than 400 ms on big albums only. I don’t see any error. 

I have weird network, I also note two extra situations:
1. When away from home specially on slow cellular data, I experienced auto logout. Meaning os waiting to load album, then after 30 seconds, if I refresh page, goes to log in. 

2. Another situation is hanging without logout, mean I select album, phone is waiting like 30 seconds, then load album with no issues. 

I think that’s it. 

Besides docker logs, is there any logs I can check?

**Comment by kkovaletp** [comment]
> 3\. I see on mov it re-encode to mp4, I check on the cache directory all mp4 related to album ID. The original mp4 are not encoded.

MOV and MP4 are video file containers. The video stream itself inside the container could be encoded in different formats, while stored inside the same container. It would be great if you could investigate some examples of the video files (both, which play fine and which don't) by running `ffprobe <path to the source video file>`

> sometimes I get slow sql, usually less than 400 ms on big albums only

This is not related to this problem

> I also note two extra situations

Thanks for mentioning it, but at this point I don't think it is related... However, still good to mention)

> Besides docker logs, is there any logs I can check?

Not really: everything done on the server, is outputted to the container's log. You can check the browser's Dev Tools Console for some JavaScript errors and the Network tab for network issues.

**Comment by googollee** [comment]
I don't think #886 relates to this issue directly. It avoids converting videos which are (possibly) supported by the browers. 

The different of returning code `200`/`206` is not a problem. `206` requests a part of the video to play immediately.

> If I use VPN or at home access via nfs ti my phone, I have no issues.

@Luis-Lourenco, it sounds like you access a home server from the internet. I highly suspect that the root cause is the speed of the connection. Through VPN or home access, the speed is normally much more stable and fast than through the internet. The first time you click, it still downloads the video and can't play.

I don't know if it's a good way to fix this, since a home connection through the internet without CDN is hard to ensure the quality.

**Comment by Luis-Lourenco** [comment]
> I don't think #886 relates to this issue directly. It avoids converting videos which are (possibly) supported by the browers.
> 
> The different of returning code `200`/`206` is not a problem. `206` requests a part of the video to play immediately.
> 
> > If I use VPN or at home access via nfs ti my phone, I have no issues.
> 
> @Luis-Lourenco, it sounds like you access a home server from the internet. I highly suspect that the root cause is the speed of the connection. Through VPN or home access, the speed is normally much more stable and fast than through the internet. The first time you click, it still downloads the video and can't play.
> 
> I don't know if it's a good way to fix this, since a home connection through the internet without CDN is hard to ensure the quality.

Since I have double NAT, I’m using CloudFlare tunnel with ssl to regular access to my PV instance.

**Comment by kkovaletp** [comment]
> I’m using CloudFlare tunnel

As far as I remember, they have a lot of settings and optimizations. Do you use their CDN/caching or every time you click the video, it is physically downloaded from your Photoview server (if not cached by the browser, but previously accessed through CloudFlare)?

**Comment by kkovaletp** [comment]
I'd agree with @googollee that the higher chances are that the reason is in the unstable internet connection. We couldn't support/guarantee/debug your internet routes and ISPs, so if there are no issues when you play videos inside your home network, it means that the issue is not in Photoview.

**Comment by Luis-Lourenco** [comment]
Well I have Jellyfin and Plex, larger videos and no issue at all. Both running on CF Tunnel. I don’t know if they use the same stream protocol as PhotoView.

**Comment by Luis-Lourenco** [comment]
> > I’m using CloudFlare tunnel
> 
> As far as I remember, they have a lot of settings and optimizations. Do you use their CDN/caching or every time you click the video, it is physically downloaded from your Photoview server (if not cached by the browser, but previously accessed through CloudFlare)?

No, I have caching disable because of streaming services.

**Comment by kkovaletp** [comment]
> Well I have Jellyfin and Plex, larger videos, and no issue at all.

Unfortunately, our UI is still waiting for contributors and a maintainer. It has not been updated for years and the player, we use, is quite primitive and old. I think that other products, designed for video streaming, are better optimized for this.

**Comment by Luis-Lourenco** [comment]
> > Well I have Jellyfin and Plex, larger videos, and no issue at all.
> 
> Unfortunately, our UI is still waiting for contributors and a maintainer. It has not been updated for years and the player, we use, is quite primitive and old. I think that other products, designed for video streaming, are better optimized for this.

I could help, but I only know C, C++ and Python. Sorry

**Comment by kkovaletp** [comment]
If you know a Senior JS/TypeScript developer who is familiar with React and interested in maintaining/improving Photoview, let them know about our Discord (the link is in the Readme)

**Comment by googollee** [comment]
@Luis-Lourenco Do you know how to monitor the network with Browser Injector? It's better to check what the network is doing when the first click happens.

**Comment by Luis-Lourenco** [comment]
> @Luis-Lourenco Do you know how to monitor the network with Browser Injector? It's better to check what the network is doing when the first click happens.

No, but I’ll google about it.  

The browser inspector is not enough? I see Firefox as a tool to slow logs timings and requests from page.

**Comment by googollee** [comment]
I guess inspector is enough to get some idea about what happens here and help to reproduce the issue.

**Comment by Luis-Lourenco** [comment]
> I guess inspector is enough to get some idea about what happens here and help to reproduce the issue.

hi @googollee I have some tests, here is the results:

It don't matter the video type of length.
1. On first click, the browser send a GET with video URL
2. I think the GET has lost or no response
3. I change to another video
4. back to same video
5. GET is send and have answer

[![Screenshot-2024-10-01-at-15-33-00.png](https://i.postimg.cc/VNBSJzqV/Screenshot-2024-10-01-at-15-33-00.png)](https://postimg.cc/zLvDMZPC)

in case link don't work: https://i.postimg.cc/VNBSJzqV/Screenshot-2024-10-01-at-15-33-00.png
Here is an example of what happened, page refresh on album, click video, navigate to other, click again and play.

**Comment by Luis-Lourenco** [comment]
Update:

Yesterday I have checked and I have cache disable on my CF domain.
Just for test, activate developer mode, bypassing cache core and purge cache, I think it solve the issue.
