### ISSUE TITLE
Filter Option: Show Pictures Without Recognized Faces

### ISSUE THREAD

**Issue by terslowe** [photoview/photoview#1112]
I would like an option on the timeline to filter and display only pictures where no faces are recognized. This should be relatively simple to implement since face recognition is already in place; it would just require filtering the timeline to exclude images with detected faces.

This way, it would be easier to find pictures like screenshots or other unnecessary images for deletion.

**Comment by kkovaletp** [comment]
@terslowe, thanks for sharing your use case!
I think that it can be covered by the #94 and #833 features during their design and implementation:
- users should be able to search for pictures with no faces
- users should be able to tag a picture with an existing or a new tag, so later they can filter all media by assigned tags.

Did I miss some aspects of your case? Please let me know.

With this, I'm closing this ticket as a duplicate, but we can continue the discussion if you need to provide additional context
