### ISSUE TITLE
FEATURE REQUEST: Allow setting of UID/GID using env vars

### ISSUE THREAD

**Issue by Retract1822** [photoview/photoview#1127]
**Is your feature request related to a problem? Please describe.**

In the [docker getting started guide](https://github.com/photoview/photoview?tab=readme-ov-file#getting-started--setup-with-docker) it mentions needing to make the media library's root folder and all the files and subfolders are readable and searchable by other users. Running the commands in the make file doesn't seem to help in my case. Though it seems to work for me if I set the owner/group as `999` as per the instructions however in my case `999` already bleongs to `systemd-coredump` which while works doesn't seem to be the most elegant solution. Ideally I should be able to specify the UID/GID I need using environment variables

**Describe the solution you'd like**
It would be really nice to be able to specify the UID/GID as for example done by the linuxserver.io images: https://docs.linuxserver.io/general/understanding-puid-and-pgid/

**Comment by kkovaletp** [comment]
@Retract1822, thanks, but this is a duplicate to the #1009, so I'm closing it. If there is something new, please add a comment to that issue
