### ISSUE TITLE
3rd folder when sharing doesn't load

### ISSUE THREAD

**Issue by Gunnest663** [photoview/photoview#143]
When i try to send a share to one of my friends and you try to go into the 3rd folder within the album it white screens and will not load
![Screenshot from 2020-12-03 14-13-29](https://user-images.githubusercontent.com/28125632/100971381-bfc70580-3571-11eb-9134-90d1823e7481.png)

**Comment by viktorstrate** [comment]
The UI just queries for albums three levels deep, when visiting a shared album.

https://github.com/viktorstrate/photoview/blob/8781ab37772ae5e788a383c73477af977570fd20/ui/src/Pages/SharePage/SharePage.js#L12-L29

This could be improved by lazily loading subalbums, when opened.
