### ISSUE TITLE
Album sharing: scroll down issue

### ISSUE THREAD

**Issue by vrenaville** [photoview/photoview#149]
Hello,

I have an issue, with the release 1.1.3 ARM docker image.

When I share an album, I can only see the first part of the album.
If I scroll down image is not visible, seems to be an JS issue .

![Selection_085](https://user-images.githubusercontent.com/355215/101328225-08cbd200-3870-11eb-8593-8c3953d7abc4.png)

**Comment by viktorstrate** [comment]
This is related to the react-lazyload library. This could maybe be solved by calling [forceCheck](https://github.com/twobin/react-lazyload#forcecheck) after the page has fully loaded

**Comment by vrenaville** [comment]
@viktorstrate 
Hello,

Sorry for last reply, I have try to check how to fix that, but I'm a newbie on JS , do you have any pointer where I need change it ?

Thanks for your help and work.

**Comment by viktorstrate** [comment]
I can see that somthing like this is already done here

https://github.com/photoview/photoview/blob/f2212988b74617d56df0f0f9dca3482142f3ab1e/ui/src/components/photoGallery/PhotoGallery.js#L89-L91

You can try to experiment with this, maybe try to call it every time it re-renders (move it out of the useEffect) and see if it helps.

I apreciate your help :)

**Comment by vrenaville** [comment]
@viktorstrate 

Hello,

I have try without luck, to correct this issue :/ .

Am I the only one to have this issue ?

**Comment by viktorstrate** [comment]
Solved in fa35ea1
