### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by viktorstrate** [photoview/photoview#156]
Give users the option to switch to a dark mode.
Should by default use dark/light mode based on the `prefers-color-scheme` CSS query. But should allow a manual override.

The [theming functionallity](https://styled-components.com/docs/advanced#theming) of Styled Components could be used to implement this.

**Comment by Ta7ar** [comment]
Hey I would like to give this an attempt, but just a few questions:
* Any particular hex color values you want for dark mode ?
* Where do you want the theme toggle button to be located ?
* Do you want icons for the toggle button ? (like sun icon during light mode, moon icon during dark)

**Comment by viktorstrate** [comment]
Hi @Ta7ar, thats awesome :)

> Any particular hex color values you want for dark mode ?

I don't have any particular hex colors in mind, though it would be nice to have the option to easily change the color palette in code, both for the light and dark theme.

The only color I've been consistent with is the blue primary color #4183c4.
Though we might have to change the shade for the dark theme.

I could imagine we would want color values for the following, though there might be more that I haven't though of:
- **Foreground**: color of text
- **Secondary foreground**: gray color for smaller text
- **Background**: white for light theme, probably not completely black for dark theme
- **Primary color**: Blue color of buttons and active elements
- **Secondary primary color**: gray color for inactive and subtle buttons,
eg. the inactive side-menu items and gear icons next to albums.
- **Highlight**: color of focus rings and other input related hightlights

> Where do you want the theme toggle button to be located ?

Ideally each user should have to their own settings page, from where they should be able to set it, and it should be saved in the database per user.

But as user settings hasn't been implemented yet, I think we should wait with the database integration, we can always do that later.

Maybe add it under the settings page. This would require some restructuring though, as non-admins currently don't have a settings page. I can help with this if you want.

>Do you want icons for the toggle button ? (like sun icon during light mode, moon icon during dark)

Icons could be nice, but not required. I imagine a drop-down menu with three options: auto (default), light, dark.
When auto is selected, the `prefers-color-scheme` value defines what color scheme to use. [See this guide](https://ourcodeworld.com/articles/read/1114/how-to-detect-if-the-user-prefers-a-light-or-dark-color-schema-in-the-browser-with-javascript-and-css).

Semantic UI allows for [icons in dropdowns](https://react.semantic-ui.com/modules/dropdown/#content-icon)

**Comment by KillerTic** [comment]
The Chrome extention "Dark Reader" does a very good job in applying a dark mode.
Maybe try that out and copy the hex codes for a proper dark mode.

**Comment by viktorstrate** [comment]
@KillerTic would you mind posting a screenshot?

**Comment by KillerTic** [comment]
Here you go!

![photoview_details](https://user-images.githubusercontent.com/57537806/145708658-d3a05250-848a-4615-a914-cbf8a16c903e.png)
![photoview_login](https://user-images.githubusercontent.com/57537806/145708659-43c412cf-bd74-4910-aa53-c27ec632d034.png)
![photoview_main](https://user-images.githubusercontent.com/57537806/145708660-7f481864-7c7c-449d-93ff-688aaba2182b.png)
