### ISSUE TITLE
GPU Support missing (?)

### ISSUE THREAD

**Issue by maltokyo** [photoview/photoview#159]
My Nvidia GPU is setup to passthrough and be available to docker containers.  Is there any way to make it available to photoview?  I noticed CPU processing load is huge (18-20 for me) when processing a big library or movies.  Adding support for the processors to use available GPUs would be great.

Here is how Jellyfin does it: https://jellyfin.org/docs/general/administration/hardware-acceleration.html#acceleration-on-docker

**Comment by viktorstrate** [comment]
I know little about this so help is appreciated.
It might be as simple as adding the `-hwaccel auto` flag to the ffmpeg command?

https://github.com/photoview/photoview/blob/4cd822f06897fe1fc566b56a984b78331227aa20/api/scanner/executable_worker.go#L97-L105

I don't know if the [OpenCL headers](https://pkgs.alpinelinux.org/package/edge/community/x86_64/opencl-headers) and [OpenCL ICD Loader](https://pkgs.alpinelinux.org/package/edge/community/x86_64/opencl-icd-loader) is needed, or could improve performance?
It is mentioned here https://trac.ffmpeg.org/wiki/HWAccelIntro#OpenCL

**Comment by maltokyo** [comment]
Here is the relevant part of my jellyfin docker-compose config, where GPU support works very well (on-the-fly video encoding, where the encoding happens at the same time as the user is watching).  It seems that for Nvidia `runtime: nvidia` is definitely required, and the other line might be jellyfin specific to enable it in the container.  The pre-setup has to be done outside of the docker container by the user.  Other graphics cards and Intel integrated graphics required a similar pre-setup, all documented in the link above.  Getting ffmpeg to use the exposed GPU in the container should not be an issue at all.

```
version: "2.1"
services:
  jellyfin_app:
    image: linuxserver/jellyfin
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
```

Then here is a sample command that is run in the jellyfin container when I try to watch a file (only when it is a format that is not web-native viewable) to transcode it for real-time streaming:

`/usr/lib/jellyfin-ffmpeg/ffmpeg -c:v h264_cuvid -resize 720x480 -i file:"/path/to/file/that/is/not/web-native/VIDEO.m4v" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset fast -b:v 3317395 -maxrate 3317395 -bufsize 6634790 -profile:v high  -g 90 -keyint_min 90 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 116579  -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcodes/0f56d04c89f601d55790f1abf1dc63d3%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/0f56d04c89f601d55790f1abf1dc63d3.m3u8"`

I hope this helps a bit?

**Comment by maltokyo** [comment]
Here is the official NVidia ffmpeg instructions:
https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

**Comment by tupats** [comment]
Any updates on this? Importing a huge library hogs my CPU

**Comment by viktorstrate** [comment]
I am not planning on working on this, mostly because I lack the proper knowledge.

But I would like to focus my energy into making the scanner smarter, for example by extracting embedded images from RAW images.

**Comment by tupats** [comment]
Thank you for your reply, I understand. Good luck!
I will try to find the time to dig deeper into integrating this, as the software is awesome for what it does.

**Comment by dsfsdbvxc** [comment]
GPU support for video transcoding would be brilliant, especially as theres now an iOS app for Photoview.

Not something I know anything about, but lots of useful info in [THIS](https://github.com/photoprism/photoprism/issues/1337) thread, getting GPU transcoding in Photoprism, may be useful as likely a similar setup.

**Comment by SureSRM** [comment]
The Photoprism approach is excellent.

I'm not a Go developer so I don't know the exact way of implementing this, but an option could be:

Add an env variable called `PHOTOVIEW_VIDEO_ENCODING_CODEC` which defaults to `h264` here:

https://github.com/photoview/photoview/blob/18b83dbbeade0de82688083fac2beb75cc3324d6/api/utils/environment_variables.go#L36-L41

Then replace the hardcoded codec `h264` with the value of that config variable here:
 
https://github.com/photoview/photoview/blob/4177b4fb33dab27a4f00cd07840935be6723688d/api/scanner/media_encoding/executable_worker/executable_worker.go#L123-L130

**Comment by kkovaletp** [comment]
@SureSRM , thanks for the idea, but it isn't so easy, because the FFmpeg tool has to be built (compiled) with the HW acceleration support. Also, a lot of dependencies should be installed into the image in order to support that.

We have another issue with the same request and I'm working on it: #652 - I'll track my progress there, so I'll close this issue as a duplicate even while it was submitted earlier - just for simplicity.
