### ISSUE TITLE
No navigation button on map

### ISSUE THREAD

**Issue by Kjeldgaard** [photoview/photoview#160]
When I go to places, I get a map. Unfortunately, there is no navigation (i.e. zoom + l,r,u,d) on the map. It is possible to zoom in by double clicking on the map, and then drag the map. However, I'm not able to zoom out without refreshing the page.

**Comment by viktorstrate** [comment]
Hi @Kjeldgaard, you can zoom using the scrollwheel.

But it would be easy to add navigation controls to mapbox see https://docs.mapbox.com/mapbox-gl-js/example/navigation/

**Comment by Kjeldgaard** [comment]
Thanks for the info. In my defense, I was using a laptop with a mouse pad, so no scroll wheel :)

I did see the page you linked. I think I'll use this issue to get started with docker build.

**Comment by viktorstrate** [comment]
Closed by #162
