### ISSUE TITLE
Places shows blank page

### ISSUE THREAD

**Issue by maltokyo** [photoview/photoview#161]
I have set up the API token and included it in the docker file.  But when I press "places"  (URL: http://my-ip:8000/places ) it just shows a blank page indefinitely.  What could I be missing?

**Comment by viktorstrate** [comment]
Does it show any errors in the web console?
If so, can you copy/paste them or send a screenshot

[Finding Your Browser's Developer Console](https://balsamiq.com/support/faqs/browserconsole/)

**Comment by maltokyo** [comment]
Oh good hint, sorry it was my mistake.  Seems I had used a secret Mapbox token, rather than the default public one.  Below was the error in Dev Tools.  Thank you, will close this.

```
src.663a0cc4.js:11 Uncaught Error: Use a public access token (pk.*) with Mapbox GL, not a secret access token (sk.*). See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
    at G._makeAPIURL (mapbox-gl.9fb3d092.js:4)
    at G.normalizeStyleURL (mapbox-gl.9fb3d092.js:4)
    at r.loadURL (mapbox-gl.9fb3d092.js:4)
    at n._updateStyle (mapbox-gl.9fb3d092.js:4)
    at n.setStyle (mapbox-gl.9fb3d092.js:4)
    at new n (mapbox-gl.9fb3d092.js:4)
    at PlacesPage.5a50f01c.js:12
    at as (src.663a0cc4.js:15)
    at exports.unstable_runWithPriority (src.663a0cc4.js:11)
    at fa (src.663a0cc4.js:15)
```

By the way @viktorstrate I love it so far!  Really great, and I was looking for something with exactly the same use case as you, store all locally, and share from there when i need!

I just would love GPU support, as the mp4 files that are generated on scan fill my tiny SSD ;)

**Comment by viktorstrate** [comment]
@maltokyo thank you, it's really motivating to keep working on Photoview when I know other people also use it!

After the release of version 2.0, I think I will work on improving video importing first.
I think transcoding on the fly will be challenging to implement but it could be a neat feature.

Reference to this discussion #131
