### ISSUE TITLE
Support Mysql - migration failed for version 2 and 3

### ISSUE THREAD

**Issue by giganteous** [photoview/photoview#163]
I got a panic while trying to run 'api' against mysql. My mysql version is 8.0.22 running on MacOS (there is no recent mariadb for Macs, sadly):

```
panic: Could not migrate database: migration failed in line 0: 
ALTER TABLE media
  ADD COLUMN IF NOT EXISTS side_car_path varchar(1024) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS side_car_hash varchar(32) DEFAULT NULL;
 (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS side_car_path varchar(1024) DEFAULT NULL,
  ADD COLUMN IF NOT EXIS' at line 2)
```

I can write a fix, dropping the 'IF NOT EXISTS' from these statements, but you might have had your reasons to add the clause?

**Comment by viktorstrate** [comment]
The database integration is currently in the works of being replaced by [Gorm](https://gorm.io/) which will expand the number of support database backends. See #137 

For now you can either install Mariadb on mac using Homebrew, see this guide https://mariadb.com/kb/en/installing-mariadb-on-macos-using-homebrew/ or remove the 'IF NOT EXISTS' statements manually.
