### ISSUE TITLE
Ignore video files / file types

### ISSUE THREAD

**Issue by scooter1556** [photoview/photoview#173]
I'm not sure if this is already possible or will be in v2 but I would like the ability to ignore video files entirely. This could either be done with a simple on/off setting or with "ignore patterns" where you can specify a list of patterns (e.g. *.mov, *.mp4, cache).

Thanks.

**Comment by viktorstrate** [comment]
This has not been implemented yet, but it's a high priority.
See also #169 and #131

**Comment by viktorstrate** [comment]
The scanner now doesn't transcode videos that can be played natively in the browser. This partially solves the problem.
Adding a way to ignore curtain paths would further solve this problem, see #32.

I will close this issue for now.
