### ISSUE TITLE
arm image not available for Photoview 2

### ISSUE THREAD

**Issue by yllekz** [photoview/photoview#179]
Hey there, I am attempting go upgrade to 2.0.0 but when I pull via either the "latest" or "2" tag, Portainer's container logs report "exec format error" which means the image is not compatible with my Raspberry Pi (ARM architecture). The previous version was working just fine.

**Comment by viktorstrate** [comment]
Okay thank you for reporting. I don't own an ARM machine and I might have forgotten to test it in a virtual machine.
I suspect this has something to do with Sqlite support as it requires cbindings and also required some changes to the Dockerfile.

**Comment by viktorstrate** [comment]
@yllekz I've worked hard today trying to figure out how to build the new photoview for all platforms, and I think I've found a solution that works now!

Would you mind testing the `:edge` tag, and confirm that it works?

**Comment by yllekz** [comment]
I'll give it a go in a bit. Thanks!

**Comment by yllekz** [comment]
The edge tag works on the Pi 4B! We're good.
