### ISSUE TITLE
Album download feature

### ISSUE THREAD

**Issue by andrasmaroy** [photoview/photoview#182]
I think it would be nice if people were able to download (shared) albums as zips similar to google drive for example.

**Comment by viktorstrate** [comment]
I think that would be a nice feature.

It would probably be fairly simple to implement, the `.zip` could maybe be saved under `media_cache/[ALBUM_ID]/[ALBUM_NAME].zip`, that way it would automatically be deleted if the album were to be deleted from the cache.

Maybe there should be the option to choose versions like `originals`, `high-res` and `thumbnails` like for individual media.

**Comment by jonas-hagen** [comment]
I would really appreciate this feature as well. One thought on that: The Zip file does not need to exist on disk. The archive can be created on the fly by writing from a zip stream to the http response stream.
