### ISSUE TITLE
Setup for Barebones ie Ubuntu Debian

### ISSUE THREAD

**Issue by DevilsDesigns** [photoview/photoview#185]
is there a way to use this on a barebones machine ie. Ubuntu 20.04, Debina 10 without a docker install? If so can you Specify.

**Comment by sh4nks** [comment]
Set it up like it's specified in the [Development Environment](https://github.com/photoview/photoview#setup-development-environment) setup instructions. Change the ``/api/.env`` accordingly (no debug mode, ui endpoint). Build the ui in ``/ui/`` with ``npm run build`` and make sure to point the API_ENDPOINT in ``/ui/.env/`` to the correct API address. The files in ``/ui/dist/`` can be hosted with apache or nginx (= this is the UI_ENDPOINT then).

**Comment by viktorstrate** [comment]
I wan't to write a propper guide explaining how to do this, I just haven't gotten around to do so yet.

I have written a guide a while ago that you can use, everything should be the same, except some of the environment variables has been changed a little with version 2. See https://github.com/photoview/photoview/issues/70#issuecomment-676255190
