### ISSUE TITLE
View all photos 

### ISSUE THREAD

**Issue by Marco1097** [photoview/photoview#187]
It would be nice to be able to view all the photos in the home, without any division into album. 
Maybe just a division by date that the user can choose (year or year - month)

**Comment by ClumsyAdmin** [comment]
+1 would love to see this implemented.

**Comment by viktorstrate** [comment]
I would like to start working on #48 soon, which looks very related to this.
Let's continue the discussion over there, unless you think it's very different, in that case feel free to elaborate and I will reopen this issue.
