### ISSUE TITLE
Timeline is multiplicated each time Photos section is entered

### ISSUE THREAD

**Issue by g3n3r0s0** [photoview/photoview#195]
Hi,
This is what I notice and how to replicate:
- The first time the Photos sections is entered, it displays the time line (OK).
- Enter Album section, then Photos again, a second timeline is added again at the end.
- And so on a third, forth, ...

**Comment by viktorstrate** [comment]
Thank you for reporting, this is probably because of how the cache is merged. I'll look into it 👍

**Comment by g3n3r0s0** [comment]
When you refresh (F5) the Photos page, the time line is restored.
