### ISSUE TITLE
Database cleanup errors

### ISSUE THREAD

**Issue by scooter1556** [photoview/photoview#198]
I am receiving this error in my logs on each scan.

I have tried deleting the db and starting from scratch but still the same error. No idea if it matters or what effect it is having.

This is running v2.1.1.

```
photoview_1    | 2021/02/16 21:47:01 /app/scanner/cleanup_media.go:106 Error 1451: Cannot delete or update a parent row: a foreign key constraint fails (`photoview`.`user_albums`, CONSTRAINT `fk_user_albums_album` FOREIGN KEY (`album_id`) REFERENCES `albums` (`id`))
photoview_1    | [25.553ms] [rows:0] DELETE FROM `albums` WHERE id IN (37,88,129,339,524,546,798,1089)
photoview_1    | 2021/02/16 21:47:01 ERROR: Could not delete old albums from database:
photoview_1    | Error 1451: Cannot delete or update a parent row: a foreign key constraint fails (`photoview`.`user_albums`, CONSTRAINT `fk_user_albums_album` FOREIGN KEY (`album_id`) REFERENCES `albums` (`id`))
```

**Comment by viktorstrate** [comment]
This looks like a bug, thank you for reporting :)

**Comment by viktorstrate** [comment]
Waiting to find a solution to this issue: https://github.com/go-gorm/gorm/issues/4126

**Comment by Redsandro** [comment]
Any update on this? Is there a workaround other than deleting your database and starting over (which I did multiple times and is bringing tears to my eyes :sweat:)?

**Comment by Redsandro** [comment]
> Is there a workaround other than deleting your database and starting over?

Ugly but it's either this or use a different photo album:

```
SET FOREIGN_KEY_CHECKS=0;
```

**Comment by viktorstrate** [comment]
Thank you for digging in this issue and collecting some scattered informations.

----

> Not sure if it is this simple, but someone commented on the linked issue. Sounds promising:
>
>    HasMany Association Mode :
>    db.Model(&item).Select("Albums ").Delete(item)
>    it works.

I don't quite understand that comment, what is the `item` refering to, maybe a user? Well we don't want to delete the entire user so that won't work.

----

I would much prefer to avoid `SET FOREIGN_KEY_CHECKS=0;`, as inconsistent foreign keys would be a huge pain to potentially deal with.

One thing that is a huge help is that the API is now testable which it wont when the problem first arrose, that would make it much easier to test that a particular modification fixed the problem.

I will take a closer look at the problem and see what I can come up with. Worse comes to worse, I don't think it's super hard to fix using raw SQL queries.

**Comment by Redsandro** [comment]
> I would much prefer to avoid `SET FOREIGN_KEY_CHECKS=0;`, as inconsistent foreign keys would be a huge pain to potentially deal with.

You are absolutely right. My hand has been stuck for two months though and I couldn't find a real surgeon so in the end I said "just chop it off!" 

Seriously though, I'm not sure why this bug doesn't affect more people, but nuking the database is a lot more costly than disabling foreign key checks (when that's the extent of your skillset) considering you'll lose all manually tagged people.

It works for now, but I'm not sure how much hidden trouble I've caused in my database. :sweat_smile: 

> I will take a closer look at the problem and see what I can come up with. Worse comes to worse, I don't think it's super hard to fix using raw SQL queries.

That would be much appreciated. A rough solution that works now is infinitely more awesome than a perfect solution that has yet to be implemented!

**Comment by viktorstrate** [comment]
I think `SET FOREIGN_KEY_CHECKS=0;` makes perfect sense as a temporary solution if the alternative is to nuke the database all the time.

I have started writing some tests to try and consistently replicate the error. I haven't managed to yet but I have also only just started.

**Comment by Redsandro** [comment]
I haven't figured out what specifically guarantees this error, but if it helps, when it happens, it has been preceded by someone with access to the root directory organizing (i.e. moving) some folders.

For example:

```
// old situation after full scan
rootAlbum/art/fun1
rootAlbum/art/fun2

// new situation before second scan
rootAlbum/2020/fun1
rootAlbum/2021/fun2
```

**Comment by viktorstrate** [comment]
Okay thank you for sharing some details. Do multiple users share the same images with your setup, that is do they have overlapping root paths?

**Comment by Redsandro** [comment]
Yes, there are two users with the exact same root path, because it's one huge album curated by some people using one admin account, and viewable by another group of people with a normal account.

**Comment by viktorstrate** [comment]
Thank you for confirming, that might be the cause of the foreign key problems.

**Comment by Redsandro** [comment]
Thank you! :tada:
