### ISSUE TITLE
RAF support

### ISSUE THREAD

**Issue by Damix48** [photoview/photoview#205]
RAW Fujifilm support is not working in `darktable-cli 2.6.0`.
Error:
```RawSpeed:Unable to find camera in database: 'FUJIFILM' 'X-T30' ''```

Maybe upgrading to `darktable-cli 3.0.1`?

**Comment by viktorstrate** [comment]
That should not be very dificult, we should be able to just add Darktable's PPA to the docker container.

https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable

**Comment by viktorstrate** [comment]
Closed with cc3f8a3
