### ISSUE TITLE
Screensaver mode?

### ISSUE THREAD

**Issue by RangerFX4** [photoview/photoview#212]
Hi,

I would like to ask if there is a "screensaver mode" option. I would like to use my old tablet as digital photo frame and let random pics/vids to show in fullscreen mode.

Regards!

**Comment by viktorstrate** [comment]
You mean like a slideshow? Maybe related to #51

**Comment by RangerFX4** [comment]
> You mean like a slideshow? Maybe related to #51

oh yes, slideshow but in fullscreen without the navigational option so make it seem like a digital photo frame. I hope it will be added in the future. for the meantime thank you for the amazing work!

**Comment by viktorstrate** [comment]
Okay thank you I will keep that in mind
