### ISSUE TITLE
Bug: Error when trying to open shared album

### ISSUE THREAD

**Issue by kaiiiz** [photoview/photoview#229]
**Describe the bug**
When opening shared album, the following error occurs in console:

```
Uncaught Error: Paginate argument is missing for query: media
    at merge (index.js:22)
    at t.runMergeFunction (chunk.N2ZMJJYN.js:35)
    at t.applyMerges (chunk.N2ZMJJYN.js:35)
    at chunk.N2ZMJJYN.js:35
    at Map.forEach (<anonymous>)
    at t.applyMerges (chunk.N2ZMJJYN.js:35)
    at t.processSelectionSet (chunk.N2ZMJJYN.js:35)
    at t.processFieldValue (chunk.N2ZMJJYN.js:35)
    at chunk.N2ZMJJYN.js:35
    at Array.map (<anonymous>)
```

And the content of the website is stuck at `Loading...`.

**To Reproduce**
I shared the `photoview-demo` album in demo site (https://photos.qpqp.dk/album/1143) and get the shared link: https://photos.qpqp.dk/share/JPUl9Tjx

After opening the shared link, open console can see the error as described above.

**Expected behavior**
Should display album content correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/30596812/109536790-1c967580-7af9-11eb-98d6-88d509e49dd4.png)

**Your environment:**
To check this error in clean environment, I tested it using docker in my personal laptop and still got the same error.

 - Are you using Docker? yes
 - Database? mariadb:10.5
 - Browser? brave
 - Version? viktorstrate/photoview:2

**Additional context**
Sharing photo is fine. e.g. https://photos.qpqp.dk/share/2Hi4OVq4

**Comment by viktorstrate** [comment]
Thank you for reporting
