### ISSUE TITLE
Are there any plans to create android/iOS apps?

### ISSUE THREAD

**Issue by joesteffee** [photoview/photoview#232]
This would be really great to replace something like google photos entirely. Not necessarily to upload photos but to view the whole library over the internet.

**Comment by viktorstrate** [comment]
Yes! I absolutely want to make mobile apps at some point.

It's not quite the same but the website can be installed as a Progressive Web App.
[How to install a PWA to your device](https://medium.com/progressivewebapps/how-to-install-a-pwa-to-your-device-68a8d37fadc1)
