### ISSUE TITLE
Bug: Error when trying to download photo

### ISSUE THREAD

**Issue by kaiiiz** [photoview/photoview#238]
**Describe the bug**
When downloading photo, the following error occurs in console:

```
Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at yt (chunk.3GYKX56M.js:63)
    at onClick (chunk.3GYKX56M.js:65)
    at Object.wa (chunk.PDZ5WKFG.js:5)
    at Sa (chunk.PDZ5WKFG.js:5)
    at Ea (chunk.PDZ5WKFG.js:5)
    at Lu (chunk.PDZ5WKFG.js:5)
    at gu (chunk.PDZ5WKFG.js:5)
    at chunk.PDZ5WKFG.js:5
    at Bo (chunk.PDZ5WKFG.js:9)
    at ga (chunk.PDZ5WKFG.js:5)
```

**To Reproduce**
1. Go to [demo site](https://photos.qpqp.dk/photos)
2. Randomly pick one photo
3. Click any of download buttons in the right tab

**Expected behavior**
Should download without problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/30596812/109990157-19db9080-7d44-11eb-8972-2049c6346622.png)

**Additional context**
It is a little off topic, but I found that the button group in sharing options would overflow when the width of window getting smaller.

Setting `flex-wrap: wrap` in the wrapper may helps a little bit, but the style (alignment) inside button may take into consideration.

![image](https://user-images.githubusercontent.com/30596812/109991384-3e843800-7d45-11eb-96f4-94990775e361.png)

**Comment by viktorstrate** [comment]
Thank you for the detailed explaination and style suggestion.
I must have missed testing downloads after removing the `PHOTOVIEW_PUBLIC_ENDPOINT` environment variable.
