### ISSUE TITLE
Crash on image scanning - Docker Edge

### ISSUE THREAD

**Issue by tulipo** [photoview/photoview#239]
I'm using the edge version of photoview docker in unraid enviroment.

It works everything but when i start scanning pictures it crash after sometimes.

Here is the log of the docker.

2021/03/05 08:59:35 Media already scanned: /photos/Gphotos/media/all/IMG-20130520-WA0010.jpg
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0xafd74f]

goroutine 183010 [running]:
github.com/photoview/photoview/api/scanner.processVideo(0xc007bda7e0, 0xc00810fc68, 0xc007ba9f30, 0x0, 0xc00810fc70, 0x797f35)
/app/scanner/process_video.go:108 +0x11ef
github.com/photoview/photoview/api/scanner.ProcessMedia(0xc007bda7e0, 0xc007c34ea0, 0x0, 0x0, 0xc007baca00)
/app/scanner/process_photo.go:80 +0xf6
github.com/photoview/photoview/api/scanner.scanAlbum.func2(0xc007bda7e0, 0x0, 0x0)
/app/scanner/scanner_album.go:79 +0x8f
gorm.io/gorm.(*DB).Transaction(0xc0003a3ce0, 0xc007b992c0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/gorm.io/gorm@v1.20.12/finisher_api.go:552 +0x3da
github.com/photoview/photoview/api/scanner.scanAlbum(0xc000bda000, 0xc0002b4c40, 0xc0003a3ce0)
/app/scanner/scanner_album.go:78 +0x2f2
github.com/photoview/photoview/api/scanner.(*ScannerJob).Run(...)
/app/scanner/queue.go:22
github.com/photoview/photoview/api/scanner.(*ScannerQueue).startBackgroundWorker.func1(0xc007967080, 0x13fc520)
/app/scanner/queue.go:93 +0x8d
created by github.com/photoview/photoview/api/scanner.(*ScannerQueue).startBackgroundWorker
/app/scanner/queue.go:91 +0x94

I'm using Docker in unraid with mysql. I also tried with mariadb but i have the same behavior.
If i use the latest version of photoview i can't visualize any picture in the browser but the thumbnails pictures are available in the folder tree.

**Comment by viktorstrate** [comment]
Can you provide steps to reproduce this?

**Comment by tulipo** [comment]
I setup a new database with mysql docker, then i start photoview, in the settings tabs i click on scan all users. After a couple of hour i   get this error bringing the docker itself on force close status. Maybe are too much images to scan. All my dslr library are 400gb and 80000 files between jpg and raw.

**Comment by tulipo** [comment]
I found like a workaround for the issue. I delete the path from my user, save and then add again.
Start scanning all the library seems to works fine. I see also the people tab filling up with faces. I just have sometimes some "thumbnail url is missing" error

**Comment by viktorstrate** [comment]
Good to hear, let me know if you experience it again. Then I'll reopen this issue.
The "thumbnail url is missing" error, has been reported here #214 :)
