### ISSUE TITLE
scanner error Incorrect datetime value for some images

### ISSUE THREAD

**Issue by joesteffee** [photoview/photoview#240]
Scanner error

Failed to begin database transaction: failed to process photo (/photos/2017-05-19/09_35_00.cr2): saving original photo to database: inserting original photo url: 5763, 09_35_00.cr2: Error 1292: Incorrect datetime value: '-6149-04-04 12:19:00' for column `photoview`.`media_exif`.`date_shot` at row 1

exiftool date info for that file:
exiftool 09_35_00.cr2
ExifTool Version Number         : 8.66
File Name                       : 09_35_00.cr2
Directory                       : .
File Size                       : 27 MB
File Modification Date/Time     : 2017:05:19 09:58:38-07:00
File Permissions                : rw-r--r--
File Type                       : CR2
MIME Type                       : image/x-canon-cr2
Exif Byte Order                 : Little-endian (Intel, II)
Image Width                     : 6000
Image Height                    : 4000
Bits Per Sample                 : 8 8 8
Compression                     : JPEG (old-style)
Make                            : Canon
Camera Model Name               : Canon EOS Rebel T6i
Preview Image Start             : 49868
Orientation                     : Horizontal (normal)
Preview Image Length            : 2005946
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Modify Date                     : 2017:05:19 09:35:00
Artist                          :
Rating                          : 0
Copyright                       :
Exposure Time                   : 1/1250
F Number                        : 5.0
Exposure Program                : Aperture-priority AE
ISO                             : 100
Sensitivity Type                : Recommended Exposure Index
Recommended Exposure Index      : 100
Exif Version                    : 0230
Date/Time Original              : 2017:05:19 09:35:00
Create Date                     : 2017:05:19 09:35:00
Components Configuration        : Y, Cb, Cr, -
Shutter Speed Value             : 1/1328
Aperture Value                  : 5.0
Flash                           : Off, Did not fire
Focal Length                    : 18.0 mm
Macro Mode                      : Normal
Self Timer                      : Off
Quality                         : RAW
Canon Flash Mode                : Off
Continuous Drive                : Continuous
Focus Mode                      : One-shot AF
Record Mode                     : CR2+JPEG
Canon Image Size                : Large
Easy Mode                       : Manual
Digital Zoom                    : None
Contrast                        : Normal
Saturation                      : Normal
Camera ISO                      : Auto
Metering Mode                   : Evaluative
Focus Range                     : Not Known
Canon Exposure Mode             : Aperture-priority AE
Lens Type                       : Unknown (4146)
Long Focal                      : 55 mm
Short Focal                     : 18 mm
Focal Units                     : 1/mm
Max Aperture                    : 3.6
Min Aperture                    : 23
Flash Activity                  : 0
Flash Bits                      : (none)
Zoom Source Width               : 0
Zoom Target Width               : 0
Manual Flash Output             : n/a
Color Tone                      : Normal
SRAW Quality                    : n/a
Auto ISO                        : 100
Base ISO                        : 100
Measured EV                     : 14.62
Target Aperture                 : 5
Target Exposure Time            : 1/1290
Exposure Compensation           : 0
White Balance                   : Auto
Slow Shutter                    : None
Shot Number In Continuous Burst : 0
Optical Zoom Code               : n/a
Camera Temperature              : 31 C
Flash Guide Number              : 0
Flash Exposure Compensation     : 0
Auto Exposure Bracketing        : Off
AEB Bracket Value               : 0
Control Mode                    : Camera Local Control
Measured EV 2                   : 15.5
Bulb Duration                   : 0
Camera Type                     : EOS High-end
ND Filter                       : n/a
Canon Image Type                : Canon EOS Rebel T6i
Canon Firmware Version          : Firmware Version 1.0.0
Canon Model ID                  : Unknown (0x80000393)
Thumbnail Image Valid Area      : 0 159 7 112
AF Area Mode                    : Zone AF
Num AF Points                   : 49
Valid AF Points                 : 19
Canon Image Width               : 6000
Canon Image Height              : 4000
AF Image Width                  : 6000
AF Image Height                 : 4000
AF Area Widths                  : 284 284 284 284 284 284 284 284 284 284 284 284 284 284 284 284 284 284 284 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
AF Area Heights                 : 345 345 345 345 345 345 345 345 345 345 345 345 345 345 345 345 345 345 345 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
AF Area X Positions             : -455 455 -455 455 -455 0 0 0 -1017 1017 -1017 1017 -1017 0 0 455 1580 -1580 1017 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
AF Area Y Positions             : -455 455 455 0 0 -455 455 0 -455 455 455 0 0 -856 856 -455 0 0 -455 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
AF Points In Focus              : 3,5,6,7,15
AF Points Selected              : 0,1,2,3,4,5,6,7,15
Bracket Mode                    : Off
Bracket Value                   : 0
Bracket Shot Number             : 0
Raw Jpg Size                    : Large
WB Bracket Mode                 : Off
WB Bracket Value AB             : 0
WB Bracket Value GM             : 0
Live View Shooting              : Off
Flash Exposure Lock             : Off
Internal Serial Number          : QA0228702
Dust Removal Data               : (Binary data 1024 bytes, use -b option to extract)
Crop Left Margin                : 0
Crop Right Margin               : 0
Crop Top Margin                 : 0
Crop Bottom Margin              : 0
Exposure Level Increments       : 1/3 Stop
ISO Expansion                   : Off
Highlight Tone Priority         : Disable
AF Assist Beam                  : Emits
AF Point Display During Focus   : On
Mirror Lockup                   : Disable
Shutter Button AF On Button     : Metering + AF start
Set Button When Shooting        : Normal (disabled)
LCD Display At Power On         : Display
Aspect Ratio                    : 3:2
Cropped Image Width             : 6000
Cropped Image Height            : 4000
Tone Curve                      : Standard
Sharpness                       : 3
Sharpness Frequency             : n/a
Sensor Red Level                : 0
Sensor Blue Level               : 0
White Balance Red               : 0
White Balance Blue              : 0
Color Temperature               : 5200
Picture Style                   : Auto
Digital Gain                    : 0
WB Shift AB                     : 0
WB Shift GM                     : 0
Measured RGGB                   : 456 1024 1024 520
VRD Offset                      : 0
Sensor Width                    : 6096
Sensor Height                   : 4056
Sensor Left Border              : 84
Sensor Top Border               : 46
Sensor Right Border             : 6083
Sensor Bottom Border            : 4045
Black Mask Left Border          : 0
Black Mask Top Border           : 0
Black Mask Right Border         : 0
Black Mask Bottom Border        : 0
Custom Picture Style File Name  :
AF Micro Adj Active             : No
AF Micro Adj Value              : 0
Peripheral Lighting             : On
Peripheral Lighting Value       : 70
Original Image Width            : 6000
Original Image Height           : 4000
Peripheral Lighting Setting     : On
Auto Lighting Optimizer         : Standard
Ambience Selection              : Standard
Grainy B/W Filter               : Off
Soft Focus Filter               : Off
Toy Camera Filter               : Off
Miniature Filter                : Off
Miniature Filter Orientation    : Horizontal
Miniature Filter Position       : 0
User Comment                    :
Sub Sec Time                    : 43
Sub Sec Time Original           : 43
Sub Sec Time Digitized          : 43
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 6000
Exif Image Height               : 4000
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
Focal Plane X Resolution        : 6718.924972
Focal Plane Y Resolution        : 6734.006734
Focal Plane Resolution Unit     : inches
Custom Rendered                 : Normal
Exposure Mode                   : Auto
Scene Capture Type              : Standard
Owner Name                      :
Serial Number                   : 032022000167
Lens Info                       : 18-55mm f/0
Lens Model                      : EF-S18-55mm f/3.5-5.6 IS STM
Lens Serial Number              : 0000386116
GPS Version ID                  : 2.3.0.0
Thumbnail Offset                : 37252
Thumbnail Length                : 12614
Photometric Interpretation      : RGB
Samples Per Pixel               : 3
Rows Per Strip                  : 338
Planar Configuration            : Chunky
Strip Offsets                   : 3086040
Strip Byte Counts               : 25664615
Raw Image Segmentation          : 1 3048 3048
Aperture                        : 5.0
Drive Mode                      : Continuous Shooting
Image Size                      : 6000x4000
Lens                            : 18.0 - 55.0 mm
Lens ID                         : Canon EF-S18-55mm f/3.5-5.6 IS STM
Preview Image                   : (Binary data 2005946 bytes, use -b option to extract)
Scale Factor To 35 mm Equivalent: 1.6
Shooting Mode                   : Aperture-priority AE
Shutter Speed                   : 1/1250
Create Date                     : 2017:05:19 09:35:00.43
Date/Time Original              : 2017:05:19 09:35:00.43
Modify Date                     : 2017:05:19 09:35:00.43
Thumbnail Image                 : (Binary data 12614 bytes, use -b option to extract)
Circle Of Confusion             : 0.019 mm
Field Of View                   : 64.4 deg
Focal Length                    : 18.0 mm (35 mm equivalent: 28.6 mm)
Hyperfocal Distance             : 3.43 m
Lens                            : 18.0 - 55.0 mm (35 mm equivalent: 28.6 - 87.4 mm)
Light Value                     : 14.9

**Comment by viktorstrate** [comment]
Is it possible for you to provide a sample image that causes this, you can just .zip compress it and attach it in a comment.

**Comment by joesteffee** [comment]
[photo_invalid_datetime.zip](https://github.com/photoview/photoview/files/6144153/photo_invalid_datetime.zip)

Here, it seems to be most if not all photos shot with my canon DSLR.

**Comment by joesteffee** [comment]
[photo_invalid_datetime_2.zip](https://github.com/photoview/photoview/files/6144184/photo_invalid_datetime_2.zip)

another example:
2021/03/15 13:08:35 ERROR: Failed to begin database transaction: failed to process photo (/photos/2016-06-26/16_32_44.jpg): saving original photo to database: inserting original photo url: 4989, 16_32_44.jpg: Error 1292: Incorrect datetime value: '-6150-05-12 19:16:44' for column `photoview`.`media_exif`.`date_shot` at row 1

**Comment by Kjeldgaard** [comment]
WIth PR https://github.com/photoview/photoview/pull/258 your two sample photos show up at 2nd of June 2016 and 26th of June 2016. I assume that is correct.
