### ISSUE TITLE
Face detection is not compatible with postgres

### ISSUE THREAD

**Issue by wolfpld** [photoview/photoview#241]
photoview_1  | 2021/03/06 16:44:20 /go/pkg/mod/gorm.io/driver/postgres@v1.0.8/migrator.go:157 ERROR: type "blob" does not exist (SQLSTATE 42704)
photoview_1  | [0.892ms] [rows:0] CREATE TABLE "image_faces" ("id" bigserial,"created_at" timestamptz,"updated_at" timestamptz,"face_group_id" bigint NOT NULL,"media_id" bigint NOT NULL,"descriptor" BLOB NOT NULL,"rectangle" VARCHAR(64) NOT NULL,PRIMARY KEY ("id"),CONSTRAINT "fk_image_faces_face_group" FOREIGN KEY ("face_group_id") REFERENCES "face_groups"("id"),CONSTRAINT "fk_image_faces_media" FOREIGN KEY ("media_id") REFERENCES "media"("id") ON DELETE CASCADE,CONSTRAINT "fk_media_faces" FOREIGN KEY ("media_id") REFERENCES "media"("id") ON DELETE CASCADE,CONSTRAINT "fk_face_groups_image_faces" FOREIGN KEY ("face_group_id") REFERENCES "face_groups"("id") ON DELETE CASCADE)

and later

photoview_1  | 2021/03/06 16:44:20 /app/scanner/face_detection/face_detector.go:54 ERROR: relation "image_faces" does not exist (SQLSTATE 42P01)
photoview_1  | [0.509ms] [rows:0] SELECT * FROM "image_faces"
photoview_1  | 2021/03/06 16:44:20 Could not initialize face detector: get face detection samples from database: ERROR: relation "image_faces" does not exist (SQLSTATE 42P01)
photoview_1  | panic: Could not initialize face detector: get face detection samples from database: ERROR: relation "image_faces" does not exist (SQLSTATE 42P01)

**Comment by viktorstrate** [comment]
Thank you for reporting
