### ISSUE TITLE
Scanner Error: Unsupported Color model

### ISSUE THREAD

**Issue by akkord64** [photoview/photoview#242]
**Describe the bug**

Scanner error
Failed to begin database transaction: failed to process photo (/photos/Desiree 1st Party/Desiree 1st Invitations-02.tif): creating high-res cached image: image decoding: failed to decode image (/photos/Desiree 1st Party/Desiree 1st Invitations-02.tif): tiff: unsupported feature: color model

**To Reproduce**
Add library and scan existing media.

**Expected behavior**
imports successfully

**Screenshots**
Scanner error:

Scanner error
Failed to begin database transaction: failed to process photo (/photos/Desiree 1st Party/Desiree 1st Invitations-02.tif): creating high-res cached image: image decoding: failed to decode image (/photos/Desiree 1st Party/Desiree 1st Invitations-02.tif): tiff: unsupported feature: color model

**Your environment:**
docker compose file provided in repo

**Additional context**

Original image.
[Desiree 1st Invitations-02.zip](https://github.com/photoview/photoview/files/6097331/Desiree.1st.Invitations-02.zip)

**Comment by viktorstrate** [comment]
I think that's a limitation of the [Go TIFF decoder](https://pkg.go.dev/golang.org/x/image/tiff), this would maybe be solved if #227 was implemented.
