### ISSUE TITLE
Photos and videos not being sorted properly on "Photos" view

### ISSUE THREAD

**Issue by Shlokp** [photoview/photoview#244]
**Describe the bug**
I recently set up photoview for all my locally stored photos and it is working well except when I am in "Photos" view, many images/videos are not corrently organised by which i mean they are showing the wrong date. I have noticed this appears to be all pngs / videos. All jpgs seems to be dated correctly as far as I can tell.

An example of the metadata for one of these photos which appear in the wrong place is below (used imageMagick to extract this)
` Properties:
    Creation Time: 2018:09:04 12:43:53
    date:create: 2020-11-25T12:43:57+00:00
    date:modify: 2020-11-25T12:43:57+00:00
`

The photo has the correct creation time however photoview seems to arrange by either date:create or date:modify as that is the date it shows up for.

Is there any way to change which value the "Photos" view sorts by?

edit - wording

**Comment by viktorstrate** [comment]
#136 might solve this

**Comment by Shlokp** [comment]
Thanks, how can I try to change the exif library and see if it works? Happy to try

**Comment by viktorstrate** [comment]
Nice, I've written some hints below if you want to take a look on implementing it. :smile:

You should take a look at the [go-exiftool](https://github.com/barasher/go-exiftool) library.
Exif parsing is quite modular, you would have to implement a new `exifParser`

https://github.com/photoview/photoview/blob/302ddf1296436f58e1ed8175ddcc5a0e0100102e/api/scanner/exif/exif.go#L12-L14

Take a look at the [existing exif parser](https://github.com/photoview/photoview/blob/master/api/scanner/exif/exif_parser_internal.go) for inspiration, then make a similar one that uses the `go-exiftool` library instead.

**Comment by Shlokp** [comment]
Thanks, will give it a go. This is way above my skill but lets see.

An example output using both goexif2 and exiftool for a photo that is misplaced
```
$ ./goexif2 Screenshot_Snapchat_20180904-142404_1.png 
2021/03/08 21:43:26 err on Screenshot_Snapchat_20180904-142404_1.png: exif: decode failed (exif: failed to find exif intro marker) 
```
```
$ exiftool Screenshot_Snapchat_20180904-142404_1.png 
ExifTool Version Number         : 11.16
File Name                       : Screenshot_Snapchat_20180904-142404_1.png
Directory                       : .
File Size                       : 2.8 MB
File Modification Date/Time     : 2020:11:25 12:43:57+00:00
File Access Date/Time           : 2021:03:08 11:41:33+00:00
File Inode Change Date/Time     : 2021:03:08 21:07:50+00:00
File Permissions                : rwxrwxr--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 1440
Image Height                    : 2238
Bit Depth                       : 8
Color Type                      : RGB with Alpha
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Significant Bits                : 8 8 8 8
SRGB Rendering                  : Perceptual
Gamma                           : 2.2
Pixels Per Unit X               : 3779
Pixels Per Unit Y               : 3779
Pixel Units                     : meters
Creation Time                   : 2018:09:04 12:43:53
Image Size                      : 1440x2238
Megapixels                      : 3.2
```

This photo shows up on 25/11/2020 on photoview so I think my goexif2 cli install is a bit broken as it is definitely able to read some info from the image

**Comment by viktorstrate** [comment]
goexif2 is very simple and doesn't always find the EXIF data properly, that's one of the reasons why it would be nice to replace it with exiftools

**Comment by Kjeldgaard** [comment]
I've made a new implementation based on go-exiftool. It is 75% done. I hope I'll have it finished within the next week.

**Comment by Shlokp** [comment]
> I've made a new implementation based on go-exiftool. It is 75% done. I hope I'll have it finished within the next week.

Great, excited to try!!

**Comment by Kjeldgaard** [comment]
> > I've made a new implementation based on go-exiftool. It is 75% done. I hope I'll have it finished within the next week.
> 
> Great, excited to try!!

See PR: https://github.com/photoview/photoview/pull/258
