### ISSUE TITLE
how can I connect to external database which isn't the docker instance?

### ISSUE THREAD

**Issue by Fsociety-one** [photoview/photoview#249]
when I want to connect the external database which isn't the docker instance, that's my docker-compose.yml file:
version: "3"
services:
  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8080:80"
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=user:userpasswd@172.17.0.1:3306/photoview
      - PHOTOVIEW_LISTEN_IP=0.0.0.0
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/var/www/photoviewche
    volumes:
      - api_cache:/var/www/photoviewche
      - /var/www/photos:/photos:ro
..........

but always report: " WARN: Could not ping database: Could not parse mysql url: default addr for network '172.17.0.1:3306' unknown. Will retry after 5 seconds " ,even if I changed the host IP, how can I change it......

**Comment by viktorstrate** [comment]
Please take a look at #200

**Comment by Fsociety-one** [comment]
Thank you very much ^_^
