### ISSUE TITLE
[Feature Request]Multiple selection/download photos

### ISSUE THREAD

**Issue by gdepre** [photoview/photoview#251]
I could be a great improvement to be able to select multiple pictures at one time and download those files in a zip file

**Comment by viktorstrate** [comment]
This would tie nicely with #182, also it could be used to improve the UX for organising face groups.

**Comment by OdneOksavik** [comment]
I know this feature request is two years old, but I still want to comment that this is a much asked for feature from my end-users. In addition to #182 mentioned above, also #609 would be resolved / will resolve the issue. 

I'm not sure how much active development is happening on the project, but this would certainly be great progress.

**Comment by kkovaletp** [comment]
As #609 provides a more generic description for the same request, I'd keep that one open and close this one as a duplicate, even if it was submitted earlier
