### ISSUE TITLE
Scrolling on iPad / touch screens not possible

### ISSUE THREAD

**Issue by jansorg** [photoview/photoview#252]
**Describe the bug**
scrolling pages with photos is almost impossible in an iPad (iPad OS 14.4 and also on an older device). This happens on pages „albums“ and Photos“. Touch&drag only moves the content for a few millimeters and then stops. 

scrolling list of faces-pictures is working much better, though.

**To Reproduce**
1. Go to „photos“
2. try to scroll down

**Your environment:**
 - Are you using Docker? Yes
 - Browser Safari, iPadOS 14.4

**Additional context**
My guess would be that it‘s caused by lazy loading, at least partially. But that‘s an uneducated guess.

**Comment by viktorstrate** [comment]
I can confirm this. I hope #189 can fix this.

**Comment by viktorstrate** [comment]
Solved
