### ISSUE TITLE
Feature request: Toggle face recognition feature

### ISSUE THREAD

**Issue by emmorts** [photoview/photoview#253]
**Is your feature request related to a problem? Please describe.**
I find that in personal use cases, face detection is mostly a gimmick rather than a useful feature, so I don't see the reason for using resources on feature I would not use.

**Describe the solution you'd like**
Add an option to toggle face detection feature via settings.

**Comment by viktorstrate** [comment]
It might be better to add this in the form of an environment variable, then the feature would be disabled when the server started and it would be much easier to implement.

Would this work instead?

**Comment by emmorts** [comment]
@viktorstrate I agree, that's probably a more reasonable resolution.

**Comment by viktorstrate** [comment]
Moved to #279
