### ISSUE TITLE
Scanner error: Error detecting faces in image

### ISSUE THREAD

**Issue by Kjeldgaard** [photoview/photoview#254]
**Describe the bug**
Gets scanner error, when scanning for images after initial setup.

**To Reproduce**
docker-compose down && docker volume prune
docker-compose up
Create new user, password and photo path
Click on settings
Click 'Scan' or 'Scan all users'
The above error is shown

**Expected behavior**
Notifications on imported images

Version:
Commit id: 3ae92086cd40549cee7f5cef7aa06536a388fc72

**Comment by viktorstrate** [comment]
Might this be related to #214?

**Comment by Kjeldgaard** [comment]
I did a git reset to commit ba16fc1caa444c9d0c937593fe4324d2925d53b8 and I did not experience the problem.
