### ISSUE TITLE
Rescan unlabaled faces to try to regroup them with labeled ones

### ISSUE THREAD

**Issue by ThibaultNocchi** [photoview/photoview#274]
**Is your feature request related to a problem? Please describe.**
After an initial run, there are a *lot* of different face groups, even though some are about the same persons. Of course, this is due to the detection and all. So I start merging some manually.

**Describe the solution you'd like**
What would be great is that you could train a new model based on the labeled groups and then run the unlabeled groups against this new model to try to improve the groups.

**Additional context**
Thanks a lot for the great software! :)

**Comment by viktorstrate** [comment]
Hi @ThibaultNocchi this is actually what the "Recognice unlabeled faces" button on the People page is for, though I think it's broken at the moment, see #255

**Comment by ThibaultNocchi** [comment]
Ok thanks, that's what I initially thought but as it didn't do anything I though it was to rescan pictures for faces. That's great then, I'll be waiting for the fix! :D
