### ISSUE TITLE
Changes in sidecar md5sum not saved

### ISSUE THREAD

**Issue by fcr--** [photoview/photoview#276]
**Describe the bug**
The last md5sum version of the sidecar files is not being saved, which means that after editing a photo, it will get processed every time the scanner is run.

**To Reproduce**
1. Add a raw image with an xmp file
2. Run the scanner
3. Do a change in the xmp file (by editing the image with darktable)
4. Run the scanner again
5. Run the scanner one last time

**Expected behavior**
No changes should be detected for the image on the 5th point.

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [yes / no]
no
 - Database [e.g. mariadb 10.5]
postgresql 9.6
firefox
 - Version [e.g. 2.0.0]
87

**Additional context**
I added a debug line here, and it was showing the correct md5sum being calculated, however in the database the old value remained after calling `Save`, and no, the "could not update side car hash" error wasn't being shown:
```
diff --git a/api/scanner/process_photo.go b/api/scanner/process_photo.go
index 47baa03..74f8dc2 100644
--- a/api/scanner/process_photo.go
+++ b/api/scanner/process_photo.go
@@ -369,6 +369,7 @@ func processRawSideCar(tx *gorm.DB, imageData *EncodeMediaData, highResURL *mode
                currentFileHash = hashSideCarFile(currentSideCarPath)
                if photo.SideCarHash == nil || *photo.SideCarHash != *currentFileHash {
                        sideCarFileHasChanged = true
+                        fmt.Printf("md5 differences: %s, %s\n", *photo.SideCarHash, *currentFileHash)
                }
        } else if photo.SideCarPath != nil { // sidecar has been deleted since last scan
                sideCarFileHasChanged = true
```

**Comment by viktorstrate** [comment]
Thank you for the detailed bug report
