### ISSUE TITLE
Can't compose in docker RPi 3b+ running OMV

### ISSUE THREAD

**Issue by maranfaran** [photoview/photoview#293]
When trying to compose I get the following error; no matching manifest for linux/armv7 in the manifest list entries, when it's trying to install MariaDB 10.5. seems to be an issue with 32bit Ubuntu-based OMV. Is there another Db that can be used with 32bit?

**Comment by viktorstrate** [comment]
Try an unofficial image like `yobasystems/alpine-mariadb`
https://github.com/yobasystems/alpine-mariadb

**Comment by maranfaran** [comment]
Thanks, will try later and report back!

**Comment by maranfaran** [comment]
It worked like a charm! Thanks!
