### ISSUE TITLE
Error on scan

### ISSUE THREAD

**Issue by darrepac** [photoview/photoview#296]
Hi

I have nothing on the web interface side about the scan (no error, no progress etc)
Looking into the log, I have tons of messages similar than this one:
```
photoview_1  | 2021/04/04 10:17:29 Insert Album /photos/2008/2008_07_27 /photos/2008/2008_07_27, contains photo is true
photoview_1  | 2021/04/04 10:17:29 Failed to get ignore file, err = open /photos/2008/2008_08_05/.photoviewignore: no such file or directory
```

Is it a right issue? It is strange because I run docker-compose with sudo...

thanks

**Comment by Kjeldgaard** [comment]
Hi darrepac

Everything is fine. It simply means that the .photoviewignore file is not present in the specific folder. The output is not meant as an error more as information.

**Comment by darrepac** [comment]
ok! even if it is jumping from one folder to an other so quickly that I doubt it is scanning anything inside
So what about the scan progress? how I can see that the files are really scanned and where I am in the scan progress?

**Comment by viktorstrate** [comment]
I have removed the `Failed to get ignore file` log to declutter the logs.

> So what about the scan progress? how I can see that the files are really scanned and where I am in the scan progress?

@darrepac when you start the scanner, popups should start to appear in the lower right corner, make sure you are not using a phone though. If you don't see them there might be something blocking the websockets connection.

**Comment by darrepac** [comment]
As I have nothing in lower right corner, I guess something is going wrong...

**Comment by darrepac** [comment]
> Hi darrepac
> 
> Everything is fine. It simply means that the .photoviewignore file is not present in the specific folder. The output is not meant as an error more as information.

How can a .photoviewignore file exist if the photo volume is read-only as by default in docker-compose file??

**Comment by viktorstrate** [comment]
> As I have nothing in lower right corner, I guess something is going wrong...

Are you using a reverse proxy? that might cause problems if not configured properly.

> How can a .photoviewignore file exist if the photo volume is read-only

The ignorefiles are not created by Photoview, you manually create them if you want to ignore certan files/directories.

**Comment by darrepac** [comment]
Ok thanks for the ignore file.

About the scan, I have no reverse proxy but my pictures are on a mounted point ... I am wondering if it could be the cause of the issue.
Now it works, with NFS instead of CIFS...
