### ISSUE TITLE
Album not showing all photos

### ISSUE THREAD

**Issue by martin-vitek** [photoview/photoview#302]
**Describe the bug**
I have one album, where I'd put something around 4k photos and videos. And when I go to this album in the Photoview, only ~230 are shown. But I can see all of them on the Photo page, and when I go to the album from here (clicking on the album name on the timeline), they start loading.

**To Reproduce**
1. Have an album with few thousands photos
2. Go to the album from the Albums page
3. Scroll down to the end
4. See error (more photos are not loading)

**Expected behavior**
More photos start loading.

**Your environment:**

 - Docker
 - mariadb 10.5
 - Chrome and Firefox on Linux
 - Version 2.3.0

**Comment by viktorstrate** [comment]
> 4. See error (more photos are not loading)

Could you explain what error you get, and does it print anything in the logs as well?

**Comment by martin-vitek** [comment]
Here is a video demonstrating the issue. Sometimes I got the loading to work by resizing the browser window size.




https://user-images.githubusercontent.com/62815564/114079023-f0190a80-98a9-11eb-99e9-e265425fbf85.mp4
