### ISSUE TITLE
exiftool is left as a zombie process

### ISSUE THREAD

**Issue by ThibaultNocchi** [photoview/photoview#308]
**Describe the bug**
It seems exiftool isn't called and closed correctly. A simple `ps aux | grep 'Z' | grep exiftool` yields me 1953 zombie exiftool processes. It seems to be in line with the number of photos I recently imported. I don't have any log with this, but I can always try to spin up an instance with a small library to have less logs and find something great.

**Your environment:**
Docker latest
Postgres

**Comment by viktorstrate** [comment]
Seems like calling open and close for each media file causes problems with `go-exiftool`.
But the `exiftool.ExtractMetadata()` function can take multiple files at once, which means this could be optimized substantially by only using one instance of exiftool and batching media with [dataloaders](https://github.com/vektah/dataloaden)
