### ISSUE TITLE
Move (Detected) Face to New Group

### ISSUE THREAD

**Issue by MinchinWeb** [photoview/photoview#318]
**Is your feature request related to a problem? Please describe.**
I was reviewing the face recognition and found a face that was in the wrong group. However, I can only move that "bad" face to an existing group, so I can't create a new group.

**Describe the solution you'd like**
Ability to move faces to a new or newly created group.

**Describe alternatives you've considered**
Ignore it? Create a dumping ground (group) for all the mismatched faces?

**Additional context**
Thanks for the amazing project!

**Comment by viktorstrate** [comment]
Detach faces does exactly this :)

<img width="248" alt="Screenshot 2021-04-17 at 22 02 30" src="https://user-images.githubusercontent.com/4233458/115125483-9c54a280-9fc8-11eb-8d62-24703386a490.png">
