### ISSUE TITLE
Additional Information (Faces, Place) to Sidebar

### ISSUE THREAD

**Issue by MinchinWeb** [photoview/photoview#319]
**Is your feature request related to a problem? Please describe.**
There is no way to see where a photo was taken, when reviewing that photo.

There is no way to see who has been detected (faces) in a photo, when reviewing that photo.

**Describe the solution you'd like**
When viewing the details of a photo, it would be nice to have the detected faces and the location of the photo listed next to the EXIF information in the sidebar.

**Describe alternatives you've considered**
You can search from the faces or places view for the photo.

**Additional context**
Thanks for the amazing software!

**Comment by darkdragon-001** [comment]
Furthermore, it would be nice to show the location as well (starting from a top-level album). This is e.g. useful when showing the sidebar in _People's view_.

**Comment by viktorstrate** [comment]
@darkdragon-001 this would be very nice, I'll think of a way to incorporate it into the redesign (#382)

**Comment by viktorstrate** [comment]
Mock up of potential improvements to the sidebar, I'd like to hear your thoughts on this :)

<img width="418" alt="Screenshot 2021-09-30 at 16 36 42" src="https://user-images.githubusercontent.com/4233458/135476050-38b21e45-6589-4752-8c4c-96eb546cfdf9.png">

**Comment by cessna** [comment]
I like the addition of the Location map and the Face Detection.

**Comment by MinchinWeb** [comment]
Exciting to see things moving forward.

Conceptually, I think I would put the people and the locations together, and the downloads and shares together, because they seem like two sets of similar functions.

Should the lat/long be listed directly as part of the other EXIF data?

Also, how do you figure out what zoom to have the map at?

**Comment by viktorstrate** [comment]
@MinchinWeb thank you for the feedback, it's nice to get input on some things I haven't put much thought into myself.

> Should the lat/long be listed directly as part of the other EXIF data?

I agree

> Also, how do you figure out what zoom to have the map at?

I thought I would experiment a little and find a good default value and have the map be locked, such that you can freely scroll withouth the map zooming in/out instead.

**Comment by Zazou49** [comment]
Very nice addition, I agree !

**Comment by darkdragon-001** [comment]
> Would it be possible to include the physical location to the file itself (e.g. /mnt/photos/2021/11/20211101_134011.jpg)?

I don't think it should be shown to the user for security reasons...
