### ISSUE TITLE
add ignored path / excluded folders

### ISSUE THREAD

**Issue by SlavikCA** [photoview/photoview#32]
I decided to run photoview on my personal photo library stored on the Synology NAS.
Most of the folders on the Synology have `@eaDir` folder with some system information.
That results in the scanner erros:

```
2020/04/16 01:35:16 ERROR: Could not read file /photos/2004/2004 10 Massachusets wedding/@eaDir/Свадьба Витали Лены''''''Фото Тимофея 001.jpg@SynoEAStream: EOF
2020/04/16 01:35:16 Broadcasting notification: Scanner error
2020/04/16 01:35:16 ERROR: Could not read file /photos/2004/2004 10 Massachusets wedding/@eaDir/Свадьба Витали Лены''''''Фото Тимофея 002.jpg@SynoEAStream: EOF
2020/04/16 01:35:16 Broadcasting notification: Scanner error
```

I suggest to have some env setting (in config / db / somewhere ...), with list of ignored folders.
And perhaps have some folder there included by defaults, such as:
```
@eaDir 
#snapshot
#recycle
```

**Comment by viktorstrate** [comment]
Does any of the folders contain unwanted pictures that show up on the site after scanning?

I think the error happens when the scanner is reading an empty file. This error should just be ignored, and the file skipped.

**Comment by SlavikCA** [comment]
no unwanted photos.
It's just system files, spamming logs, 
But yes, it can be just ignored

**Comment by viktorstrate** [comment]
Okay I’ll do that for now to keep it simple

**Comment by viktorstrate** [comment]
I've fixed the false positive error notification.
I will close this as I think it would add some maybe unnessary complexity to add an _ignored folders_ system.

**Comment by iamjackg** [comment]
This would actually be a fantastic feature to have: I have three subfolders in my main `pictures` folder, but I would like PhotoView to only consider two of them.

**Comment by viktorstrate** [comment]
@iamjackg I see, I'll reconsider this.
Though I think this could also be solved with https://github.com/viktorstrate/photoview/issues/67#issuecomment-724939054

**Comment by narensankar0529** [comment]
It would be great if this was implemented because on a Synology NAS - especially if you store the media in the default directory of /photo - thumbnails are created in @eaDir directories and it would mess up photoview to scan those. So it would be ideal to allow for a way to exclude directory patterns. Most of the alternative solutions like PhotoPrism allow this feature and it makes life a lot easier on the NAS.

**Comment by Kjeldgaard** [comment]
Agree, this feature is paramount for Synology NAS users.

**Comment by Kjeldgaard** [comment]
> I've fixed the false positive error notification.
> I will close this as I think it would add some maybe unnessary complexity to add an _ignored folders_ system.

To keep it simple, one possibility could be to add a .photoview_ignore file to all folders which should be ignored by Photoview. Having said that, I do not know if this is already fixed (or will be) by #67.

**Comment by viktorstrate** [comment]
@Kjeldgaard that could be a solution.
Another similar approach (I think the Nextcloud Client does this), is to add a `.photoview_ignore` file with the same pattern matching as `.gitignore` files, then apply the rules found in the file to all subdirectories.

That would allow greater control, eg. if you don't have write permissions to a subfolder that you want to ignore, you could add an ignore file to a parent folder and exclude it from there.

**Comment by Kjeldgaard** [comment]
That is definitely a better approach, albeit not as simple.

**Comment by Kjeldgaard** [comment]
Could also be an option https://github.com/zabawaba99/go-gitignore.
