### ISSUE TITLE
Better Rounding of Exposure Values

### ISSUE THREAD

**Issue by MinchinWeb** [photoview/photoview#320]
**Describe the bug**
Some of the reported exposure times are very *exact*. I suspect this is due to floating point number issues, rather than sub-millisecond accuracy on my camera shutter.

Examples:

- 1/120.99999999879
- 1/118.00000000259601
- 1/1337.0000000359653
- 1/1525.0000000419375
- 1/59.999999988

**To Reproduce**
Add a picture to the library? (I can provide sample pictures privately if needed)

**Expected behavior**
 Display a nicely rounded exposure value.

**Screenshots**
![image](https://user-images.githubusercontent.com/1548809/115121957-a946a700-9f72-11eb-88ea-8cb9ef9a0931.png)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? Yes
 - Database MariaDB -- ghcr.io/linuxserver/mariadb:latest 
 - Browser Firefox
 - Version 2

**Additional context**
Thanks for the amazing software!

**Comment by viktorstrate** [comment]
This has already been fixed in 7f885fa63e48d7448149bed14aea555652c3c6df
