### ISSUE TITLE
Display Version Number on WebUI

### ISSUE THREAD

**Issue by MinchinWeb** [photoview/photoview#321]
**Is your feature request related to a problem? Please describe.**
In completing another ticket, I couldn't easily determine what version of the software I'm running. I know I pulled the latest version tagged with '2' from Docker Hub, but can't tell you more.

**Describe the solution you'd like**
Display the software version on the 'Settings' page of the WebUI.

**Describe alternatives you've considered**
Working backwards from Docker tags.

**Additional context**

**Comment by viktorstrate** [comment]
This would be nice and it could be automated in the building process to include what kind of build it is (proper release or edge build) as well as build date.

**Comment by viktorstrate** [comment]
Closed in #336
