### ISSUE TITLE
Bunch of ideas (sidebar, albums, timeline...)

### ISSUE THREAD

**Issue by sysoppl** [photoview/photoview#322]
**Is your feature request related to a problem? Please describe.**

Hello. This will be probably an untypical request. In the last couple of months I was searching for fast and good self hosted alternative to, obviously , Google Photos. I tried PhotoPrism (not even close), LibrePhotos (nah, good but slow and heavy AF) and now I'm here. So far, the lightness and speed of operation is very good. I'm testing it with my 13 000 files. So there is my few ideas that showed in my head right after deploying photoview. 

**Describe the solution you'd like**

- [ ] **ability to hide photo** (something like archive) 
_sometimes I made bad photo and I don't want to show it in the gallery, but it is still on HDD and I want keep it there_

- [x] **ability to close / hide sidebar**
_I know it is showing information about photo, but for me there is no need to see them. What I want is small 'i' symbol which will open information about photo_
![obraz](https://user-images.githubusercontent.com/30871217/115145338-54c62900-a051-11eb-9245-443f1d37b145.png)

- [x] **ability to show all photos from day** [because I have one folder with photos]
_well I never sort my photos from my phone, so I have one big (13000+) folder with files. Now, when I took more photos same day, there is no ability to see them without opening album page. Sadly for me, it opens whole library_
![obraz](https://user-images.githubusercontent.com/30871217/115145396-9a82f180-a051-11eb-9bfc-eca08fbcdb4f.png)

- [x] double tap open fullscreen photo
_now when I click on photo it just show more information in the sidebar. Double tap does nothing. So there's my idea: if sidebar is enabled double tap can open fullscreen, and when it's hidden single tap open fullscreen_

- [x] timeline (as in https://github.com/photoview/photoview/issues/295)
_a really good feature to search through 10+ years of photos_

- [ ] create albums (https://github.com/photoview/photoview/issues/414)
_right now album is same as mounted folder. I want to select photos and put them into album in app, not in folder_

- [x] more informations in the sidebar (https://github.com/photoview/photoview/issues/319)
_so if I really need to show informations about my photo/video most times I want to see date ✓, time ✓, location (with map), people on photo, and later the rest (metadata or something)_

- [ ] hide album name
_for someone having one big folder with photos there is no need to show album below date. Ability to hide it will be great. But this is not necessary, just an UI idea_
![obraz](https://user-images.githubusercontent.com/30871217/115145913-707efe80-a054-11eb-82ec-333370f13afc.png)

**Regardless of the above wishes, the application is really fast and light. I think I finally found a good alternative. Thanks!** 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by viktorstrate** [comment]
Hi @sysoppl, I'm happy that Photoview seems to fit your needs.
I think you've got some nice ideas here, I've added some comments on each one below:

> ability to hide photo

This can already be done using a `.photoviewignore` file, much like `.gitignore` files. See the original PR #213.
I don't know if this is what you're looking for though?

> ability to close / hide sidebar

I agree, this would be a nice addition.
I'm not quite sure on the best approach though:

- Either there should be a global button (maybe in the header) to toggle the sidebar
- Or there should be a dedicated icon on each thumbnail (I think this is what you suggest)
- Or the sidebar should appear when the thumbnail is selected, much like how it works on mobiles atm. (this is maybe my favorite)
- There might be other approaches and I'd like to hear suggestions

> ability to show all photos from day + timeline

Better date navigation is probably what I miss the most when actually using Photoview.
#230 seems related to this one as well.

> double tap open fullscreen photo

Would be very simple to implement and I've heard others suggest this as well.
Also double clicking the thumbnail in the side bar to go to full screen would be nice.

> create albums

One of the core philosophies for Photoview is that the filesystem should always be the "source of truth" (see [Introduction in Docs](https://photoview.github.io/docs/#aim-and-values).
But I'm open to a solution where "virtual" albums could be created only inside of Photoview, but with a clear distinction to actual albums from the filesystem.

> more informations in the sidebar (infobar)

I agree. There is already an issue for this at #319

> hide album name

On the original Timeline feature issue, this comment https://github.com/photoview/photoview/issues/48#issuecomment-772875545 suggested a mode where no info were shown, only a grid of images sorted by date.

I don't necessarily think that that would be the best solution, but I'd like to hear others oppinion and suggestion to an alternative viewing mode for the timeline. Or maybe just a complete design restructuring without two separate modes.

**Comment by sysoppl** [comment]
Hey, thanks for your reply. 

For the hiding option I mean something like a button so I can click it, and it will hide selected photo/video (but it will be still visible in dedicated 'hidden' album or archive). This option is in GPhotos (archive) and LibrePhotos (hide).

In my opinion, the sidebar should be an global button option - you want to see information about photo - just open it and don't close - it will stay opened for each photo. You don't? Just hide it. You want to see info about that one specific photo? Open sidebar, check info and hide it. You also mentioned mobile - I'd prefer to open fullscreen photo instead of the sidebar there. It is covering almost whole screen even after opening fullscreen and closing it. 
But as everything, this is my personal opinion.

**Comment by 6164696c** [comment]
My use case is the same as sysoppl so all of the ideas proposed are great.

+1 for virtual albums as this is the one that will really enable us to start using the solution for organising our photos that get auto backed up through the file system.

**Comment by nZeloT** [comment]
I have a similiar use case. I like photoview a lot. Theres just two features I'm missing. First, a sticky sidebar and second, the already proposed "virtual" albums, which to my understanding would resemble something like Tags (i.e. one image can be in multiple virtual albums / have tags attached to it).

**Comment by viktorstrate** [comment]
@nZeloT it's funny you should mention it, I've just pushed a commit for the redesign (#382) that adds a pin icon the the top of the sidebar.

Adding "virtual albums" in the form of tags is a great idea. I think that would be very intuitive and easy to manage.
It might even be combined with EXIF keywords (#145)

**Comment by nealhead** [comment]
> One of the core philosophies for Photoview is that the filesystem should always be the "source of truth" (see [Introduction in Docs](https://photoview.github.io/docs/#aim-and-values).
> But I'm open to a solution where "virtual" albums could be created only inside of Photoview, but with a clear distinction to actual albums from the filesystem.

I think this is really important as you may want a picture in multiple different albums and share each of those "Virtual Albums" differently.
