### ISSUE TITLE
Thumbnails not loading after selecting person on mobile (iOS)

### ISSUE THREAD

**Issue by McDowell-CSSD** [photoview/photoview#324]
**Describe the bug**
Thumbnails for images under a person load correctly via Ubuntu/Windows/macOS. Choosing a person on mobile results in blank thumbnails. Selecting the blank placeholder will show the image, but thumbnails are not shown. 

**To Reproduce**
1. Log in on iOS (any browser on iOS)
2. Choose "People"
3. Click a NAMED person
4. Thumbnails of pictures will not load.

**Expected behavior**
When selecting the person the correct page loads with blank placeholders for the thumbnails. The thumbs do not load.

**Screenshots**
See attached

**Your environment:**
iOS 14.4.2
Same issue in Chome (iOS), Safari (iOS), and Firefox (iOS)

 - Are you using Docker? [yes]
 - Database [mariadb 10.5]
 - Version [e.g. 2.0.0]

**Additional context**
None
![IMG_4611](https://user-images.githubusercontent.com/10521282/115177610-cd96a680-a08c-11eb-9f1b-d11ee02ad8d9.JPG)

**Comment by orellazri** [comment]
Just wanted to add that the same things happens to me as well, also in the Photos and Albums tabs, but when I click on Settings and then click back on Photos/Albums, the pictures all appear. When choosing a face and clicking Settings, after going back to People the whole people page re-appears and so when click a face the pictures don't show.

Running pretty much the same setup (Docker w/ mariadb)

**Comment by sanchon** [comment]
I have the same problem, don't see any obvious errors in the web inspector

**Comment by sanchon** [comment]
I have discovered that if I activate the experimental feature "Lazy image loading" (iOS Safari Settings) it works. 

I am using ios 14.5.1 and Photoview 2.3.4

**Comment by ark-** [comment]
I'm having the same issue in Safari for MacOS. Needed to go into Preferences -> Advanced -> Show Develop Menu in Toolbar, then go Develop -> Experimental Features -> Lazy Image Loading.

Hope this helps someone else. Maybe a warning about Safari not supporting lazy loading, or disabling lazy loading on this browser. I think they plan to support it eventually so it should only be a temporary solution.

**Comment by viktorstrate** [comment]
A fallback method should be in place for browsers that don't support lazy loading nativeley, but it obvisously doesn't work properly in Safari.

But thank you @sanchon and @ark- for reporting, this really helps to narrow down the bug.

**Comment by dsfsdbvxc** [comment]
Just to add to this, I'm having the same problem with images not loading, appears to be both Safari on iOS and MacOS.

Same setup, Docker + mariadb

**Comment by yllekz** [comment]
The "Lazy Image Loading" fix worked for me on iPadOS, great find.

**Comment by viktorstrate** [comment]
Fixed with #484
