### ISSUE TITLE
Fontsizes in the navigation sidebar are too big

### ISSUE THREAD

**Issue by robin-moser** [photoview/photoview#331]
**Describe the bug**
In many of the now available localization are the titles in the navigation sidebar too big and overflow.  

**To Reproduce**
Select different language (german, swedish, italian, etc)

**Expected behavior**
The titles in the sidebar should readable, either through a smaller fontsize or through text wrap. 

I don't have design/ux experience, but in my opinion, it would help if the fonsize gets reduced and the sidebar width gets a bit larger, like in the screenshot below.

**Screenshot**

<img width="624" alt="photoview-sidebar" src="https://user-images.githubusercontent.com/26254821/115326401-7f1d0100-a18d-11eb-86b4-535d540ca4be.png">

**Your environment:**
Feel free to remove and add what you think might be useful.
 - Language: German
 - Display dimension: 2560 × 1600

**Comment by viktorstrate** [comment]
solved in #380
