### ISSUE TITLE
Overflow in Photos tab does not show if display photos are landscape

### ISSUE THREAD

**Issue by MattDHill** [photoview/photoview#338]
**Describe the bug**
If you upload a group of photos, Photoview will usually show an overflow indicator (ie +100) on the right side of the batch. If, however, the display photos are landscape, meaning only 1-2 can be displayed on the screen, Photoview will not display the overflow indicator.

**To Reproduce**
1. Upload a few very large (or landscape) photos on the same date, such that only 2 can be displayed in the row.

**Expected behavior**
No overflow indicator will show.

**Screenshots**
<img width="918" alt="Screen Shot 2021-04-21 at 11 02 44 AM" src="https://user-images.githubusercontent.com/9935159/115592979-28005480-a291-11eb-8c11-158a71aada46.png">

**Comment by ILAsoft** [comment]
Same issue in mobile view - one photo is displayed and overflow is not displayed...
