### ISSUE TITLE
Photoview icon

### ISSUE THREAD

**Issue by after99** [photoview/photoview#340]
have u [icon for homer](https://github.com/NX211/homer-icons)?

**Comment by viktorstrate** [comment]
https://photos.qpqp.dk/photoview-logo.GMCX5YYT.svg

**Comment by after99** [comment]
![photoview](https://user-images.githubusercontent.com/63257521/115958233-7a927880-a4fe-11eb-81a7-95da9fc376c4.png)

**Comment by viktorstrate** [comment]
Here's a PNG version

![photoview_1024](https://user-images.githubusercontent.com/4233458/115959944-0dd3aa00-a50f-11eb-8fd6-e60337fa97a0.png)
