### ISSUE TITLE
Face recognition not working in v2.3.0

### ISSUE THREAD

**Issue by praul** [photoview/photoview#344]
Hey, I just discovered this exciting project, spun it up with the docker-compose example (using :latest). Everything seems to work so far, but face recognition does nothing. Does nothing when I click "recognize unlabeled faces", and does not detect faces by default.
Log just shows 
`photoview_1  | 2021/04/26 05:35:59 POST 200 192.168.2.111:2343/api/graphql 4.281557ms user: paul`

It also says
`2021/04/25 18:15:14 /app/graphql/models/site_info.go:24 record not found` on container startup.

Maybe I am missing something to do? Any help would be greatly appreciated. 
Btw: I changed from docker volumes to mapped folders for db and cache

mariadb 10.5
chrome
docker-image: viktorstrate/photoview:latest

Thanks a lot for any suggestions

**Comment by viktorstrate** [comment]
This is a confirmed bug in v2.3.1 only, see also the discussion at #342

For now you can use v2.3.0 until the bug is fixed.

**Comment by praul** [comment]
Thanks for the info, I will try that. Great work btw, thank you a lot.

**Comment by viktorstrate** [comment]
Thank you, I appreciate it!
