### ISSUE TITLE
Can't install on Raspberry pi 4

### ISSUE THREAD

**Issue by jaime2m1** [photoview/photoview#358]
I wanna install Photoview on a raspberry pi, I've created the docker-compose.yml, and docker and docker-compose are installed.
My issue happens when I try to run ```docker-compose up -d``` It returns ```no matching manifest for linux/arm/v7 in the manifest list entries``` 

I think that happens because my raspberry OS has the non-arm64 version. But IDK

How can I install it without the arm64 version??

**Comment by viktorstrate** [comment]
Docker images should be built for arm/v7 as well. I don't understand why you get the `no matching manifest for linux/arm/v7` error.

From the docker hub page it curtainly looks like arm/v7 builds exist for all tags.
https://hub.docker.com/r/viktorstrate/photoview/tags

What tag/version are you trying to pull?

**Comment by colinfrei** [comment]
as far as I can tell the problem is not photoview, but mariadb, which doesn't seem to build official arm/v7 builds

I was able to work around it by using a different mariadb image, specifically by replacing the line `image: mariadb:10.5` in the docker-compose.yml file with `image: ghcr.io/linuxserver/mariadb:alpine-version-10.5.9-r`

**Comment by fluxtendu** [comment]
For future references:

Actually the mariadb linuxserver image is `ghcr.io/linuxserver/mariadb:alpine-version-10.5.9-r0` 
(you can find the latest version on [this page](https://fleet.linuxserver.io/image?name=linuxserver/mariadb))

And I had to update libseccomp on the host:
```
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo apt install ./libseccomp2_2.5.1-1_armhf.deb
```
(you can find the latest version on [this page](http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/))

**Comment by yukdumboobumm** [comment]
using 

`image:lscr.io/linuxserver/mariadb`

will pull the latest image regardless of arch
