### ISSUE TITLE
Ability to correct false face detection from the sidebar.

### ISSUE THREAD

**Issue by zefy2k5** [photoview/photoview#383]
**Is your feature request related to a problem? Please describe.**
It's a hassle to fix face recognition for false positive detection. For 3000+ images to correct, it's true cumbersome.

**Describe the solution you'd like**
It's nice to have button of "Detach Face" in the info sidebar.

**Describe alternatives you've considered**
Maybe allow multiple filename in the search textbox(for "Detach Face" function) separate by comma.
This way I can copy multiple filename to text editor and put in the textbox later.

**Additional context**
Thanks for the amazing software. It's truly easy to setup and use for beginners.

**Comment by viktorstrate** [comment]
Let's continue this thread over at #319
