### ISSUE TITLE
v2.3.4 modified after release?

### ISSUE THREAD

**Issue by Jules-Bertholet** [photoview/photoview#385]
**Describe the bug**
Version 2.3.4 of Photoview was modified after release. This broke the [Photoview package for YunoHost](https://github.com/YunoHost-Apps/photoview_ynh), which I maintain.

**To Reproduce**
Download the tarball of [release v2.3.4](https://github.com/photoview/photoview/releases/tag/v2.3.4) of Photoview: its sha256 checksum has changed from `86ab44a5ed7489b02864b9ce543800118456968a4921fbff29ec9201aa83a591` to `c3b9f09e65af1d8116730d9b88b2430c71ba01e4cd8294d205056d81d822f5d0`, and GitHub shows that it was released "6 hours ago" even though it was available well before then.

**Expected behavior**
Releases are snapshots in time and are never modified after being published.

**Comment by viktorstrate** [comment]
Yes i'm sorry for the inconvenience. The "original" 2.3.4 didn't build properly and thus was never pushed to Dockerhub. Theirefore I decided to push an update replacing the old one.

I hope the YunoHost package can be solved?

**Comment by Jules-Bertholet** [comment]
Yes, I can update the checksum in the package. But changing the checksums of existing releases is always suspicious (from a security perspective), so I prefer to ask what is going on.
