### ISSUE TITLE
Cannot host behind reverse proxy on path like localhost/photos

### ISSUE THREAD

**Issue by LouDou** [photoview/photoview#390]
**Describe the bug**

I've been trying to get this app set up using docker-compose and behind an nginx reverse proxy.
My nginx instance proxies on to many apps on my server, each of them on their own path - because I'm hosting on local home network and I cannot use subdomains (there's no domain available).

My intention is to be able to host photoview under http:/[host]/photos URL; and testing locally using http://localhost/photos

However, when I've tried to configure this, the photoview app is still trying to load JS/CSS assets from the http://[host]/ root path, and there's some other strangeness going on that requesting any resource under http://[host]/photos/file.js returns the HTML from the index.html file.

**To Reproduce**

The steps required to get this going are not clear. I've tried a few different things in various permutations and none work.
I'm pasting here only the relevant parts of the config that I've tried relating to URLs and proxying; I have other docker-compose apps already working behind the proxy, and I have also got photoview to run correctly locally without the proxy.

1. photos/docker-compose.yml - using the example
-> https://github.com/photoview/photoview/blob/master/docker-compose.example.yml

2. photos/docker-compose.yml - using locally built image from git source
```
services:
  photoview:
    build:
      context: https://github.com/photoview/photoview.git
      args:
        - TARGETPLATFORM=linux/amd64
<snip>
```

3. photos/docker-compose.yml - with the `UI_PUBLIC_URL` arg:
```
  photoview:
    build:
      context: https://github.com/photoview/photoview.git
      args:
        - UI_PUBLIC_URL=/photos/
        - TARGETPLATFORM=linux/amd64
<snip>
```

4. nginx location - attempt 1
```
<snip>
location /photos {
  proxy_set_header        Host $host;
  proxy_set_header        X-Real-IP $remote_addr;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header        X-Forwarded-Proto $scheme;

  proxy_pass http://photoview;

  proxy_read_timeout      600s;
  proxy_send_timeout      600s;
}
<snip>
```

5. nginx location - attempt 2
```
<snip>
location /photos {
  proxy_set_header        Host $host;
  proxy_set_header        X-Real-IP $remote_addr;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header        X-Forwarded-Proto $scheme;

  proxy_pass http://photoview/;

  proxy_read_timeout      600s;
  proxy_send_timeout      600s;
}
<snip>
```

6. nginx location - attempt 3
```
<snip>
location /photos {
  proxy_set_header        Host $host;
  proxy_set_header        X-Real-IP $remote_addr;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header        X-Forwarded-Proto $scheme;

  proxy_pass http://photoview/photos/;

  proxy_read_timeout      600s;
  proxy_send_timeout      600s;
}
<snip>
```

**Expected behavior**

I'm expecting the app to load and work at http://[host]/photos

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? yes
 - Database mariadb 10.5
 - Browser chrome
 - Version latest / master

---

If there's any further information you require to debug this, do let me know.

Regards,
Doug.

---

Edit 1 : url markup

**Comment by viktorstrate** [comment]
I don't know if Nginx can do it but Traefik has an option called [StripPrefix](https://doc.traefik.io/traefik/middlewares/stripprefix/) that can remove the prefix before sending the request to Photoview. That way Photoview never even sees the prefix.

If your reverse proxy cannot be configured in that way, I guess it would also be possible to manually build the Docker image with a hard-coded path prefix, by setting `UI_PUBLIC_URL=/photos` at built time.
