### ISSUE TITLE
Media cache is growing over the top

### ISSUE THREAD

**Issue by stevenmache** [photoview/photoview#394]
**Describe the bug**
My mediacache folder is 90Go now (it was 2Go 3 days after install)  for a photo/video folder of 20Go. I did not add volume data since. 

**To Reproduce**
Not sure

**Expected behavior**
Have a consistent behavior for cache. Being able to purge it if necessary. 

**Your environment:**
Rpi4 8gb on yunohost 4.2

**Comment by viktorstrate** [comment]
That seems strange, I've got +150GB of media and the cache is about 16GB.
You can try to just delete the cache directory, then media will automatically be reprocessed when viewed.
