### ISSUE TITLE
Sub-albums should be visually distinct from images

### ISSUE THREAD

**Issue by darkdragon-001** [photoview/photoview#395]
**Is your feature request related to a problem? Please describe.**
Sub-albums/folders previews look exactly the same as single images which can lead to confusion that a click opens that folder instead of the displayed thumbnail.

**Describe the solution you'd like**
I suggest using some sort of _folder symbol_ (e.g. up to 4 square images instead of the current single one).

**Describe alternatives you've considered**
_None_

**Additional context**
I set up Photoview for my family photo archive and this was feedback from my dad.

**Comment by viktorstrate** [comment]
I'm not exactly sure what you mean. Here albums are rounded whereas images are square.
Am I missing something?

<img width="512" alt="Screenshot 2021-06-07 at 12 32 47" src="https://user-images.githubusercontent.com/4233458/121002304-7c518c00-c78c-11eb-80a1-724b0c213bce.png">

**Comment by darkdragon-001** [comment]
True, but the difference is so small, I didn't even notice while paying attention. Especially when you have many subfolders where the _Images_ part is not shown without scrolling. Maybe it would also be fine to add a heading _Albums_ or put the image _inside_ a folder icon or similar.
