### ISSUE TITLE
Failed to process photo - darktable killed

### ISSUE THREAD

**Issue by bw-jamescross** [photoview/photoview#403]
**Describe the bug**
When attempting to scan a directory which includes some RAW photos (.nef file format), Photoview fails to process each photo and errors with:

```
Failed to begin database transaction: failed to process photo (/photos/....nef): creating high-res cached image: encoding image using: /usr/bin/darktable-cli [/photos/....nef /app/cache/4/5/highres_..._nef_AZIdZ9Zx.jpg --core --conf plugins/imageio/format/jpeg/quality=70 --configdir /tmp/photoview-darktable742067280]: signal: killed
```

Eventually the docker process is killed and restarted.

I wonder if it has something to do with resources on my machine as I am attempting to run this on a VM with 1vCPU and 1GB memory. I am not sure what the minimum requirements are for running this app whilst scanning?

**Your environment:**
 - Are you using Docker? yes (based on docker-compose example in repo)
 - Database:mariadb 10.5
 - Version: viktorstrate/photoview:2 (2.3.4 (90963f2f))

**Comment by viktorstrate** [comment]
I think this is a memory issue as Darktable (and RAW processing in general) is quite RAM heavy.
If you can't afford to increase the memory usage try to lower the _concurrent workers_ from the Settings page to 1.
This would make sure that only one image would be processed at once.

**Comment by bw-jamescross** [comment]
Yep, our suspission was correct. I added a swap file and can now processing RAW photos.

**Comment by viktorstrate** [comment]
Good to hear, thank you for posting your solution, It might be helpful for others.
