### ISSUE TITLE
Management of images and albums via the web interface

### ISSUE THREAD

**Issue by deexno** [photoview/photoview#408]
**Is your feature request related to a problem? Please describe.**
You could say that, because my family members would like to have a central management system for their pictures (where only selected family photos are uploaded), Photoview would be exactly the right tool for this and I could use it perfectly for this purpose. Unfortunately, no folders or pictures can be created/uploaded directly via the web interface...

**Describe the solution you'd like**
A button where you can create a folder and a button where you can upload pictures/videos. And per folder and file or so again a button to delete the folders and images.

**Describe alternatives you've considered**
Nextcloud was suggested to me by someone but it's not really the right solution in my case either for several reasons.... An upload via the web interface would simply make the whole project perfect...

**Additional context**
I have now tested many such projects, I would even say all the better known ones and so far Photoview is the best and it has all the functions I would need, only this feature is missing and I (and certainly other users) would urgently need it. Thanks so far for the time you have put into this project, so far it is a 10/10 except for the missing feature.

**Comment by viktorstrate** [comment]
Thank you for writing the detailed issue and for the dissusion over at Discord, I'd like to refer further discussion to issue #216.
