### ISSUE TITLE
No Map (but images are pinned)

### ISSUE THREAD

**Issue by danmed** [photoview/photoview#409]
**Describe the bug**
I've created a map api key and the map menu has appeared, but i dont actually have a map.. just the pins.

**To Reproduce**
1. add Map API,
2. Go to Places

**Expected behavior**
Expect there to be an actual map

**Screenshots**
![image](https://user-images.githubusercontent.com/3878490/123177379-14ce5880-d47d-11eb-9f99-b4e1f6c5e386.png)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [yes]
 - Database [e.g. mariadb 10.5] mariadb External
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 2.0.0] latest

**Comment by viktorstrate** [comment]
Could this be because you didn't add your Mapbox token properly?

Are any errors printed to the web console?
