### ISSUE TITLE
How do i fix a bunch of incorrect face recognition?

### ISSUE THREAD

**Issue by danmed** [photoview/photoview#410]
i would like to basically start again with face recognition.. 

something has gone horribly wrong and my 2 kids are merged in 1 face.. i didn't do this..(i'm pretty certain).. but without going through and detaching a few thousand photos, i'm not sure how to do this without rescanning everything from scratch..

i did try going in to the face and detaching one image (in the hope that all similar matches would detach too..) but nothing happens when i click the detach button..  (same thing with the move option)

I'm still scanning the library at the moment btw.

**Comment by viktorstrate** [comment]
At the moment the "Recognize unlabeled faces" button doesn't work (See #255), but when that is fixed you should be able to press that and all unlabeled faces will be rescanned against all labeled faces.
