### ISSUE TITLE
Docker-compose doesn't work - Something went wrong  Server error: internal system error at (initialSetupWizard)

### ISSUE THREAD

**Issue by Dave4234** [photoview/photoview#413]
**Describe the bug**
docker-compose.yml file loads successfully but can't complete initial setup

**To Reproduce**
1. I created a new directory, added the docker-compose.yml file changing nothing except the port to connect to (8001 instead of 8000).
2. I run "docker-compose up -d" and it runs successfully.
3. I go to my browser (on another machine on network) and enter <ip>:8001, the Initial Setup screen shows.
4. I enter a user and password, and enter ~/Pictures as the photo location (though I tried others and it didn't like anything).
5. I click Setup Photoview. I get the error:
"Something went wrong
Server error: internal system error at (initialSetupWizard)"

**Expected behavior**
It should complete initial setup

**Screenshots**
n/a

**Your environment:**
Raspberry Pi 4 - SSHed into it
Ubuntu Desktop for Raspberry Pi installed but Desktop Environment not running during this test.
Using Docker and Docker-compose

Any ideas on where to start troubleshooting?

**Comment by viktorstrate** [comment]
First of all, you need to enter an absolute path for th ephoto location, secondly make sure that it's a path within the container.
Maybe take a look at #381

**Comment by wizardion** [comment]
I have the same error on my mac and docker.
my config is: 
![Screen Shot 2021-12-04 at 5 13 41 PM](https://user-images.githubusercontent.com/2981194/144726152-4bf18e1c-7103-47a8-9320-55583dbb9204.png)

**Comment by viktorstrate** [comment]
Your docker-compose file looks fine, I need more information if I am to help you.

- What error shows up?
- What did you enter on the setup screen?
- What is the output of the logs: `docker-compose logs`?

**Comment by wizardion** [comment]
I figured it out! I was entering the same location as in yml file `/Users/alex/Pictures/photos-test` to the **photo location** field and was getting this error message in the docker-compose logs. 

```
Warn: invalid root path: '/Users/alex/Pictures/photos-test'

stat /Users/alex/Pictures/photos-test: no such file or directory

runtime error: invalid memory address or nil pointer dereference
```
Then, when I entered the photo location as `/photos` (from yml configuration) it worked.

**Comment by viktorstrate** [comment]
No worries, it might be helpful for other people in the future.
