### ISSUE TITLE
Creating user w/o Photo path, breaks UI

### ISSUE THREAD

**Issue by ScuttleSE** [photoview/photoview#415]
**Describe the bug**
Creating user w/o Photo path, breaks UI

**To Reproduce**
1. Create a new user, but don't enter anything in the Photo path textbox
2. Click "Add User"
3. Nothing happends
4. Create user again, with same username, this time enter a Photo Path
5. MySQL Error
6. Reload page. See user created in step 1

**Comment by viktorstrate** [comment]
Thank you for reporting 👍
