### ISSUE TITLE
Renaming albums

### ISSUE THREAD

**Issue by ScuttleSE** [photoview/photoview#417]
Right now, when I log in and click Albums, I am presented with one album named "photos". Lowercase p

Either give me the ability to rename albums, or if only one Photo Path is added to a user, make the content of that folder the "root" folder for the Album view, instead of the folder itself.

**Comment by viktorstrate** [comment]
This has already been discussed here #362 but an issue was never opened.

The proposed solution was to "add an edge case for users with only one root path, and show the content of the directory directly."

**Comment by kkovaletp** [comment]
I'm not sure at which point, but it is already implemented: if you set the media library path to `/photos` and you have inside a list of media files and sub-folders, then after the 1st scan is finished, you'll see those files and folders on the 'root' level of the 'Albums' section.
I'm closing this issue as completed
