### ISSUE TITLE
could not create thumbnail cached image: png: invalid format: too much pixel data

### ISSUE THREAD

**Issue by supermamie** [photoview/photoview#423]
**Describe the bug**
On some of my pictures, I have errors like this :
```
Failed to begin database transaction: failed to process photo (/path/to/picture/download_20150106_232429.png): could not create thumbnail cached image: png: invalid format: too much pixel data
```

**Your environment:**

 - Are you using Docker? no
 - Database mysql  Ver 15.1 Distrib 10.3.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
 - Browser Firefox 89
 - Version 2.3.4

**Additional context**
If it can help, I am using YunoHost to install PhotoView.
Here is the repo for PhotoView : https://github.com/YunoHost-Apps/photoview_ynh

And here is the picture :

![download_20150106_232429](https://user-images.githubusercontent.com/693751/124610603-f307a500-de70-11eb-891f-08f1044762d4.png)

**Comment by viktorstrate** [comment]
I think your image is malformatted or uses a special encoding that the Golang image decoder does not understand. I suggest that you re-encode the image manually.

I found this related issue: https://github.com/golang/go/issues/20899
