### ISSUE TITLE
Favourites button on top of sidebar

### ISSUE THREAD

**Issue by PJ-Watson** [photoview/photoview#424]
**Describe the bug**
When using a smaller screen or at higher magnification, the button to "show only favourites" is on the layer above the sidebar.

**To Reproduce**
1. Resize the screen on a desktop browser, or open on mobile.
2. See error - screenshot attached.

**Screenshots**
![Annotation 2021-07-07 172649](https://user-images.githubusercontent.com/59647390/124803886-90d2a100-df51-11eb-890c-fbcb172fa511.jpg)

**Expected behavior**
The button should be on the same layer as the text describing its function.

**Your environment:**
 - Are you using Docker? **yes**
 - Version **2.3.4**

**Additional context**
This may already be solved by the **redesign** branch!

**Comment by viktorstrate** [comment]
Thank you for reporting. The favorites button has been redesigned in #382 and will be a part of the next release.

**Comment by PJ-Watson** [comment]
Looks like it's been fixed now - thanks for all the work!
