### ISSUE TITLE
Offset in face icons on People page

### ISSUE THREAD

**Issue by PJ-Watson** [photoview/photoview#438]
**Describe the bug**
Some of the preview icons for face groups appear to be offset from the actual detected faces in the new redesign.

**To Reproduce**
Unclear - about 17/20 of the most common faces in my library seem to suffer from this (see screenshot below). Current working theory is that it seems to be related to the orientation of the original photo, primarily affecting landscape photos.
![image](https://user-images.githubusercontent.com/59647390/126150549-c5f9d663-b68a-4d9b-ae84-33c58dc5cdfa.png)

**Expected behavior**
As before the redesign.

 - Are you using Docker? **yes**
 - Version: **Docker (edge)**

**Comment by PJ-Watson** [comment]
Narrowed down the cause to line 15 in [ui.index.src](https://github.com/photoview/photoview/blob/master/ui/src/index.css), which adds the base styles from Tailwind. Digging into that a bit more shows the problem stems from the following lines:
```
img,
video {
  max-width: 100%;
  height: auto;
}
```
Removing `max-width: 100%` in the browser console seems to completely fix the alignment issue on the People page - but I'm not sure if this has any knock on effects for the other pages. It definitely only affects images in landscape orientation!

**Comment by viktorstrate** [comment]
Nice catch, what browser are you using

**Comment by PJ-Watson** [comment]
Primarily firefox on desktop, but I've tested on chrome and the android versions as well. I've submitted a pull request for this, which should hopefully fix it.

I did wonder if it might make more sense to pre-generate the face images, and cache them somewhere for later use? I suppose it depends on the trade-off between CPU usage and network speed, but it would be the difference between transferring ~50-100kB files and ~3kB files.

**Comment by viktorstrate** [comment]
Thank you for the PR.
I don't know if it's worth it to pre-generate face thumbnails. Although it might improve quality and size of the faces but it would also add a lot of (maybe unnecessary) complexity to the project. It might change in the future however. :)
