### ISSUE TITLE
Release Version  undefined ()

### ISSUE THREAD

**Issue by FuzzyMistborn** [photoview/photoview#452]
**Describe the bug**
When looking in Settings, it says the release version is undefined.

**To Reproduce**
1. Go to Settings
2. Look at "Release Version"

**Expected behavior**
Prints the release number.

**Screenshots**
![image](https://user-images.githubusercontent.com/16689090/126690557-9f25cc8f-ecff-45d0-9388-c47178d2a809.png)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? Yes
 - Browser: Firefox
 - Version 2.3.5

**Additional context**

**Comment by DjSni** [comment]
Same on manual build Version

![image](https://user-images.githubusercontent.com/31524614/127223532-4acf3bd2-d45b-4e70-98fa-e578a5378ddd.png)

**Comment by Jorilx** [comment]
@viktorstrate I'm sorry but I'm getting this problem too, using the Docker photoview:master image... Is this expected?

**Comment by kkovaletp** [comment]
@Jorilx, do you build it or pull it from the Docker hub?
It is fine if you build it locally

**Comment by Jorilx** [comment]
@kkovaletp I'm using the `make all` method, should I use something else?

**Comment by kkovaletp** [comment]
@Jorilx, the question, I asked, is more about the image definition in the `docker-compose.yml`, used by the Makefile. By default, it is pulled from the Docker hub: `viktorstrate/photoview:2`. Please confirm that this is what you have in your Compose file, or share your image definition

**Comment by Jorilx** [comment]
@kkovaletp Sorry, I'm using `photoview:master`

**Comment by kkovaletp** [comment]
@googollee, it looks like with the recent changes in the image building pipeline, merged to the `master` branch, the UI variables are not applied to the build correctly.
Can you please compare `master` with `2.4.0` and find out the reason?

**Comment by googollee** [comment]
It seems failing a long while, with [this commit](https://github.com/photoview/photoview/commit/b2a79a4c9da03ea93f3fdfbae34153b4c310090d). When we changed to use `docker xbuild`, we missed at least setting args `VERSION` and `BUILD_DATE`. I'm checking how to bring them back now.

**Comment by kkovaletp** [comment]
> It seems failing a long while, with [this commit](https://github.com/photoview/photoview/commit/b2a79a4c9da03ea93f3fdfbae34153b4c310090d).

This is strange because the 2.4.0 release is not affected by this issue, so it was working at least at the release time.

**Comment by Jorilx** [comment]
Now I'm seeing

Release Version
master ([bb66a8b7](https://github.com/photoview/photoview/commit/bb66a8b791bc486c109cb2dd4392fd429a30c435))

Many thanks!

(Build date shows "undefined" but it's all right :) )

**Comment by googollee** [comment]
Build date is fixed by https://github.com/photoview/photoview/pull/1027.
