### ISSUE TITLE
White logo is shown when installing as web app.

### ISSUE THREAD

**Issue by Akruidenberg** [photoview/photoview#456]
**Describe the bug**
When adding photoview as web app, the application icon is white.

**Expected behavior**
The photoview logo must shown.

**Your environment:**

 - Are you using Docker? yes
 - Database  MariaDB 10.3]
 - Browser: Firefox Fenix
 - Latest version

**Comment by kkovaletp** [comment]
Currently, the PWA feature is broken: #938.
While investigating it, I noticed that the logo and other thumbnails are placed in the wrong location during the UI build, which most probably causes this bug. However, I think that fixing this issue should be done together with the #938, so I'm closing this one as duplicate, even though it was submitted earlier
