### ISSUE TITLE
Thumbnails of subalbums are not correctly aligned

### ISSUE THREAD

**Issue by hupfdule** [photoview/photoview#460]
**Describe the bug**
Subalbums with titles that are longer than the width of the thumbnail "push" the adjacent thumbnail aside.

**To Reproduce**
Open an album with multiple subalbums. The subalbums should have partly short and partly long names.

**Expected behavior**
All subalbums should be displayed in a grid so they are aligned vertically and horizontally.

**Screenshots**
Here is a screenshot that shows the problem. The thumbnails and album names are blurred, but the problem is visible.

![pv-bug](https://user-images.githubusercontent.com/36069345/127300467-f91fde68-d7d1-4a46-9782-7b65982c112d.png)

**Your environment:**
 - Version: 2.3.5

**Additional context**
Prior to the redesign the problem already existed, but the misalignment was _vertically_. Now, after the redesign, the are misaligned _horizontally_.

The subalbum names contain spaces. I think that wrapping could be applied (if necessary) at those spaces. If the subalbum name does _not_ contain spaces it should be hard wrapped at an appropriate position to not shift other albums thumbnails horizontally.

The optimal solution is if the thumbnails are aligned in a perfect grid (as would be the case if all album names are shorter than the width of the thumbnails). If some album names are longer they will inevitably enlarge the grid sizes, but that should be applied to the whole grid, not only the single thumbnail. 

A decision must be made whether to enlarge the grid in such cases horizontally or vertically or both. Enlarging vertically would be least invasive in my opinion. Therefore wrapping should be applied to the subalbums names if necessary. 

Here is an example of how I think would be the correct solution:

```
+---+   +---+   +---+
|   |   |   |   |   |
|   |   |   |   |   |
+---+   +---+   +---+
one     uno     eins
two
three

+---+   +---+   +---+
|   |   |   |   |   |
|   |   |   |   |   |
+---+   +---+   +---+
один    un      jedna

+---+   +---+   +---+
|   |   |   |   |   |
|   |   |   |   |   |
+---+   +---+   +---+
едно    veryl   yksi
        ongal
        bumna
        me
```

As you can see the first subalbum has a name that is longer than the thumbnail width. Therefore it is wrapped at spaces where necessary.

All subalbums in the same rows get the same height then.

The middle subalbum in the last rows also has a name that is too long, but doesn't contain spaces. Therefore it is wrapped at "random" places that allow the width of the grid not to change.

I hope I made clear what I mean.

**Comment by viktorstrate** [comment]
This was fixed in release `2.3.7`
