### ISSUE TITLE
Unable to save periodic scan setting

### ISSUE THREAD

**Issue by jmt-gh** [photoview/photoview#468]
**Describe the bug**
I'm unable to save the periodic scan setting. 

**To Reproduce**
1. Install via docker
2. Manually scan directory
3. Let scan finish
4. Click checkbox for "Run periodic scan"
5. Input 1 in the input box and select "Day" from the drop down
6. Unclear what to do next -- regardless of what I do (press enter, log out and log in, etc.) it never saves

**Expected behavior**
Either a save button to pop up, or the selection would be saved on edit

**Screenshots**
N/A

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? yes
 - Database mariadb 10.5
 - Browser Firefox, Firefox (Android), Chrome (Android)
 - Version 2.0.0, but Settings page shows "undefined()"

**Additional context**

**Comment by KRiedmiller** [comment]
Can confirm, same Bug in my installation. I'm also using docker and the build from 2021-07-22T16:25:13Z, version is undefined ()
None of the scan settings are saved, neither the continuous scan, nor scan interval or number of workers.

**Comment by szjani** [comment]
I have the same issue, reducing the number of workers is working though. Running viktorstrate/photoview:2 docker image.

**Comment by floco** [comment]
I have the same issue with 2.3.13 ([446ef9a4] deployed with docker.
Enable periodic scanner is not saving
