### ISSUE TITLE
Add Portuguese Support

### ISSUE THREAD

**Issue by BrnPer** [photoview/photoview#469]
Hi @viktorstrate   I hope you're doing well.

I'm really enjoying this project, it's awesome! Thank you.

I noticed that there isn't still the translation to portuguese. And portuguese is a language spoken by millions of people.

I would like to start contributing to this repo. Could I start by adding support to portuguese?

Thanks in advance

**Comment by viktorstrate** [comment]
Thank you, I appreciate your interest in the project.
It would be great if you'd help translating to Portugese. The easiest way is if you copy the `en/` directory to `pt/` and translate the json file inside it. Then I can add all the necessary code to make it work afterwards :)

https://github.com/photoview/photoview/tree/master/ui/src/extractedTranslations

**Comment by BrnPer** [comment]
Thank you for the opportunity 😊 How do you want me to add the translation? Make a fork and then a PR?

**Comment by viktorstrate** [comment]
Yes, that would be preferable 😊
