### ISSUE TITLE
Windows share mounted scanning issue

### ISSUE THREAD

**Issue by ray73864** [photoview/photoview#475]
All my photos are on a windows share, I have mounted the directory in linux using samba, I have PhotoView running in Docker and it can correctly see the mount and it tries to start scanning it.

When I tell it to start a manual scan, I see a popup in the bottom right about permission denied trying to access 'System Volume Information' and it doesn't look like the scan proceeds much after that.

Is there any way of telling Photoview to just ignore certain directories without creating a photoviewignore file in each directory?

I would create that file, except 'System Volume Information' is a special directory on windows and nobody can get inside of it, and on linux I can't even get inside it, which means I have no way to add the file.

Error message I see:

```
Scanner error
Could not read directory (/photos/System Volume Information): readdirent: permission denied
```

**Comment by viktorstrate** [comment]
You should be able to add a `.photoviewignore` at the root directory `/photos` and the rules will be propagated down to all subdirectories
