### ISSUE TITLE
"Albums" page always contains a single album that actually contains albums.

### ISSUE THREAD

**Issue by Redsandro** [photoview/photoview#485]
**Describe the bug**

You expect to see albums under the "albums" button. But you actually see the configured directory which contains the albums. So you always have to click that first.

**Screenshots**

![image](https://user-images.githubusercontent.com/1702193/131378543-2dc7774c-d5fe-4e96-851a-bea3663b0a39.png)

**Expected Result**

Either show all albums inside the directory, or - if there's some logic that requires current behavior - if there is only one item, automatically go there.

I.e. if you click on "albums" on the left bar, go here:

![image](https://user-images.githubusercontent.com/1702193/131378758-f4ef8387-0f85-4f6c-9071-0218834cea25.png)

**Comment by viktorstrate** [comment]
I have thought of the same. The biggest problem by adding a special case for users with only one root path is that there would be no way to get settings of the root album, thus it would be impossible to share the root album.

Can you think of a good solution for that, otherwise it might not be that big of a problem if the options of the root album cannot be accessed?

**Comment by Redsandro** [comment]
I don't think it's that big of a problem. Who wants to share the root album? I think this benefits a lot of people and only hurts very few people, if any.

Of course I could be wrong. In that case, a solution could be to prepend the breadcrumbs with `Albums >` and on click go to the root album.

In stead of `Media > Some Album`, you'll have `Albums > Media > Some Album`.

Now the user can click on "Albums" to go to the root album.

**Comment by Revorge** [comment]
I would really like to see this implemented - and think the proposed solution above for the root album settings would be sufficient  :)

**Comment by imler** [comment]
I would like to see this implemented.

Regarding your concerns, as someone suggested the breadcrumb could be expanded to provide an additional link to all albums.

The second solution could be leaving current behavior as default and adding a new option in settings, so users can consciously enable auto-opening if there is only one album available.

**Comment by mniehe** [comment]
What about the option of virtual albums? Being able to create albums of media that aren't all in the same directory could also get around this.

**Comment by viktorstrate** [comment]
@mniehe I think virtual albums is a little unrelated to this issue, but checkout #414

**Comment by mniehe** [comment]
Ah that ticket is better place for my comment. Thanks for pointing it out!

**Comment by khalo-sa** [comment]
Would love to see this implemented, too. It's quite irritating, at first I thought that I somehow did a mistake with mounting the directory...
