### ISSUE TITLE
Moving directories around sometimes prevents scan from working

### ISSUE THREAD

**Issue by Redsandro** [photoview/photoview#486]
**Describe the bug**

After user has moved some directories around, I can no longer run a scan. It throws the following error:

![image](https://user-images.githubusercontent.com/1702193/131379055-07d3a8e0-76ee-4862-b129-dd2ef70f1e95.png)

```
Scanner error

Could not delete old albums from database: 
Error 1451: 
Cannot delete or update a parent row: 
a foreign key constraint fails 
  (
    `photoview`.`user_albums`, 
    CONSTRAINT `fk_user_albums_album` 
    FOREIGN KEY (`album_id`) 
    REFERENCES `albums` (`id`)
  )
```

**Your environment:**

 - Are you using Docker? yes
 - Database: Mariadb 10.5
 - Browser: Brave
 - Version: tagged 2.3.4

**Comment by Redsandro** [comment]
Updated to latest tagged version 2.3.5. Same issue.

![image](https://user-images.githubusercontent.com/1702193/131379891-e57a7477-215b-4292-83aa-75a5086b685c.png)

**Comment by Redsandro** [comment]
@viktorstrate is this a duplicate of #198?

**Comment by viktorstrate** [comment]
It seems like it, thank you!
