### ISSUE TITLE
PostgreSQL ERROR: invalid input syntax for type bigint: "" (SQLSTATE 22P02)

### ISSUE THREAD

**Issue by deric** [photoview/photoview#502]
**Describe the bug**
Migration fails while setting up an empty database

```
2021/09/02 14:18:18 /home/deric/go/pkg/mod/gorm.io/driver/postgres@v1.0.8/migrator.go:294
[18.161ms] [rows:-] SELECT column_name, is_nullable, udt_name, character_maximum_length, numeric_precision, numeric_precision_radix, numeric_scale, datetime_precision FROM information_schema.columns WHERE table_catalog = 'photoview' AND table_schema = CURRENT_SCHEMA() AND table_name = 'media_exif'
2021/09/02 14:18:18 Migrating `media_exif.flash` from string to int

2021/09/02 14:18:18 /home/deric/dev/photoview/api/database/migration_exif.go:121 ERROR: invalid input syntax for type bigint: "" (SQLSTATE 22P02)
[0.459ms] [rows:0] UPDATE media_exif SET flash = NULL WHERE flash = ''
2021/09/02 14:18:18 Failed to run exif fields migration: migrating `media_exif.flash` failed: convert flash attribute empty values to NULL: ERROR: invalid input syntax for type bigint: "" (SQLSTATE 22P02)
```

**To Reproduce**
1. create DB: `createdb -p 5434 -O $(whoami) -E UTF8 photoview`
2. Switch to postgres driver in `api/.env` (assuming `ident` authentication from `localhost` configured in `pg_hba.conf`)
```
PHOTOVIEW_DATABASE_DRIVER=postgres
PHOTOVIEW_POSTGRES_URL="postgres:///photoview"
```
3. start server

**Expected behavior**
Not to see an error

 - Are you using Docker?  **no**
 - Database **postgresql 12**

**Comment by viktorstrate** [comment]
Just tested locally using Postgres.app for MacOS running PostgreSQL v13 and everything worked as expected.
My `.env` file:

```
PHOTOVIEW_DATABASE_DRIVER=postgres
PHOTOVIEW_POSTGRES_URL=postgres://viktorstrate@localhost/viktorstrate

PHOTOVIEW_LISTEN_IP=localhost
PHOTOVIEW_LISTEN_PORT=4001

PHOTOVIEW_API_ENDPOINT=http://localhost:4001/
PHOTOVIEW_UI_ENDPOINT=http://localhost:1234/

PHOTOVIEW_DEVELOPMENT_MODE=1
```

**Comment by deric** [comment]
Error comes [from here](https://github.com/photoview/photoview/blob/master/api/database/migration_exif.go#L121)

I don't think there would be a breaking change between PostgreSQL 12 and 13. `bigint` simply can't have a string value.
```
photoview=> UPDATE media_exif SET flash = NULL WHERE flash = '';
ERROR:  invalid input syntax for type bigint: ""
LINE 1: UPDATE media_exif SET flash = NULL WHERE flash = '';
```

**Comment by viktorstrate** [comment]
Right.. The reason it checks for `''` (an empty string) is that the migration converted the old way of storing the flash information, which was as a string. The problem occurs when it runs the migration on a database that doesn't need the migration.

When looking at where the function is called, it does check if the column type is either `double`, `numeric` or `real`, but if Postgres stores the column as a `bigint` that's the problem, simply adding that to the `case` would solve the problem I think.

https://github.com/photoview/photoview/blob/5eb4bf83f3fb923975683a5f1664b2350fcedfdf/api/database/migration_exif.go#L35-L45
