### ISSUE TITLE
Image counter icon not updating

### ISSUE THREAD

**Issue by ch-koehler** [photoview/photoview#524]
**Describe the bug**
The image counter icon in the timeline, displaying the number of images *not* being displayed - I assume, seems to be fixed to `total_number_of_images - 5`, instead of taking the actual number of images into account, that are not being displayed.

Example from the [demo site](https://photos.qpqp.dk/photos):
![grafik](https://user-images.githubusercontent.com/62340304/133663768-e76a977b-8008-41fa-bc0d-4561afd68f03.png)

After resizing the browser window, some pictures disappeared from the grid view, but the counter icon stays the same:
![grafik](https://user-images.githubusercontent.com/62340304/133665743-96b1e371-af38-420c-ba82-07314ca8e154.png)

**Expected behavior**
The counter updates dynamically to always display the number of images not appearing in the grid view.

**Your environment:**
https://photos.qpqp.dk/photos, running version 2.3.6 (4af3d11d)

**Additional context**

**Comment by viktorstrate** [comment]
I am currently working on rewriting the timeline completeley, and this will be fixed then :)

**Comment by ch-koehler** [comment]
Ah, good to hear! But I'm reading this a second to late. I've just entered another [bug report (525)](https://github.com/photoview/photoview/issues/525) related to the timeline :(

**Comment by viktorstrate** [comment]
No problem, they are both related to the same problem: that flex-box isn't flexible enough (see #347).

**Comment by viktorstrate** [comment]
Fixed with #530
