### ISSUE TITLE
Only 5 images per date visible when skipping through the timeline

### ISSUE THREAD

**Issue by ch-koehler** [photoview/photoview#525]
**Describe the bug**
Skipping from image to image through the timeline shows only up to 5 images per date.

**To Reproduce**
1. In the timeline, open the last previewed image of a date with more than five images, by clicking on it. Like this one on the demo site:
![grafik](https://user-images.githubusercontent.com/62340304/133667810-4d08bbb3-956e-4271-bb1f-c065dbdcef73.png)

2. Click on the right arrow, to jump to the next image from August 11th (we know there is one, the counter told us)
3. Instead of the last image of August 11th, the application jumps directly to the first image from August 10th (the nice image of the *Besseggen* - the two lakes)

**Expected behavior**
Skipping from image to image in the timeline let's you move through the *entire* collection of images, sorted by capture date / time.

**Your environment:**
The demo site https://photos.qpqp.dk/photos, running version 2.3.6 (4af3d11d).

**Additional context**
Photoview is great, keep up the good work! :)

**Comment by ch-koehler** [comment]
Just to clarify, I'm *not* talking about the max. 5 images that are displayed in the grid view / preview. What I'm referring to is when you open the image and then jump from image to image using the arrows.

**Comment by viktorstrate** [comment]
Fixed with #530
