### ISSUE TITLE
Timeline view reverse order

### ISSUE THREAD

**Issue by PJ-Watson** [photoview/photoview#531]
Just to preface by saying I'm a big fan of the new timeline - I haven't had a chance to update my own instance yet, but it looks really good on the demo! 

However, is the view on each individual day not reversed? Looking at the demo on my phone, the top of the page has photos taken before those at the bottom of the page. I think it stems from the query in `resolvers/timeline.go`, which defaults to ascending order if not specified. The fix (if this isn't intended!) should just be a case of appending one line:

```
	query := r.Database.
		Joins("JOIN albums ON media.album_id = albums.id").
		Where("albums.id IN (?)", r.Database.Table("user_albums").Select("user_albums.album_id").Where("user_id = ?", user.ID)).
		Order("YEAR(media.date_shot) DESC").
		Order("MONTH(media.date_shot) DESC").
		Order("DAY(media.date_shot) DESC").
		Order("albums.title ASC").
		Order("TIME(media.date_shot) DESC")
```

In my personal case, I've got quite a few days with a mix of photos from both a phone album and camera album - so I might also comment out the album ordering, since the links above each row seem to work really well. I suspect that will largely depend on personal preference though!

**Comment by viktorstrate** [comment]
Good catch, I'll make sure to fix this before the next release 👍
