### ISSUE TITLE
Server (syntax) Error on timeline page (postgres)

### ISSUE THREAD

**Issue by dhananjayraut** [photoview/photoview#536]
**Describe the bug**
Today I fetched latest image of photoview and recreated my existing container.
now I am getting Server error on timeline page (which is not supposed to be empty).
Albums are working fine.

**To Reproduce**
1. Go to homepage

**Expected behavior**
No error should be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/32713597/134935590-c4725ee4-674f-4d3a-b672-3899c2614654.png)

**Your environment:**
I am using docker containers on raspberry pi 4 (ubuntu)

 - Are you using Docker?
 yes

 - Database [e.g. mariadb 10.5]
 postgres:11

 firefox

 - Version [e.g. 2.0.0]
 2.3.8

**Additional context**
logs says following thing:
```
2021/09/27 14:56:15 /app/graphql/resolvers/timeline.go:37 ERROR: syntax error at or near "media" (SQLSTATE 42601)
[1.662ms] [rows:0] SELECT "media"."id","media"."created_at","media"."updated_at","media"."title","media"."path","media"."path_hash","media"."album_id","media"."exif_id","media"."date_shot","media"."type","media"."video_metadata_id","media"."side_car_path","media"."side_car_hash" FROM "media" JOIN albums ON media.album_id = albums.id WHERE albums.id IN (SELECT user_albums.album_id FROM "user_albums" WHERE user_id = 1) ORDER BY YEAR(media.date_shot) DESC,MONTH(media.date_shot) DESC,DAY(media.date_shot) DESC,albums.title ASC,TIME(media.date_shot) DESC LIMIT 200
```

**Comment by kernelkaribou** [comment]
Apologies but is this meant to be considered fixed? I am on 2.3.8 and the error for the same query persists.

![image](https://user-images.githubusercontent.com/25406580/135496787-39f06b11-47d8-4798-b103-39449ad76349.png)

**Comment by viktorstrate** [comment]
> Apologies but is this meant to be considered fixed? I am on 2.3.8 and the error for the same query persists.

The fix is not released yet

**Comment by kernelkaribou** [comment]
Understood! Thanks for the quick response and all the effort on this.

**Comment by viktorstrate** [comment]
I'm sorry that the patch for the bug hasn't been released yet. But I'd like to finish #554 before pushing the next release, I hope I will be able to push a release in the upcomming week.
