### ISSUE TITLE
Server error on upgrade to 2.3.7 (and 2.3.8)

### ISSUE THREAD

**Issue by ILAsoft** [photoview/photoview#539]
**Describe the bug**
Upon upgrading to 2.3.7 all images appear broken (thumbnails and actual previews) and error shows up:
Something went wrong
Server error: fill user albums: Error 1054: Unknown column 'albums.cover_id' in 'field list' at (myMedia)

Checking logs, I see following:
2021/09/27 11:56:12 /app/graphql/models/user.go:159 Error 1054: Unknown column 'albums.cover_id' in 'field list'
[0.861ms] [rows:0] SELECT `albums`.`id`,`albums`.`created_at`,`albums`.`updated_at`,`albums`.`title`,`albums`.`parent_album_id`,`albums`.`path`,`albums`.`path_hash`,`albums`.`cover_id` FROM `albums` JOIN `user_albums` ON `user_albums`.`album_id` = `albums`.`id` AND `user_albums`.`user_id` = 1
2021/09/27 11:56:12 WARN: error authenticating photo: fill user albums: Error 1054: Unknown column 'albums.cover_id' in 'field list'

**To Reproduce**
1. Upgrade from 2.3.6
2. Go to homepage - observe no images shown, error displayed
3. Switch to "albums" and observe same error: Error fill user albums: Error 1054: Unknown column 'albums.cover_id' in 'field list'

**Expected behavior**
No errors thrown, images shown properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1714445/134958858-ed596b93-bd69-41e5-a1c9-4463e79bb090.png)

![image](https://user-images.githubusercontent.com/1714445/134958922-3eb16a1a-981a-4559-8617-61484f666763.png)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? YES
 - Database? MariaDB
 - Browser? ANY (firefox)
 - Version? 2.3.7+

**Additional context**

**Comment by viktorstrate** [comment]
`Unknown column 'albums.cover_id'` the `cover_id` attribute was added but the database should automatically migrate and add it. Can you try to restart the container and if that doesn't work run this command:

```sh
$ docker-compose exec db mysql -uphotoview -pphoto-secret photoview -e 'SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME="albums";'
```

Does it return the `cover_id` column?

**Comment by ILAsoft** [comment]
Thank you for such an instant response, @viktorstrate! Issue was indeed on the "user" (my) side - the DB was somehow corrupted (eg even running select * from mysql.user reported errors), running mysql_upgrade was also failing. Doing a #1 hard restart of the MariaDB container, followed by #2 the mysql_upgrade -u root -p and then #3 hard restart of the photoview container resolved the issue in full and all logs clean too now. Thank you again!
