### ISSUE TITLE
Cant scroll in timeline

### ISSUE THREAD

**Issue by DjSni** [photoview/photoview#542]
**Describe the bug**
I can no longer scoll when I view images in full screen in the timeline and then go back to the timeline. The scrollbar also disappears, **I have this behaviour in Chrome-based browsers**.

**To Reproduce**

1. click on a picture in the timeline
2. click on the arrow on the right or left (a few times)
3. then click on the big X to go back to timeline
4. then try to scroll

**Expected behavior**
To scroll

**Your environment:**
 - Are you using Docker? no
 - Database MYSQL
 - Browser Brave 1.29.81 Chromium: 93.0.4577.82 (Offizieller Build) (64-Bit) 
 - Version Master branch

**Comment by viktorstrate** [comment]
I can't seem to reproduce this, is it apparent on the demo server as well?

**Comment by DjSni** [comment]
The demo server has the same problem as my manual version had, can't log in.

![20210930_wfmesDvXMlHjJC1mYlzG__8i](https://user-images.githubusercontent.com/31524614/135496614-4dafd1c4-0972-4fef-97d3-c5a1cfa0655f.png)

**Comment by viktorstrate** [comment]
Then it's a cache problem, clear your browser cache
