### ISSUE TITLE
Release Version undefined ()

### ISSUE THREAD

**Issue by DjSni** [photoview/photoview#543]
Describe the bug
When looking in Settings, it says the release and build date version is undefined.

To Reproduce

Go to Settings
Look at "Release Version"
Lock at "Build date"
Expected behavior
Prints the release number and date

Screenshots
![image](https://user-images.githubusercontent.com/31524614/127223532-4acf3bd2-d45b-4e70-98fa-e578a5378ddd.png)

Your environment:

Are you using Docker? no
Database MYSQL
Browser Brave 1.29.81 Chromium: 93.0.4577.82 (Offizieller Build) (64-Bit)
Version Master branch

**Comment by viktorstrate** [comment]
Release version is baked into the build when the CI builds the docker images, you can manually set the right environment variables before building the UI manually, but further support when manually building will not be added.
