### ISSUE TITLE
Ability to download and mark as favorite in the viewer

### ISSUE THREAD

**Issue by Marc-06** [photoview/photoview#548]
**Is your feature request related to a problem? Please describe.**
When browsing photos in full screen, you can not download the original nor add to favorite. 

**Describe the solution you'd like**
Add button overlay download original and add to favorites

**Comment by CorneliousJD** [comment]
To add to this - you should also have a little "i" icon for the info/map/ and creating share links, etc while browsing full screen view as well.

**Comment by kkovaletp** [comment]
I think that this issue should be handled by the #607 implementation, as it describes a sub-set of that issue functionality, so I'm closing this one as duplicate, even though it was submitted earlier
