### ISSUE TITLE
Filter only videos

### ISSUE THREAD

**Issue by ClumsyAdmin** [photoview/photoview#564]
**Is your feature request related to a problem? Please describe.**
Not really a problem, I think just a videos tab would be cool. I recently tried out PhotoPrism and realized that's a cool feature that I think would be a nice addition to Photoview.

**Describe the solution you'd like**
A new tab on the sidebar that says Videos and shows all the videos in your library. 

**Describe alternatives you've considered**
Or maybe a more subtle approach like with Google Photos where you search "videos" and it'll show you all your videos.

**Additional context**
N/A

**Comment by viktorstrate** [comment]
Maybe this could be done using a filtering system similar to Lightroom, maybe have a checkbox like the "Show only favorites" but for showing/hiding videos. That way the option could be easily accessible on all pages that show a gallery of media?

That would also tie niceley with #94

**Comment by kkovaletp** [comment]
I'd agree that integrating this use case into the #94 would be the best implementation here, so I'm closing this one as not planned
