### ISSUE TITLE
2FA TOTP

### ISSUE THREAD

**Issue by ClumsyAdmin** [photoview/photoview#565]
**Is your feature request related to a problem? Please describe.**
I'd like to have the ability to secure my photoview account with 2FA via TOTP.

**Describe the solution you'd like**
Give the ability to secure photoview accounts with TOTP 2FA. Not sure how hard it would be but it looks like there is already libraries made for js https://github.com/yeojz/otplib

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by viktorstrate** [comment]
https://github.com/pquerna/otp might be a good library for Go

**Comment by kkovaletp** [comment]
Adding an integration with 3rd-party auth products/services looks like a better strategy, as those products are focused on that functionality and provide more secure solutions. We have the #624 for that, so I'm closing this one as not planned
