### ISSUE TITLE
albums appear to be empty / no images are shown

### ISSUE THREAD

**Issue by rt87** [photoview/photoview#572]
**Describe the bug**
The images do not show up in some albums (s. image). The (sub)folders a there, but they appear to be empty. I regulary imported these albums and had the workers scan them, I also restarted the container, just to be safe.

Regarding the image: The folder-names **do** appear, I just cut them out manually for this bug report.

**To Reproduce**

unknown

**Expected behavior**
folder is not empty / images can be seen.

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/30858878/137402931-6194db3f-c5b8-4a18-b8e9-e55b8313b2d0.PNG)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? **yes**
 - Database **mariadb 10.6.4**
 - Browser **firefox/chrome/opera**
 - Version up-to-date

**Additional context**

**Comment by viktorstrate** [comment]
Do the directories contain any media directly? Does the scanner report them in the logs? Does the web console print any errors.

I can't really pinpoint the issue without more information.

**Comment by viktorstrate** [comment]
By directly I mean that the directory/album you are looking at contains images and not only subalbums with images in.

> `2021/10/20 12:44:27 Failed to get ignore file, err = open /photos/Sony-A6000/aaa/...../zzz/.photoviewignore: no such file or directory`

I thought I had changed it such that this logs wasn't printed anymore, what version are you running, you can see it on the bottom of the settings page?
Anyway that log is completely harmless.

> If by web console you refer to pop-ups, then no, I don't think there are any.

I mean the web console that you get by pressing `F12` and clicking on the `Console` tab. Then look for red lines.

**Comment by rt87** [comment]
any news on that?

**Comment by GitSchorsch** [comment]
Same problem here. Empty albums and a lot of messages like 

```
2021/11/06 07:18:44 Did not find auth-token cookie
2021/11/06 07:18:44 POST 200 localhost/api/graphql 1.681689ms unauthenticated
```
and 
`2021/11/05 23:30:27 Failed to get ignore file, err = open /photos/.../.photoviewignore: no such file or directory`

Running photoview version 2.3.9 with Docker on a Raspberry Pi 4.

**Comment by viktorstrate** [comment]
Is it only some albums that are empty or are no media showing up at all?

**Comment by GitSchorsch** [comment]
Only some albums are empty, most albums are fine. After a second scan, some of the empty albums are OK, but most of them are still empty.

BTW: photoview is a really cool gallery software. Small, fast and very easy to install.

**Comment by viktorstrate** [comment]
Okay, do you get any `signal killed` error logs when running the scanner?

**Comment by GitSchorsch** [comment]
I've started a new scan, but it takes some time, since there are more than 100k photos to scan. I will report when the scan is finished.

Just a small question: is it posible to suppress the message

```
2021/11/06 15:22:10 Media already scanned: /photos/.../20140615-155122.JPG
2021/11/06 15:22:10 Media already scanned: /photos/.../20130525-153714.JPG
```
This generates extremely huge logfiles...

**Comment by viktorstrate** [comment]
That's good to hear, I've removed the `Media already scanned` logs. It would probably be nice to have a more advanced logger where a log level can be set.

**Comment by rt87** [comment]
has the actual issue been resolved? After all, logs improvement is great, but I don't think it's bringing back the gallery photos ;)

**Comment by viktorstrate** [comment]
I thought the problem was the `signal killed` issue. For that case there is probably two solutions, lower the amount of concurrent workers or allocate more resources to photoview when it's scanning, as discussed in #403.

**Comment by rt87** [comment]
I'm not getting the signal killed though, and I already have only one scanner worker so as to not overstress my drives, which makes it difficult to lower ;)
