### ISSUE TITLE
Overview of shared images

### ISSUE THREAD

**Issue by armin771** [photoview/photoview#573]
**Is your feature request related to a problem? Please describe.**
If I share multiple images, I won't know which ones I shared later. Then when I don't want to share images anymore, I have to swipe each image individually to see which images are shared

**Describe the solution you'd like**
An overview in which only shared images are displayed. In which also the sharing can be stopped easily.

**Comment by kkovaletp** [comment]
We have #868, which describes this case better, so I'll close this one as a duplicate, even though it was submitted earlier
