### ISSUE TITLE
Search in "Places " should stay in "Places" and display Results on the Map

### ISSUE THREAD

**Issue by berwegera** [photoview/photoview#576]
**Is your feature request related to a problem? Please describe.**
When I use search in "Places" and select an album or photo from the search results, I am always redirected to "Albums". This is not logical for me.

Screenshot of the search in "Places" which then redirects to Albums and does not stay on the map.
![image](https://user-images.githubusercontent.com/8930645/138093609-82c8c754-99a4-45c4-86a3-f7e60dfa65e5.png)

**Describe the solution you'd like**
When I use the search in "Places" and select an album or photo from the search results, the found elements (single photo or all photos of the selected album) **should be displayed on the map** under places.

Vice versa it should be possible to jump from each album or single photo directly to the map view with the single photo or accordingly all photos of the album. 

Thanks for the great software!

**Comment by kkovaletp** [comment]
Now we have only the global search with no possibility to decide where to show the result. We have the #94 and I think that this request might be discussed under that issue discussion, so I'm closing this one as a duplicate
