### ISSUE TITLE
Add CR3 Support

### ISSUE THREAD

**Issue by pattertj** [photoview/photoview#581]
**Is your feature request related to a problem? Please describe.**
I have a Canon M50 Mark II and cannot import my images with the latest CR3 format.

**Describe the solution you'd like**
Add support for .cr3 files. I can see .cr2 support in the code so I hope it's an easy addition.

**Describe alternatives you've considered**
n/a. My camera only supports .cr3

**Comment by pattertj** [comment]
I think I can handle this fix. Is it cool if I open a branch and PR for this?

**Comment by viktorstrate** [comment]
I don't think Darktable supports CR3 yet, see https://github.com/darktable-org/darktable/issues/2170 and https://github.com/darktable-org/rawspeed/pull/271

But it looks like it's comming soon though.

**Comment by pattertj** [comment]
Appreciate the response, I'll keep an eye on this and help if I can!

**Comment by kmilos** [comment]
Why don't you just pull embedded thumbnails w/ exiftool instead of doing the heavy raw processing?

**Comment by pattertj** [comment]
Is that just a matter of installing it, per this doc?
 https://photoview.github.io/docs/installation-manual/#exif-parsing

**Comment by kmilos** [comment]
Wouldn't know, sorry. No idea how photoview actually implements exiftool support... Apart from installing it, there needs to be specific step of thumbnail extraction implemented somewhere:

https://www.google.com/search?q=exiftool+thumbnail

**Comment by kmilos** [comment]
Lupus in fabula: https://discuss.pixls.us/t/rt-extracting-embedded-jpeg-from-raw-image-using-rt/28067

**Comment by vke** [comment]
It looks like this has been fixed in the latest version of the darkable.
