### ISSUE TITLE
Update darktable to latest 3.6.1 from bullseye-backports

### ISSUE THREAD

**Issue by ivkiwi** [photoview/photoview#582]
Hello viktorstrate!

Is it possible to update current 3.4.1 version from default bullseye repository to latest 3.6.1-1 from bullseye-backports?

**Comment by ivkiwi** [comment]
I did it manually in my current docker and was able to achieve immediate processing  and  preview/hires generation of my sony a1 RAWs that are unprocessabe by 3.4.1 version.

**Comment by viktorstrate** [comment]
Yes that would be very nice, pull requests are very welcome!

**Comment by ivkiwi** [comment]
I've never done any pull requests at all. Just made some  googling how to update content inside docker container :)
I can describe what I've done if it helps somehow

**Comment by viktorstrate** [comment]
I'd like to hear what steps you took to update it.
That would save me the time of researching it myself :)

**Comment by ivkiwi** [comment]
In docker console:
apt install nano
nano /etc/apt/sources.list
Add:
deb http://deb.debian.org/debian bullseye-backports main
deb-src http://deb.debian.org/debian bullseye-backports main
apt update
apt upgrade
