### ISSUE TITLE
A lot of ideas

### ISSUE THREAD

**Issue by walking-octopus** [photoview/photoview#584]
**Is your feature request related to a problem?**
Recently I started replacing all Google services with privacy-focused alternatives and stumbled upon Photoview. It fits all my core criteria but lacks some useful features. I don't want to overwhelm you with all these ideas, but I feel some of them might be important enough to consider implementing.

**Describe the solution you'd like**:
 -  [ ] Selection and file management. It's quite important for a photo management app to quickly select several photos and add them to an album, download, or delete.
 -  [ ] Top bar in photo viewer. Most users would expect to be able to download, zoom, share, favorite, delete or open the info dialog within the photo viewer, similar to Google Photos.
 -  [ ] Local sharing. Shared albums with other users of an instance would be extremely useful. 
 -  [ ] Automatic compression. Add an option to settings to automatically compress and downscale images while scanning.
 -  [ ] Blurry photos detection. It's an essential feature for users with a lot of photos and isn't hard to implement with OpenCV.
 -  [ ] AI-assisted photo tagging. A photo tagging system with client-side TensorFlow JS suggestions in an input drop-down ordered by probability.
 -  [ ] Documents tab. Add a way to separate documents and screenshots from photos or hide them from the timeline. Similar to Google Photos "Archive".
 -  [ ] Federation. Federated shared albums on ActivityPub would create a network of Photoview instances, allowing everyone to retain their data ownership without losing the convenience of a centralized service.

**Comment by viktorstrate** [comment]
Thank you for your interest in the project and bringing some ideas to the table!

I have taken the liberty to remove some of your bullet points because they were direct duplicates of existing issues. If you want to show support for those issues I suggest that you give them a thumbs up (👍), that way it's much easier to sort by when picking what to work on next / needs attention.

> Top bar in photo viewer. I think most users would expect to be able to download, zoom, share, favorite, delete, or open the info bar within the photo viewer, similar to Google Photos.

This would be a nice addition

> Local sharing and federation. Shared albums with other users in the same instance would be very useful. It would only be more useful with federated photo sharing on ActivityPub.

I think sharing between users would be great, I know little about ActivityPub so I won't comment too much on that.

> Mobile app. An official mobile application would be extremely useful. You can take the approach of Home Assistant, and simply wrap the web UI, and add photo auto-upload.

There is an iOS app in the workings: https://github.com/photoview/photoview-ios
I am not planning on working on an Android app anytime soon, but I encourage someone else to make one.
Being that the API uses GraphQL it shouldn't be that hard/frustrating.

> Automatic compression. Add an option to settings to automatically compress and downscale images.

Thumbnails are automatically generated and highly compressed.
Also all HTTP requests are compressed when possible.

> - Blurry photos detection.
> - Documents tab. Add a way to separate documents and screenshots from photos or hide them from the timeline.

I am not sure that I want to work too much on sophisticated algorithms to automatically detect these kinds of stuff.
Object recognition might be, especially if the implementation is unobtrusive for people who don't like automatic tagging etc.

**Comment by walking-octopus** [comment]
Thanks for such a quick response! It's exciting to be able to quickly get in touch with the authors of a project.

> I have taken the liberty to remove some of your bullet points because they were direct duplicates of existing issues.

Thanks! My ideas were all over the place, so it was useful to clean them up a bit. 
> I know little about ActivityPub so I won't comment too much on that.

I don't know much about it either, but saw it could fit. Though there might be a simple library for that.
>  I am not planning on working on an Android app anytime soon, but I encourage someone else to make one.
Being that the API uses GraphQL it shouldn't be that hard/frustrating.

I'll look into it. I've always wanted to try ReactNative anyways.
> Thumbnails are automatically generated and highly compressed. Also, all HTTP requests are compressed when possible.

I meant photo compression similar to Google Photos. Like using lossless compression and downscaling to HD on all photos after scanning.
> I am not sure that I want to work too much on sophisticated algorithms to automatically detect these kinds of stuff.

I've heard it's quite easy to detect blurry photos in OpenCV. As for document detection, I first meant manually marking something as a document, moving from Timeline into a dedicated Documents tab. Although automatic recognition would be much more useful.
> Object recognition might be, especially if the implementation is unobtrusive for people who don't like automatic tagging etc.

It could be done like in Cryptee Photos, where you can manually tag a photo, but when tagging a photo below the input field there are some suggestions sorted by probability generated with client-side Machine Learning with TensorflowJS. It could be easy to implement and unobtrusive enough to be added.

**Comment by ouafnico** [comment]
Hi,

Another idea : be able to rescan a specific folder on the interface.
In place of asking to rescan all folders or all user's folder, just browsing a specific folder and ask for a rescan of this one only.

**Comment by viktorstrate** [comment]
@ouafnico that has already been suggested here: https://github.com/photoview/photoview/issues/31#issuecomment-961415023

**Comment by walking-octopus** [comment]
Should I convert some of these ideas into separate issues?

**Comment by viktorstrate** [comment]
@walking-octopus feel free to open separate issues for the first three bullet points.
I think the other ones are either out of scope of what I want photoview to be or already suggested in other issues.

**Comment by viktorstrate** [comment]
Thank you for opening the separate issues, I'll close this one then.

**Comment by walking-octopus** [comment]
It still has some less important ideas, but they are mostly irrelevant now. If I'll ever revisit them, I'll open dedicated issues.
