### ISSUE TITLE
Merge faces with same name into one facegroup

### ISSUE THREAD

**Issue by XRTce** [photoview/photoview#585]
**Is your feature request related to a problem? Please describe.**
As an user I want to be able to merge all faces with the same name into one main face group for that face

**Describe the solution you'd like**
Add a Button inside a facegroup page to merge faces with the same name into the current one

**Describe alternatives you've considered**
Bulk merge

**Comment by mniehe** [comment]
An alternative to this would be the ability to select multiple faces from the "Merge Face" menu. That way you don't need to label a multiple face groups before being able to merge them.

**Comment by viktorstrate** [comment]
@mniehe I like that idea

**Comment by nublaii** [comment]
Wouldn't it be nice if you could use auto-completion when you're labeling a face? That way you could just add pictures to existing 'faces'.

**Comment by RobHofmann** [comment]
I came here to request the same thing. I'm trying to onboard ~300.000 photos into this software at the moment (to test it out). Its currently unworkable to merge faces (i've had 100's of different groups for 1 person with tons of persons and its still adding more photos to the database).

**Comment by kkovaletp** [comment]
Names are not unique so different people might have the same name. Merging all of them based on the name/label doesn't look like a good idea.
Instead, faces multi-select at merge would work for this use case. We already have the #718, so I'm closing this one as a duplicate, even though it was submitted earlier
