### ISSUE TITLE
Search Items should be scrollable 

### ISSUE THREAD

**Issue by IceWreck** [photoview/photoview#610]
Right now search results are shown like this:

![image](https://user-images.githubusercontent.com/18102790/142973001-63c14191-42d9-4bcb-845b-317851c6e59e.png)

It isnt possible to scroll and view the next result. Instead I have to search again and click on the next photo.

**Describe the solution you'd like**

Search results should be shown like this:

![image](https://user-images.githubusercontent.com/18102790/142973221-e2f5ab5e-2337-47c7-b37f-d829791e1438.png)

**Additional context**
I used to use pigallery 2 before and it is excellent but it started crashing on me with 20k+ photos. Its indexer just cant't handle the load.
Photoview seems to be handling the same amount of pictures very well. Thanks for making this.

Search is a pain point right now tho because of this issue.

**Comment by viktorstrate** [comment]
What if the search worked as it does at the moment, but if you pressed enter you would go to a dedicated search page with advanced filters and infinite scroll? This could tie niceley with #94

**Comment by IceWreck** [comment]
> What if the search worked as it does at the moment, but if you pressed enter you would go to a dedicated search page with advanced filters and infinite scroll? This could tie niceley with #94

Hey, that sounds great.

**Comment by kkovaletp** [comment]
Closing this issue as a duplicate to the #94 then.
