### ISSUE TITLE
Android Motion Photos

### ISSUE THREAD

**Issue by Sieboldianus** [photoview/photoview#611]
This is similar to #273 

On many Android phones these days, `Motion Photos` can be created - taking a picture captures a number of frames, which are
stored in the picture as mp4 files.

They are `jpg` files with embedded short `mp4` videos.

It would be incredible if Photoview could show these videos.

There are many Packages available for extraction:

- [Online Motion-Photo-Viewer](https://github.com/dj0001/Motion-Photo-Viewer)
- [GoMoPho Google motion photos video extractor](https://github.com/cliveontoast/GoMoPho)
- [Medium: Working with Motion Photos](https://medium.com/android-news/working-with-motion-photos-da0aa49b50c)
- [libmphoto: A motion photo demuxer and remuxer](https://github.com/googleinterns/libmphoto)
- [The same feature request, just for Nextcloud photos](https://github.com/nextcloud/photos/issues/365)

I will upload a sample image later.

**Comment by viktorstrate** [comment]
I think a solution for #273 could easily be extended for this format as well.

### UI/UX discussion
I am not sure what the optimal user experience for these kinds of media would be on desktop though. On mobiles you long press and it plays the video until you release your finger, how would interaction with live photos work on desktop?

### Technical discussion (Graphql API)
Implementing this would probably require the introduction of a new media type besides `photo` and `video`, such that the UI can present "live/motion photos" in a unique way.

Alternativeley live photos should be represented as a regular `video` with the [poster](https://www.w3schools.com/tags/att_video_poster.asp) and thumbnail being the photo part, but then a huge play button would be shown on top of all live photos, and also a video player would always be shown in the sidebar or in fullscreen.

The third option is a hybrid between these, like the media would be represented as a `video` but with an extra flag to specify that it should not be considered an ordinary video. This would be nice for other frondends like the [iOS app](https://github.com/photoview/photoview-ios) such that they wouldn't have to implement custom UI to support it as it would default to be shown as a video.

**Comment by Sieboldianus** [comment]
Many thanks, Viktor. All of this sounds great. I think first supporting the playback of Motion Photos/ Live Photos would already be a big step. I do not worry that much if there is a play button in the middle of the picture. Of course, having a unique format and UX for these special formats would be the gold option, albeit requiring the biggest changes to the code base.

**Comment by viktorstrate** [comment]
### Part of discussion moved to #273

The discussion has shifted towards #273 rather than being about Android Motion Photos specifically.
To keep things organised, let's continue the general discussion about "video enhanced photos" over at #273,
and use this one for Android Motion Photos specifically.

**Comment by kkovaletp** [comment]
As from the technical perspective, there is no difference between this issue and the referenced #273, I'm closing this one as a duplicate. Hope that both will be covered by the fix for #273.
