### ISSUE TITLE
Album sort direction not working

### ISSUE THREAD

**Issue by aktentasche** [photoview/photoview#615]
**Describe the bug**
When changing the orderDirection in an folder which contains only folders, no descending sorting can be applied.

I have a folder of folders with year numbers, the initial view goes from 2000, to 2001 etc to 2021.

When I sort by title, descending so 2021 is first, nothing happens.

**To Reproduce**
1. Go to an album which contains only albums
2. Change the sorting direction

**Expected behavior**
Sorting direction is reversed

**Screenshots**
None

**Your environment:**

- Are you using Docker? yes
- Database whatever docker is starting
- Browser ungoogled-chromium
- Version 2.3.9 (72cb02d)

**Additional context**
None

**Comment by viktorstrate** [comment]
I think the sorting was only ever implemented for the media. But this should be an easy fix, since it's already implemented in the API, it just needs to be hooked up to the UI

**Comment by afrojewelz** [comment]
may i ask a feature to put an option for every album to show a customed orderDirection in presetting default? i know weburl can past this parameters anytime,but it's not convinient for mobile weburl to do that.
