### ISSUE TITLE
Places not visible on a new install

### ISSUE THREAD

**Issue by hunkyn** [photoview/photoview#619]
Found out about Photoview today. I have to say this is the best and simple implementation of photo gallery.  Tried, lychee, photoprism, piwigo, librephotos, nextcloud and some other solution that I cannot remember. This is hands down the best and easiest solution. 

**Issue:** Places is not visible on a new issue. Is there a setting that i need to enable. Or will it show up after I scan photos?

![image](https://user-images.githubusercontent.com/2773074/144948986-366bcb91-ba11-49dd-a03a-a9e240ed3a6a.png)

That is all I see.

**Comment by hunkyn** [comment]
Hello, checking to see if anyone can take a look at my issue above.

**Comment by viktorstrate** [comment]
From the docs here, https://photoview.github.io/docs/installation-docker/#environment-variables

> One thing that you might want to configure here is the MAPBOX_TOKEN variable. This is needed if you want to use map related features, like the Places page. A token can be generated for free on Mapbox's website, after you create an account.

**Comment by hunkyn** [comment]
Thanks this worked.
