### ISSUE TITLE
Response not successful: Received status code 422

### ISSUE THREAD

**Issue by juvenalandres** [photoview/photoview#620]
**Describe the bug**
I just logged into my server via web browser and this message pops-up. `Response not successful: Received status code 422`. Right after it logs me out. I've tried on my phone and it works as I never sign out on it.
This is the first time I've seen it. 

The logs show this:

```
2021/12/07 14:47:23 GET 0 photo.xxx.com/api/graphql 2m55.739439624s user: juve
2021/12/07 14:47:23 POST 200 photo.xxx.com/api/graphql 344.715µs user: juve
2021/12/07 14:47:23 POST 200 photo.xxx.com/api/graphql 1.152559ms user: juve
2021/12/07 14:47:23 Registering notification listener
2021/12/07 14:47:23 POST 422 photo.xxx.com/api/graphql 965.814µs user: juve
2021/12/07 14:47:23 Deregistering notification listener
2021/12/07 14:47:42 Did not find auth-token cookie
2021/12/07 14:47:42 POST 200 localhost/api/graphql 641.43µs unauthenticated
2021/12/07 14:48:42 Did not find auth-token cookie
2021/12/07 14:48:42 POST 200 localhost/api/graphql 891.836µs unauthenticated
2021/12/07 14:49:42 Did not find auth-token cookie
2021/12/07 14:49:42 POST 200 localhost/api/graphql 543.264µs unauthenticated
```

**Expected behavior**
Just log me in as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/18738412/145051023-bdc2185c-7529-4a79-8ef3-5926735e9752.png)

**Your environment:**

 - Docker
 - Mariadb:10.5 [e.g. mariadb 10.5]
 - Chrome
 - Version 2.3

**Comment by viktorstrate** [comment]
Strange, can you repeat it or was it a one time off kind of thing?

**Comment by juvenalandres** [comment]
Nop. The issue seems to have fixed itself. Will keep you posted if it happends again.

Thank you.
