### ISSUE TITLE
Include Searching for Tags

### ISSUE THREAD

**Issue by DaxtonD** [photoview/photoview#625]
Over the past decade, I've painstakingly assigned tags to all of my photos to assist with searching and organizing.
Initially this was done with Google Picasa, but I've moved onto Digikam.
All faces have been trained and tags have been assigned to associated faces. Places, events, locations, people, ect., have all been tagged to my photos. 
Currently, Photoview is my favorite photo manager software but I'm unable to search/find photos based on tags I've already assigned to photos. 
Please consider adding this feature.

**Comment by viktorstrate** [comment]
I think this would be covered by #94 and #145
