### ISSUE TITLE
Support for Phase One IQ3 files (IIQ format)

### ISSUE THREAD

**Issue by jhammerstad** [photoview/photoview#627]
I am using a Phase One camera with a IQ3-100 back. It would be extremely nice if this format was supported in PhotoView.

IQ250 is supported at darktable, 
However, IQ3-100 is not listed specifically, but the format should not be (much) different from IQ2 (I have been told).

I have attached an example of a iiq-file from the Phase One IQ3-100.

**Comment by jhammerstad** [comment]
GitHub will not allow me to attach iiq-files, so here is a link instead:
https://www.dropbox.com/s/i6valxa0nsuhhkh/Deliane79650.IIQ?dl=0

**Comment by kkovaletp** [comment]
This issue is going to be fixed in the scope of #996 implementation, so closing this one as not planned
