### ISSUE TITLE
Not Creating Large Thumbnails

### ISSUE THREAD

**Issue by supajason** [photoview/photoview#631]
Large thumbnails are not being created when the original file is a JPG. For a time my camera was set to JPG instead of RAW.
The issue is that when browsing it's load the >15mb thinking it's the large web optimised version.

Just add a large JPG file and hit scan

I would expect a large thumbnail be created.

![image](https://user-images.githubusercontent.com/9890014/149569200-4c4784f4-d182-4b49-b7a1-99acc8a6db7c.png)

 - Are you using Docker? Yes
 - Database mariadb 10.5
 - Version latest

I'm guessing when scanning for new media it see's the original JPG as the what would be created large thumbnail so won't create it.

**Comment by viktorstrate** [comment]
When the original image can be viewed directly in the browser, then that is used directly as the high resolution image.
