### ISSUE TITLE
Connecting to Nextcloud

### ISSUE THREAD

**Issue by gecoz** [photoview/photoview#633]
I understand that currently Photoview can connect to photos within Nextcloud to then be viewed by a Photoview user. However, I was thinking that, in order to make the software even easier and quicker to download and use, especially for those less used to coding and using Terminal, Photoview could be added as an app on Nextcloud. 

I realise that this would involve a lot of work for those wanting to do it, and I totally respect if this is not the direction you would want this application to go. However, it would also mean a larger outreach of people,  such as professional photographers, would be able to use this powerful tool.

**Comment by viktorstrate** [comment]
Hi @gecoz although this would be nice, it is certainly a very tricky if not impossible task, since Photoview and Nextcloud are made using completly different technologies.

It is unfortunatly out of scope for this project.
