### ISSUE TITLE
.avif image support

### ISSUE THREAD

**Issue by FerrahWolfeh** [photoview/photoview#634]
**Is your feature request related to a problem? Please describe.**
A while ago there was a merge request that enabled `.heif/.heic` detection and import in photoview, however, since photoview utilizes `libheif` to interact with HEIF images, it also could use the same library to decode `.avif` files

**Describe the solution you'd like**
Photoview should be able to detect/import `.avif` files like it already does with `.heic` files, possibly even using the same `libheif` library

**Describe alternatives you've considered**
I thought about converting my images to `.heif`, but the substantial loss in quality and bigger file size made me discard that idea

EDIT: autocorrect...

**Comment by viktorstrate** [comment]
Can you provide a sample image, that will make it easier to test.

**Comment by thousandsofthem** [comment]
Samples:

http://pocketmoon.ams3.digitaloceanspaces.com/upload/2022-10-08_1665253729206.avif

http://pocketmoon.ams3.digitaloceanspaces.com/upload/2022-10-08_grass.avif

https://libre-software.net/image/avif-test/

**Comment by sXperfect** [comment]
Is there any update regarding AVIF image support?

**Comment by kkovaletp** [comment]
Still in the queue(
It would be great if you can contribute the implementation of the supported files enhancement

**Comment by kkovaletp** [comment]
This issue is going to be fixed as part of the #996 implementation. Closing this one as not planned.
