### ISSUE TITLE
Opening details panel for image shows "internal system error"

### ISSUE THREAD

**Issue by ionstorm66** [photoview/photoview#637]
**Describe the bug**
When clicking on some images I get a blank preview pane with "internal system error" with no way to close it. Under it is a popup notification that says "Server error: internal system error at (media,faces,1,faceGroup,imageFaceCount)"

**Your environment:**

- OS: Unraid 6.9.2
- Docker? yes
- Database: mariadb 10.5.13
- Browser: chrome, firefox
- Version: 2.3.9 (72cb02d9)

**Comment by kkovaletp** [comment]
There is no response from the reporter. Also, it looks like the issue was caused by misconfiguration and not reproducible on our side. Closing it as not planned
