### ISSUE TITLE
Problem with upgrade to 2.3.12

### ISSUE THREAD

**Issue by muCruiser** [photoview/photoview#654]
i came from 2.3.9 and downloaded on docker 2.3.12

now i get following problem in log:

```
2022/03/03 14:52:16 Auto migration failed: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`photoview`.`#sql-alter-1-2e`, CONSTRAINT `fk_albums_parent_album` FOREIGN KEY (`parent_album_id`) REFERENCES `albums` (`id`) ON DELETE SET NULL)

2022/03/03 14:52:16 /app/database/database.go:181 Error 1452: Cannot add or update a child row: a foreign key constraint fails (`photoview`.`#sql-alter-1-2e`, CONSTRAINT `fk_albums_parent_album` FOREIGN KEY (`parent_album_id`) REFERENCES `albums` (`id`) ON DELETE SET NULL)
```

in frontend i can see 

```
Something went wrong
Server error: Error 1054: Unknown column 'media.blurhash' in 'field list' at (myTimeline)
```

i already tried to go trough 9 10 11 12, but problem stays as written above.

how can i solve this issue?

**Comment by ch-koehler** [comment]
I'm experiencing the same issue. Tried to upgrade the docker image from 2.3.9 to 2.3.12 and get the same error message in the frontend. Also the older versions 9, 10 and 11 do not work anymore now. Is there any solution yet?

**Comment by earnhardt3rd** [comment]
I run Photoview from unraid docker container and after upgrading received the same error:
![2022-10-26_13-37-22](https://user-images.githubusercontent.com/2643739/198098980-57830757-0f58-44f0-903f-d509fa9db0a7.png)

After replicating error from phpMyAdmin
![2022-10-26_13-36-19](https://user-images.githubusercontent.com/2643739/198099438-c2d10d51-d16d-4729-bdcf-2496824fbab2.png)

I was able to get past error by disabling 'foreign key check':

![2022-10-26_13-50-29](https://user-images.githubusercontent.com/2643739/198100350-ec872337-b3b7-422b-885a-e958af984bcd.png)

![2022-10-26_13-32-39](https://user-images.githubusercontent.com/2643739/198100570-c3e0ff3a-a3af-424c-b73d-e1fb8515e63d.png)

![2022-10-26_13-39-16](https://user-images.githubusercontent.com/2643739/198100602-2332e26d-17f9-4daf-9476-2fc6e3ff41ab.png)

Afterwards, Photoview completed auto migration and site was working again...

**Comment by kkovaletp** [comment]
@muCruiser, thanks for the report, and @earnhardt3rd - for the solution.
I think that this is not an issue for new users and existing users, who currently have 2.latest version running. So, I'd close it as completed having this manual solution as the final one.
