### ISSUE TITLE
Password can be changed to an empty password, but on login password field mustn't be empty

### ISSUE THREAD

**Issue by TwlyY29** [photoview/photoview#659]
Hi there,

first of all: thank you for this great piece of software! I use it to organize and access my photo library and I really love it!

Since I have photoview running in my home network unaccessable from the outside, I've been thinking about how I could make it easier for myself to access the library. My take was to set an empty password. The UI allows to change the password to an empty string. However, on login, I'm required to enter something into the password field.

I guess this is not a bug report, but something you maybe want to consider. 

Ok, bye then. Figuring out how to get access again ;-) 
Mirco

**Comment by kevin-king** [comment]
I just ran into this same issue. I fixed it by (1) deleting the user in the database and (2) by resetting the initial_setup flag. All existing settings and scans were unaffected, which was nice since scanning over 100GB of photos takes FOREVER.

```
$ docker ps
CONTAINER ID    IMAGE             ...
e088e2aca383   mariadb:10.5   ...

$ docker exec -it e088e2aca383 bash

root@e088e2aca383:/# mysql -u photoview -p photoview
<enter password>           (password is photosecret by default, check your docker-compose.yml)

MariaDB [photoview]> select * from site_info;
---------------------------------------------------------
initial_setup  periodic_scan_interval  concurrent_workers 
---------------------------------------------------------
0              0                       3              

MariaDB [photoview]> select * from users;
---------------------------------------------------------------------------------------
id  created_at                updated_at                 username   password      admin
---------------------------------------------------------------------------------------
10  2022-04-06 13:06:50.897   2022-04-06 17:24:35.167    kevin      <hidden>      1 

MariaDB [photoview]> update site_info set initial_setup=1,periodic_scan_interval=0,concurrent_workers=3;

MariaDB [photoview]> delete from users where id=10;
```

Database credentials for the above are found in docker-compose.yml
```
- MYSQL_DATABASE=photoview
- MYSQL_USER=photoview
- MYSQL_PASSWORD=photosecret
```

Now log out, back in again, and reconfigure your user with a non-empty password.
