### ISSUE TITLE
Empty albums

### ISSUE THREAD

**Issue by loranger** [photoview/photoview#661]
**Describe the bug**
Hello,

I tried to index/delete/recreate database few times but some album appears empty and does not show any thumbnail or pictures whereas those files exists

I tried to manually launch scans but once the files are _ignored_, they are never scanned anymore.
I can delete all (database and images) and setup everything again, those files would appears, but some other would be ignored.

What did I miss ?

**To Reproduce**
1. Get a fresh install
2. Set a new admin user
3. Go to settings
4. Add a source photo path
5. Launch Scan
6. Wait for the scan to finish

**Expected behavior**
I would see all my photos and videos

**Screenshots**

https://user-images.githubusercontent.com/6014/158234338-7f259278-50c4-4f18-8ab3-f650a1f22fcb.mp4

**Your environment:**
Feel free to remove and add what you think might be useful.

 - OS: Debian 11
 - Docker: 20.10.12
 - Database: mariadb:10.5
 - Browser: firefox
 - Version: 100

**Comment by rt87** [comment]
I am experiencing the same issue since quite some time now... It's the same when using a postgres database... truly annoying.

**Comment by sittzon** [comment]
Same problem, no photos shows up. I added my root photo folder, and no photos are shown at all. I checked the log for the scanner worker and it said 'Insert Album xxx, contains photo is false'.

**Comment by sittzon** [comment]
Update: I tried adding a folder in the user home folder and that seemed to work. Seems to be something about access rights.

**Comment by freefrank** [comment]
same happens here, all files have permision 666 and one or two specific album just not loading.

**Comment by okdv** [comment]
havent really dug into the details of it yet, but it looks like the graphql request has an argument `onlyRoot` that may be the culprit. when set to false, instead of true, it responds with the albums as expected.

**Comment by yashwantrkamath** [comment]
I also experiencing the same.

I just added a folder in the directory and started scan. and it went blank.

**Comment by kkovaletp** [comment]
I don't have this problem, and my best guess is that it happens when your gallery contains broken media files so that when PhotoView scans it, the job fails on such file and terminates, leaving other files in the queue not scanned, while folder structure is already scanned and converted into albums.

To prove that you could:
- check your PhotoView container log after the 1st scan. There is another issue opened, that if the scanner fails, it doesn't report an error to the log, however, you still might notice some side effects in the log
- scan your media gallery for broken files by some of tools, developed for this (like `ImageMagick` and `ffmpeg`)

**Comment by yashwantrkamath** [comment]
Thank you for your reply.

Sorry I couldn't wait till a reply. (I know, I should have, to find the issue) 

I deleted the entire db and set it up again and now it i working.

But i guess, it was something to do with docker? 

the folders disappeared from pigallery2 as well, which is also hosted in same device with same folder.

**Comment by kkovaletp** [comment]
> it was something to do with docker?

it could be the case: proposed `docker-compose` example contains many bugs and misconfiguration.
you could try the fixed version of the setup from the PR #863, where I fixed the most annoying ones. Maybe, as a side effect, this one was fixed as well...

**Comment by viktorstrate** [comment]
@kkovaletp can we close this issue, it seems to me that the problem was resolved somehow?

**Comment by kkovaletp** [comment]
Sure, I'm closing it
