### ISSUE TITLE
Change Mapbox language to user selected locale

### ISSUE THREAD

**Issue by log-time** [photoview/photoview#672]
Make Mapbox use that selected language rather than always English.

Mapbox has a guide on this here:
https://docs.mapbox.com/mapbox-gl-js/example/language-switch/

**Comment by IamSAL** [comment]
I want to take on this issue!

**Comment by kkovaletp** [comment]
@log-time, thanks for the proposal. 

I'll close this issue, as we have the #789, which has a bit better description and a PR linked.
