### ISSUE TITLE
Shared Links Require Login when using Add Home Screen in Chrome on Android

### ISSUE THREAD

**Issue by kuselfoo** [photoview/photoview#683]
**Observed behavior:**
When a shared link is added to the home screen using Chrome on an Android device, the user is asked for a login.

**Expected behavior:**
When a user adds a shared link to the home screen there should be no login required.

**Steps to reproduce:**
1. Create a shared (password protected) link for an album
2. Open that link in Google Chrome on an Android device
3. Tab on the three dots in the upper right corner and select add to home screen and confirm
4. Go to the home screen and tab the newly created icon
5. Login screen is shown instead of the gallery or password dialog

**Comment by kkovaletp** [comment]
@kuselfoo, thanks for the report.
To me, it looks like an issue with Chrome, unable to remember the password and apply it to the saved link on the Home screen. I believe that there is nothing we can do from the product perspective with this, so I'm closing the issue. If I'm wrong, please reply here with some info about how to handle such a case from the website side and I'll reopen it back.
