### ISSUE TITLE
Easier Merge Faces

### ISSUE THREAD

**Issue by danmed** [photoview/photoview#687]
It's an increasingly slow process (on an initial scan of a large library) to then go through and merge faces...

It feels like we should be able to either merge multiple faces at once, or at least get the option to merge when typing in a new label against a face isntead of having to go in to each face and click merge and then select.

**Comment by andiohn** [comment]
+1!

**Comment by kkovaletp** [comment]
I'm closing this issue as a duplicate to the #718, as it is a bit better described and already has a PR draft
