### ISSUE TITLE
Social Share Preview

### ISSUE THREAD

**Issue by simeonradivoev** [photoview/photoview#692]
**Is your feature request related to a problem? Please describe.**
It would be nice if shared links to albums and photos have defined metadata so that social media preview works.

**Describe the solution you'd like**
Stuff like the `og:title`, `og:description` and `og:image` should be defined.

**Comment by viktorstrate** [comment]
Duplicere of #77

**Comment by simeonradivoev** [comment]
Ah it seem there is already a card for it #77
