### ISSUE TITLE
Failed to process videos and photos

### ISSUE THREAD

**Issue by JVT038** [photoview/photoview#714]
**Describe the bug**
When scanning photos, various errors appear for various files:
* `Failed to begin database transaction: failed to process photo (/photos/video.mp4): failed to read metadata for original video (video.mp4): read video stream metadata: could not read video metadata (video.mp4): error running ffprobe [] exit status 1`
* `Failed to begin database transaction: failed to process photo (/photos/video.mov): could not encode mp4 video (/photos/video.mov): encoding video using: /usr/bin/ffmpeg: exit status 1`
* `Failed to begin database transaction: failed to process photo (/photos/photo.jpg): could not create thumbnail cached image: invalid JPEG format: missing 0xff00 sequence`
* `Failed to begin database transaction: failed to process photo (/photos/photo.jpg): image: unknown format`
* `Failed to begin database transaction: failed to process photo (/photos/photo.jpg): invalid JPEG format: unknown marker`
* `Failed to begin database transaction: failed to process photo (/photos/photo.jpg): could not create thumbnail cached image: invalid JPEG format: bad Huffman code`

**To Reproduce**
Just start a scan

**Expected behavior**
I expected these files to be processed normally

**Your environment:**

 - Are you using Docker? Yes
 - Database MariaDB 10.8.3
 - Browser Firefox
 - Version 2.3.12 ([0b9d04ef](https://github.com/photoview/photoview/commit/0b9d04eff2b6f896a70e8d081b6706dc4068f732))

**Comment by viktorstrate** [comment]
Can this be reproduced in the newest release (2.3.13)?
If it is possible for you to send sample files that causes these problems it would be a huge help.

**Comment by JVT038** [comment]
So I have checked all the files with these errors and turns out they were corrupted in some way and couldn't be opened by my photo and video applications. So these errors are probably caused because the files were corrupted. 
A nice thing to add however, would be to add a warning, saying that the file might be corrupted.

**Comment by kkovaletp** [comment]
Fixed by #892, so closing as completed
