### ISSUE TITLE
Openharmony application

### ISSUE THREAD

**Issue by chenguangweixi** [photoview/photoview#719]
> Note that if you have a question please use the [Discussions](https://github.com/photoview/photoview/discussions) instead
I  am  developing  an  Openharmony  application with JavaScript langue which used your library,will your library support Openharmony platform by JavaScript language? If so,I want to contribute to the Openharmony build of this library. Expecte for your repleyy!

**Comment by viktorstrate** [comment]
Please send a link to the project and more details on what the integration with Photoview would consist of.
