### ISSUE TITLE
let external users to add pictures without login

### ISSUE THREAD

**Issue by llexaxell** [photoview/photoview#732]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my friend don't want to share pictures because they need to create a new account. It will be easier to share a public url where they can upload without any login.

A optionnal nickname would be useful to identify who's upload what.

**Comment by viktorstrate** [comment]
Photoview does not allow for the user to upload directly. The reason why is explained in the [_Aim and Values_ section](https://photoview.github.io/en/docs/#aim-and-values) in the documentation.
