### ISSUE TITLE
Watch folder, so periodic scanner is unnecessary

### ISSUE THREAD

**Issue by JVT038** [photoview/photoview#741]
**Is your feature request related to a problem? Please describe.**
So currently, photoview takes a lot CPU power when scanning, because it literally rescans all of the scanned content again. 

**Describe the solution you'd like**
This could be solved by implementing a feature that watches the folder(s) and automatically detects and scans any new and/or changed files; this way, not the entire gallery, but only a few files are scanned, thus saving CPU power.

**Describe alternatives you've considered**

**Additional context**
And besides that, adding hardware acceleration to the scanning process would also be nice, to make scanning less CPU intensive.

**Comment by ouafnico** [comment]
Agreed.
Got more than 100K files, and it takes some hours every day to rescan, on 4 cpus. Actually not usuable.

Maybe it can be useful to tell photoview to scan every newly discovered folders, but just one time, and then, only rescan specifics tagged/flagged folders ?

**Comment by viktorstrate** [comment]
Duplicate of #201
