### ISSUE TITLE
Can not connect to MariaDB

### ISSUE THREAD

**Issue by Smiggel** [photoview/photoview#754]
**Describe the bug**
2022/10/09 17:54:31 WARN: Could not ping database: Could not parse mysql url: default addr for network '192.168.1.94' unknown. Will retry after 5 seconds

**To Reproduce**
1. Install linuxserver/mariadb
2. Create a DB + user for photo view
3. Install photoview stack
4. Set string to connect to the maria DB
5. Start photoview docker stack.

**Expected behavior**
Expected the docker container to start and connect to the database, like other docker containers do.

**Screenshots**

**Your environment:**
OpenMediaVault on Raspberry Pi4 with docker installation.

 - Are you using Docker? yes
 - Database: 10.x
 
**Additional context**
Docker stack layout:

> version: "3"
> 
> services:
>   photoview:
>     image: viktorstrate/photoview:2
>     restart: always
>     ports:
>       - "5000:80"
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - PHOTOVIEW_DATABASE_DRIVER=pdo_mysql
>       - PHOTOVIEW_MYSQL_URL=photoview:photoview@192.168.1.94/photoview
>       - PHOTOVIEW_LISTEN_IP=photoview
>       - PHOTOVIEW_LISTEN_PORT=80
> 
>       # Change This: to the directory where your photos are located on your server.
>       # If the photos are located at `/home/user/photos`, then change this value
>       # to the following: `/home/user/photos:/photos:ro`.
>       # You can mount multiple paths, if your photos are spread across multiple directories.
>       - /srv/dev-disk-by-uuid-6da15416-013d-4e63-930e-2bd24701f958/Pictures:/photos:ro

**Comment by viktorstrate** [comment]
`Could not parse mysql url` make sure `PHOTOVIEW_MYSQL_URL` is properly formatted.
https://github.com/go-sql-driver/mysql#dsn-data-source-name
