### ISSUE TITLE
media type detection fails on .RAF files

### ISSUE THREAD

**Issue by skwerlman** [photoview/photoview#764]
**Describe the bug**
Files with the extension `.RAF` are not processed, even if they are supported by darktable.

**To Reproduce**
1. Add a file with an (uppercase) extension such as `DSCF6170.RAF`
2. Scan files
3. An error is logged: `File is not a supported media /mnt/nextcloud/Vienna/Oct 2/DSCF6170.RAF`

**Expected behavior**
Photoview detects and scans images correctly.

**Screenshots**
N/A

**Your environment:**
 - Are you using Docker? no, AUR
 - Version `photoview 2.3.13-1`
 - `darktable 4.0.1`
 - Arch Linux in LXC

**Additional context**
The files do load when opened in the darktable gui on windows, version 4.0.1

**Comment by kkovaletp** [comment]
The latest version of Darktable processes RAF files correctly in the scope of integration with Photoview. Linking the issue with the PR, which updates the Darktable version.

**Comment by NikoKS** [comment]
Still getting same error on version 2.4.0

```
2025/08/16 08:45:35 File is not a supported media /photos/Test/DSCF6562.RAF
```

Any update on when the next release is?

**Comment by kkovaletp** [comment]
@NikoKS, we've switched to ImageMagick in the `master` branch/image - please try it, it should work for you.

Unfortunately, currently we have a big gap in the UI code quality, as we have no UI maintainer in the project and nobody can review many open UI PRs, fix a lot of UI issues, as well as update the UI dependencies to the recent versions...

I'm in the process of designing an alternative solution to overcome it, but no guarantees on the result or even time...
