### ISSUE TITLE
Cannot use SQLite database

### ISSUE THREAD

**Issue by gechandesu** [photoview/photoview#768]
Migration to database fails on initial setup.

**To Reproduce**
1. Run docker
```
docker run \
    --name photoview \
    --detach \
    --publish 127.0.0.1:3080:80 \
    --restart=always \
    -e PHOTOVIEW_DATABASE_DRIVER=sqlite \
    -e PHOTOVIEW_SQLITE_PATH=/app/data/photoview.db \
    -e PHOTOVIEW_LISTEN_IP=localhost \
    -e PHOTOVIEW_LISTEN_PORT=80 \
    -e PHOTOVIEW_MEDIA_CACHE=/app/cache \
    --volume /opt/photoview/data:/app/data \
    --volume /opt/photoview/cache:/app/cache \
    --volume /opt/photoview/photos:/photos:ro \
    viktorstrate/photoview:2
```

docker logs:
```
2022/11/01 18:10:35 Opening SQLITE database: /app/data/photoview.db?cache=shared&mode=rwc
2022/11/01 18:10:38 Migrating `media_exif.flash` from string to int

2022/11/01 18:10:38 /app/database/migration_exif.go:122 no such table: information_schema.columns
[0.192ms] [rows:0] SELECT data_type FROM information_schema.columns WHERE table_name = 'media_exif' AND column_name = 'flash';
2022/11/01 18:10:38 Failed to run exif fields migration: migrating `media_exif.flash` failed: read data_type of column media_exif.flash: no such table: information_schema.columns
2022/11/01 18:10:38 Initializing scanner queue with 1 workers
2022/11/01 18:10:38 Periodic scan interval changed: disabled
2022/11/01 18:10:38 Scan interval runner: Waiting for signal
2022/11/01 18:10:38 Scan interval runner: New ticker detected
2022/11/01 18:10:38 Scan interval runner: Waiting for signal
2022/11/01 18:10:38 Queue waiting
2022/11/01 18:10:39 Found executable worker: darktable (this is darktable-cli 3.8.1)
2022/11/01 18:10:39 Found executable worker: ffmpeg (ffmpeg version 5.0.1-3+b1 Copyright (c) 2000-2022 the FFmpeg developers)
2022/11/01 18:10:39 Found exiftool
2022/11/01 18:10:39 Initializing face detector
2022/11/01 18:10:40 Could not initialize face detector: initialize facedetect recognizer: Unable to open data/models/shape_predictor_5_face_landmarks.dat for reading.
panic: Could not initialize face detector: initialize facedetect recognizer: Unable to open data/models/shape_predictor_5_face_landmarks.dat for reading.


goroutine 1 [running]:
log.Panicf({0xe66c8c?, 0x147ce20?}, {0xc000139f20?, 0x0?, 0xc000139f70?})
	/usr/lib/go-1.18/src/log/log.go:392 +0x67
main.main()
	/app/server.go:62 +0x26d
```

You're use `information_schema.columns`, but SQLite does not have this.

**Comment by grisu48** [comment]
Same issue here, it would be so great to have sqlite3 support for photoview!

**Comment by strootje** [comment]
Your problem is because you mount `/app/data/`.
Photoview uses data models for facial recognition and those are placed in /app/data/models/. By mounting /app/data to some host folder you remove those models from the filesystem

I instead placed my sqlite file at `/app/database/photoview.db` and then mounted `/app/database` to something on the host.

Your docker script would become this:
```
docker run \
    --name photoview \
    --detach \
    --publish 127.0.0.1:3080:80 \
    --restart=always \
    -e PHOTOVIEW_DATABASE_DRIVER=sqlite \
    -e PHOTOVIEW_SQLITE_PATH=/app/database/photoview.db \
    -e PHOTOVIEW_LISTEN_IP=localhost \
    -e PHOTOVIEW_LISTEN_PORT=80 \
    -e PHOTOVIEW_MEDIA_CACHE=/app/cache \
    --volume /opt/photoview/data:/app/database \
    --volume /opt/photoview/cache:/app/cache \
    --volume /opt/photoview/photos:/photos:ro \
    viktorstrate/photoview:2
```

**Comment by Mr-Roxe** [comment]
> Your problem is because you mount `/app/data/`. Photoview uses data models for facial recognition and those are placed in /app/data/models/. By mounting /app/data to some host folder you remove those models from the filesystem
> 
> I instead placed my sqlite file at `/app/database/photoview.db` and then mounted `/app/database` to something on the host.
> 
> Your docker script would become this:
> 
> ```
> docker run \
>     --name photoview \
>     --detach \
>     --publish 127.0.0.1:3080:80 \
>     --restart=always \
>     -e PHOTOVIEW_DATABASE_DRIVER=sqlite \
>     -e PHOTOVIEW_SQLITE_PATH=/app/database/photoview.db \
>     -e PHOTOVIEW_LISTEN_IP=localhost \
>     -e PHOTOVIEW_LISTEN_PORT=80 \
>     -e PHOTOVIEW_MEDIA_CACHE=/app/cache \
>     --volume /opt/photoview/data:/app/database \
>     --volume /opt/photoview/cache:/app/cache \
>     --volume /opt/photoview/photos:/photos:ro \
>     viktorstrate/photoview:2
> ```

I meet the same problem. And I didn't mount the path `/app/data`. Can you find my error where is it. Thanks!

Here is my docker script:

```
docker run -dit \
  -e HOST_PHOTOVIEW_MEDIA_ROOT=/Pictures \
  -e HOST_PHOTOVIEW_MEDIA_FAMILY=/Albums \
  -e PHOTOVIEW_MEDIA_CACHE=/app/cache \
  -e PHOTOVIEW_DATABASE_DRIVER=sqlite \
  -e PHOTOVIEW_SQLITE_PATH=/app/database/database.db \
  -e PHOTOVIEW_LISTEN_PORT=8088 \
  -v /srv/dev-disk-by-uuid-87eaa7a6-7b58-4565-b9f5-361cf7fbda23/Pictures:/Pictures \
  -v /srv/dev-disk-by-uuid-87eaa7a6-7b58-4565-b9f5-361cf7fbda23/Albums:/Albums:ro \
  -v /root/photoview/cache:/app/cache \
  -v /root/photoview:/app/database \
  --device=/dev/dri:/dev/dri \
  --network=host \
  --restart always \
  --name photoview \
  viktorstrate/photoview
```

**Comment by kkovaletp** [comment]
@Mr-Roxe, you use `viktorstrate/photoview` image, which is resolved by docker to the `viktorstrate/photoview:latest` and refers to the latest release (from 2022) - this image doesn't contain the fix, so please use `viktorstrate/photoview:master` instead.
But before using the `master` image, please align your command with the [guide in the Readme](https://github.com/photoview/photoview#getting-started--setup-with-docker) to make sure that everything is set correctly and compatible with the requirements.

**Comment by Mr-Roxe** [comment]
> @Mr-Roxe, you use `viktorstrate/photoview` image, which is resolved by docker to the `viktorstrate/photoview:latest` and refers to the latest release (from 2022) - this image doesn't contain the fix, so please use `viktorstrate/photoview:master` instead. But before using the `master` image, please align your command with the [guide in the Readme](https://github.com/photoview/photoview#getting-started--setup-with-docker) to make sure that everything is set correctly and compatible with the requirements.

Thank you very much. I solved this problem. After changing the docker tag, it should also be noted that the SQLite database file and all upper-level directory 777 permissions must be given, otherwise the SQLite driver will prompt ·write to a read-only database·. It took me a long time to resolve the error. Besides, why not update the latest tag??

**Comment by kkovaletp** [comment]
> it should also be noted that the SQLite database file and all upper-level directory 777 permissions must be given

It is already part of the guide (step 4).
Also, giving 777 permissions is too much for the purpose of letting Photoview work: it needs the mounted folders (and their sub-folders - lower-level folders) to have `rwx` permissions for 'others' and all parent folders (upper-level ones) to have just `x` permission for 'others' - that is enough for Photoview. Of course, you can add more permissions if you need, but we don't require that.

> why not update the latest tag?

that is the decision of the owner of the repo on how the product distribution should work:
- `latest` points to the latest release
- `2` points to the latest minor release of the major version 2
- `master` points to the latest successfully built image from the `master` branch, which is the latest changes for the ongoing development cycle and future release.
