### ISSUE TITLE
memory usage - docker image of photoview

### ISSUE THREAD

**Issue by 1mfaasj** [photoview/photoview#772]
I love photoview and use the Docker variant, only a pity that it takes up a lot of memory.
maybe something can be done about that?

I've loaded all my photos into it and am using 16 percent of the 8 GB at the moment, compared to other docker images I have running, that's a lot.

thanks in advance

**Comment by Revorge** [comment]
That sounds weirdly high. How many photos are we talking? My library is about 300gb of photos and the container hovers around 100mb memory usage.

**Comment by kkovaletp** [comment]
@1mfaasj, I cannot reproduce this issue as well. On my system, it uses 159 MB of RAM.
I'll close this issue. If this is still an issue for you, please open a new issue with a detailed description of your setup, and attach logs from `photoview` service, including container start and at least 1 complete scanner job. Also, please share your compose file.
