### ISSUE TITLE
No sharing options

### ISSUE THREAD

**Issue by linuxuser332** [photoview/photoview#776]
Hi there. Photoview looks great, but having installed it onto my server, I do not see any of the photo sharing options which the website mentions?   Should the sharing options be rendered on the page somewhere?  Many thanks

**Comment by kkovaletp** [comment]
Make sure that you generate a link for the object, you want to share, by pressing the (i) button on that object instead of opening it for some other object and then clicking on the one, you're going to share. There is the #925 for this issue.

Closing this issue as not planned
