### ISSUE TITLE
Add support for .HIF format

### ISSUE THREAD

**Issue by spin6lock** [photoview/photoview#785]
**Is your feature request related to a problem? Please describe.**
According to [fileinfo.com](https://fileinfo.com/extension/hif), .hif is variation of HEIC format, with support of 4:2:2 depth per color channel.

**Describe the solution you'd like**
https://github.com/photoview/photoview/blob/master/api/scanner/media_type/media_type.go#L154 add one more line:
```golang
".hif": TypeHeic,
```

**Describe alternatives you've considered**
Maybe add new type `TypeHIF` ?  

**Additional context**
[Sony Camera Support of HEIF](https://support.d-imaging.sony.co.jp/support/ilc/heif/01/en/index.html)

**Comment by kkovaletp** [comment]
@jordy2254 please confirm that adding this format to Photoview is as easy, as in the Solution section of the issue. Will it then be fully supported or is this a hack and there is a better way to add it?

**Comment by kkovaletp** [comment]
This issue is going to be fixed in the scope of #996 implementation. Closing this one as not planned.
