### ISSUE TITLE
Perform scan on filesytem changes

### ISSUE THREAD

**Issue by AlexanderNelzin** [photoview/photoview#793]
**Is your feature request related to a problem? Please describe.**
Periodic scanning of a big library takes a lot of time and server resources. It's better to process only new images and videos.

**Describe the solution you'd like**
Implement filesystem changes event-based scanning. If if some file is written, execute scan for this file, or folder, where it is located.

**Describe alternatives you've considered**
Allow trigger by command line command. With this command it will be possible to implement processing of inotify events externally.

**Comment by viktorstrate** [comment]
#792 works on this
