### ISSUE TITLE
[README UPDATE] Set up development environment and work in progress status

### ISSUE THREAD

**Issue by tkapias** [photoview/photoview#794]
After a few hours testing Photoview there is too much problems with the setup and some missing features. I had issues with the procedure without docker, with libheif compilation, go-face execution and the fact that there is no frontend upload feature...

I think that it is still in early developement, but the REAME does not state it directly. I will come back in a few month to check.

I'm writing this issue to leave my installation notes that may help other users without docker. It works on Debian 11 with mysql and nginx as a reverse proxy. 

1. Install go-lang in the latest version:

``` bash 
cd $HOME
wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.5.linux-amd64.tar.gz
rm -Rf go1.19.5.linux-amd64.tar.gz
# follow instruction to export PATH env values
```

2. Install Debian 11 dependancies:

``` bash
sudo apt-get install libdlib-dev libblas-dev libatlas-base-dev liblapack-dev libjpeg62-turbo-dev libheif-dev
sudo apt-get install ffmpeg exiftool darktable
```

3. Install latest LTS Nodejs & NPM before v17 with NVM for the user that will run Photoview:

``` bash
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
nvm install v16.19.0
nvm alias default v16.19.0
nvm use default
# add export values to your user .bashrc
#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

4. Find a place to setup Photoview, clone it, build it in a app/ folder:

``` bash
git clone --depth=1 https://github.com/photoview/photoview
mkdir app && cd app/
cp ../photoview/ui/package*.json .
npm ci --omit=dev --ignore-scripts
cp -r ../photoview/ui/* .
npm run build -- --base=/
export CGO_ENABLED=1
go env
cp ../photoview/api/go.* .
sed -i 's/libheif v1.12.0/libheif v1.11.0/g' go.mod
go get github.com/photoview/photoview/api/routes
go mod download
sed -i 's/-march=native//g' $HOME/go/pkg/mod/github.com/\!kagami/go-face*/face.go
go install github.com/mattn/go-sqlite3 github.com/Kagami/go-face
cp -r ../photoview/api/* .
go build -v -o photoview .
cp -r ../photoview/api/data/ ./data/
cp -r ./dist/ ./ui/
```

5. create an .env file in the app/ folder:

``` bash
PHOTOVIEW_DATABASE_DRIVER=mysql
PHOTOVIEW_MYSQL_URL=username:password@tcp(localhost)/databasename
PHOTOVIEW_LISTEN_IP=localhost
PHOTOVIEW_LISTEN_PORT=8095
PHOTOVIEW_MEDIA_CACHE=$HOME/media_cache
PHOTOVIEW_SERVE_UI=1
PHOTOVIEW_UI_PATH=$HOME/app/ui
PHOTOVIEW_DEVELOPMENT_MODE=0
```

6. create the cache folder and run:

``` bash
mkdir $HOME/media_cache
cd $HOME/app/
./photoview
```

7. modify your nginx setup to serve:

```nginx
location / {
    proxy_pass http://127.0.0.1:8095;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_buffers           4 32k;
    client_max_body_size    500m;
    client_body_buffer_size 128k;
}
```

**Comment by viktorstrate** [comment]
There's a guide on the website here:
https://photoview.github.io/en/docs/installation-manual/

**Comment by tkapias** [comment]
Thank you. The link is on the Github page but I missed it somehow. I was focused on the informations in the repository.

Seeing this it would have helped me with the nodejs version.

But there are still an issue to install libheif 1.12 with nodejs. It may be because you installed it from a PPA repository first and I have to use Debian repos, but downgrading to 1.11 in the project worked.

I will try again later.
