### ISSUE TITLE
Raw Files (DNG, CRW) not being imported

### ISSUE THREAD

**Issue by jckso** [photoview/photoview#800]
**Describe the bug**
When raw photos (dng and crw) are present in my library they are not properly imported. 

**To Reproduce**
1. Have DNG or CRW photos present in file structure
2. Run a Scan
3. Log will contain File is not a supported media /photos/IMG_****.DNG

**Expected behavior**
Raw photos should be properly imported.

**Screenshots**
<img width="1150" alt="Screen Shot 2023-02-11 at 11 07 29 PM" src="https://user-images.githubusercontent.com/64824845/218294300-32b8be70-f7a8-4f3c-ad2d-f8f58db6b521.png">

**Your environment:**
TrueNAS Scale

 - Are you using Docker? [yes / **no**]
 - Database [e.g. mariadb 10.5]: Postgres 
 - Browser [e.g. chrome, safari:] Firefox
 - Version [e.g. 2.0.0] 2.3.13

**Comment by WindLi001** [comment]
According to api\scanner\media_type\media_type.go, IsSupported(),
```
	if executable_worker.DarktableCli.IsInstalled() && imgType.IsRaw() {
		return true
	}
```
 to support raw file, the Darktable is necessary.  Darktable is included in the docker image of photoview. But if you don't use docker, you have to install it by yourself.
