### ISSUE TITLE
Cannot start Docker Compose container

### ISSUE THREAD

**Issue by FrankNoWar** [photoview/photoview#803]
**Describe the bug**
Executing `$ docker compose up -d` produces the following error:
`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/lib/gnupg: invalid argument`

**To reproduce**
1. Create _docker-compose.yaml_ file
2. Start Docker container
3. Wait for download and extraction
4. Get aforementioned error message

**Expected behavior**
The start of the container

**Your environment:**
Feel free to remove and add what you think might be useful.

 - **OS:** archlinux (fully up to date)
 - **Are you using Docker?** yes
 - **Database:** mariadb:10.5
 - **Version:** 2 (default)

**Additional information**
The only line I did change in the YAML file is the photo volume (`/data/media/photos/photoview:/photos:ro`)

**Comment by viktorstrate** [comment]
Closing as this doesn't sound like a problem with Photoview. Feel free to reply with a comment if you think otherwise
