### ISSUE TITLE
Periodic scanner - Scans entire library

### ISSUE THREAD

**Issue by DaxtonD** [photoview/photoview#806]
Perhaps this isn't as much of a bug as it is a suggestion?
When I enable the periodic scanner (one of my favorite features of Photoview) It re-scans my entire photo library.
If I set it to something like 1 minute, the scanner will continuously run as the library is larger than it can complete scanning in 1 minute. This hogs a lot of system resources to scan the entire library to look for changes.

Is there another way to find newly added files without having to rescan the entire library?

Installed via Docker on Unraid using viktorstrate/photoview:edge repository.

**Comment by viktorstrate** [comment]
#792 is working on this
