### ISSUE TITLE
Login does not work when ui is served by the api.

### ISSUE THREAD

**Issue by gabrielgio** [photoview/photoview#812]
**Describe the bug**

Login works fine when I run `npm start` and `go run server.go` into two difference process, but it does not work when backend is serving the ui (`PHOTOVIEW_SERVE_UI=1`).

Working configuration:
```
PHOTOVIEW_DATABASE_DRIVER=sqlite
PHOTOVIEW_SQLITE_PATH=photoview.db
PHOTOVIEW_LISTEN_IP=localhost
PHOTOVIEW_LISTEN_PORT=4001
PHOTOVIEW_API_ENDPOINT=http://localhost:4001/
PHOTOVIEW_UI_ENDPOINT=http://localhost:1234/
PHOTOVIEW_SERVE_UI=0
PHOTOVIEW_UI_PATH=/home/gabrielgio/Git/photoview/ui/dist
PHOTOVIEW_DEVELOPMENT_MODE=1
```

Not working configuration (ui served by backend):
```
PHOTOVIEW_DATABASE_DRIVER=sqlite
PHOTOVIEW_SQLITE_PATH=photoview.db
PHOTOVIEW_LISTEN_IP=localhost
PHOTOVIEW_LISTEN_PORT=4001
PHOTOVIEW_API_ENDPOINT=http://localhost:4001/
PHOTOVIEW_UI_ENDPOINT=http://localhost:1234/
PHOTOVIEW_SERVE_UI=1
PHOTOVIEW_UI_PATH=/home/gabrielgio/Git/photoview/ui/dist
PHOTOVIEW_DEVELOPMENT_MODE=1
```

The cookie is not being set on the frontend when ui is being served by the backend even on a successful login.

**To Reproduce**
1. Go to `ui` folder
2. Copy `exemple.env` to `.env`
4. Run `npm run build`
4. Go to `api` folder
6. Copy `exemple.env` to `.env`
7. Edit `.env` to use sqlite and serve UI (as showed above)
8. Run `go run server.go`

**Expected behavior**
Login works and `auth-token` cookie is set.

**Your environment:**

 - Are you using Docker? no
 - Database sqlite3
 - Browser Firefox 109.0.1 and qutebrowser v2.5.2
 - OS Alpine Linux 3.17
 - npm 9.1.2 and node 19.7.0
 - go 1.19.6

**Additional context**

Since the cookie is set by the frontend I have no expertise to debug it.

**Comment by viktorstrate** [comment]
See this guide for manual setup: https://photoview.github.io/en/docs/installation-manual/

**Comment by gabrielgio** [comment]
I have seem the that manual, I have tried it and many other options with the env file.

The problems is always the same. The cookie is not properly set when ui when it is served by the backend.

Following exactly as it says in the manual installation, I have:

The login works just fine.
![image](https://user-images.githubusercontent.com/4411113/222983051-1b760acb-bb24-4250-afe3-77c8c19b4829.png)

The response is html (which I think it the intended behaviour from what I could understand of the source code).
![image](https://user-images.githubusercontent.com/4411113/222983130-8c0ff719-2817-46c3-9bad-c1acd864683b.png)

But the cookie is not set
![image](https://user-images.githubusercontent.com/4411113/222983177-bbfde30d-1851-48d2-b481-e39fa5f80e9f.png)


This is my env file now. Using `/opt/photoview/app` folder tree (which I think is not relevant but I followed as it says).
```
PHOTOVIEW_DATABASE_DRIVER=sqlite

PHOTOVIEW_SERVE_UI=1
PHOTOVIEW_PUBLIC_ENDPOINT=http://localhost:4001/
```

I used a database which was populated already, but I don't see it as a problem.

<details><summary>/op/photoview/app tree</summary>
<code>
.
├── data
│   └── models
│       ├── dlib_face_recognition_resnet_model_v1.dat
│       ├── mmod_human_face_detector.dat
│       └── shape_predictor_5_face_landmarks.dat
├── photoview
├── photoview.db
├── tree
└── ui
    ├── apple-touch-icon.png
    ├── assets
    │   ├── AlbumBoxes.c33b8b65.js
    │   ├── AlbumPage.5cbd6d8a.js
    │   ├── AlbumsPage.30c5f6c2.js
    │   ├── Dropdown.dfafc5c7.js
    │   ├── InitialSetupPage.3a38d666.js
    │   ├── Input.17d41380.js
    │   ├── LoginPage.a7ff8ca4.js
    │   ├── MapboxMap.15d75db3.js
    │   ├── MapboxMap.df5cc615.css
    │   ├── MediaGallery.bfb3c2f1.js
    │   ├── MessageBox.228bd6e0.js
    │   ├── PlacesPage.3b3810dd.js
    │   ├── SettingsPage.9fbfb6e3.js
    │   ├── SharePage.4c9ba83d.js
    │   ├── Table.705270c2.js
    │   ├── TimelinePage.9e618554.js
    │   ├── closeSidebarIcon.5ca8e681.svg
    │   ├── date.d95f7a80.svg
    │   ├── direction-arrow.12951b21.svg
    │   ├── dismissIcon.2ef7a37b.svg
    │   ├── gear.8db68ba2.svg
    │   ├── image-popup.ac743778.svg
    │   ├── index.15a1ec57.js
    │   ├── index.ccbdb765.css
    │   ├── index.esm.917ffff3.js
    │   ├── mapbox-gl.a7de3095.js
    │   ├── peopleDotsIcon.bf7f4f7f.svg
    │   ├── pinSidebarIconFilled.7a44c08d.svg
    │   ├── pinSidebarIconOutline.e420f820.svg
    │   ├── shareAddIcon.fd340651.svg
    │   ├── shareCopyIcon.dd0e1bd8.svg
    │   ├── shareDeleteIcon.4967c544.svg
    │   ├── shareLinkIcon.3461b970.svg
    │   ├── shareMoreIcon.8a0d12b3.svg
    │   ├── sorting.2fac2c45.svg
    │   ├── textboxActionArrow.6613d43f.svg
    │   ├── textboxLoadingSpinner.08be3a8a.svg
    │   ├── translation.005155a1.js
    │   ├── translation.0b216bdf.js
    │   ├── translation.2ecd4e40.js
    │   ├── translation.5871b870.js
    │   ├── translation.76f04d78.js
    │   ├── translation.8155e5be.js
    │   ├── translation.8c1dd4d0.js
    │   ├── translation.8fb087a5.js
    │   ├── translation.aca1371c.js
    │   ├── translation.ae1e7b7d.js
    │   ├── translation.b02254d6.js
    │   ├── translation.cf40a5b0.js
    │   ├── translation.d3b4b99d.js
    │   ├── translation.ffe0d070.js
    │   ├── useOrderingParams.471b6dbd.js
    │   ├── useURLParameters.12331373.js
    │   └── videoThumbnailIcon.b08f22dc.svg
    ├── favicon.ico
    ├── index.html
    ├── logo192.png
    ├── logo512.png
    ├── manifest.json
    └── photoview-logo.svg

4 directories, 67 files

</code>
</details>

**Comment by gabrielgio** [comment]
After some time digging I noticed that the websocket handshake is not being completed (even on dev mode) hance the not being able to login?

![image](https://user-images.githubusercontent.com/4411113/222987513-b2e0141f-a5cd-4c9d-aac9-c2bd3fa8a9de.png)
