### ISSUE TITLE
Per album index.md files with description

### ISSUE THREAD

**Issue by v-marinkov** [photoview/photoview#816]
I just tried Photoview and compared to Nextcloud + Memories, it's processing my library with lightspeed! There is one feature which I miss dearly from Google Photos - the ability to write blog-style text.

Pigallery2 has a brilliant and simple solution which abides to the files-first philosophy of PhotoView: read `index.md` files from the specific folder and display them in an accordion at the start of the album (see [here](https://pigallery2.onrender.com/gallery)). The .md files should be ignored in the Timeline and other views - just display them at the album level.

This is very useful for documenting and sharing family experiences, and shouldn't be too much of a hassle to visualise in the browser.

**Comment by kkovaletp** [comment]
Closing it as a duplicate, but copied the proposal to the original issue
