### ISSUE TITLE
Host is not allowed to connect to this MariaDB server

### ISSUE THREAD

**Issue by adamk33n3r** [photoview/photoview#830]
**Describe the bug**
[error] failed to initialize database, got error Error 1130: Host '172.26.0.3' is not allowed to connect to this MariaDB server
2023/04/15 04:19:35 WARN: Could not ping database: Error 1130: Host '172.26.0.3' is not allowed to connect to this MariaDB server. Will retry after 5 seconds
2023/04/15 04:19:40 Connecting to MYSQL database: photoview:photosecret@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2023/04/15 04:19:40 WARN: Could not ping database: Error 1130: Host '172.26.0.3' is not allowed to connect to this MariaDB server. Will retry after 5 seconds
2023/04/15 04:19:40 /app/database/database.go:101

**To Reproduce**
1. Copy docker compose example
2. paste into portainer to create new stack

**Expected behavior**
Running app

**Your environment:**
I'm running portainer on a synology nas

 - Are you using Docker? yes 
 - Database mariadb 10.5
 - Browser chrome
 - Version 2, edge

**Additional context**
The only thing I changed in the docker compose file is the mount path for photos

**Comment by Chacsam** [comment]
Same issue here

**Comment by Chacsam** [comment]
Update, I just tried again without portainer (plain command line `docker compose up -d`) and it worked.

**Comment by adamk33n3r** [comment]
Can you explain why it was closed as not planned? I'd like to get it working..... What's the issue here?

**Comment by Chacsam** [comment]
I guess it was closed because my comment suggested a Portainer issue.
Did you try the plain approach? (direct docker compose)

**Comment by adamk33n3r** [comment]
> I guess it was closed because my comment suggested a Portainer issue. Did you try the plain approach? (direct docker compose)

Not I didn't, because I use portainer lol. Sure it's an issue with using portainer, but I don't think it's an issue with portainer itself. Every other container I use with portainer works fine, I'm guessing it's just because the dockerfile is not configured correctly to work with portainer. But I don't know how to make it work correctly. I ended up just changing it to use the root user and that works which isn't great, but it works. I'm guessing it's some kind of network thing that's different but I'm not familiar with docker enough to know what to do.
