### ISSUE TITLE
SQLite db simultaneous access

### ISSUE THREAD

**Issue by alexyr** [photoview/photoview#846]
When scan is in progress, cannot login to web interface:

Server error: database is locked at (authorizeUser)

My compose yml:
<pre>
version: "3"

services:
  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8000:80"

    cpus: 1.0

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=sqlite
      - PHOTOVIEW_SQLITE_PATH=/app/database/photoview.db
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache

    volumes:
      - api_cache:/app/cache
      - /home/user/docker/photoview:/app/database
      - /media/storage/Photos:/photos:ro

volumes:
  db_data:
  api_cache:
</pre>

**Comment by alexyr** [comment]
Possible solution: separating login and media data to different sqlite files?

**Comment by oscarcarlsson** [comment]
Try enabling the WAL (write-ahead log), which should enable you to use the DB while scanning.

    sqlite3 /app/database/photoview.db 'PRAGMA journal_mode=WAL;'

You need sqlite3 installed somewhere, either in another container or on the host OS.

**Comment by kkovaletp** [comment]
@jordy2254, I think that this might be a really simple and fast fix.
Is it possible to add the "PRAGMA journal_mode=WAL;" SQL execution to the code in the place, where the SQLite DB is created or connected?
I think that it makes sense to run this query in both cases (assuming that the DB creation code also connects to freshly created DB, so the connect to existing DB code is not executed this time), as there is no negative impact to run it more than once on the same DB, but automatically covers the case of already existing DBs when a user pulls a newer image with this fix

here is the doc [sqlite.org](https://www.sqlite.org/wal.html)

It might be even faster to you to make a PR, than answering me here)

**Comment by jordy2254** [comment]
@oscarcarlsson Thanks for the infomation that's very informative and saved me a little research as sqllite isn't my main dialect unless i'm doing development.

Change seems sensible to me an nice and quick to make, added the good first issue tag as it's a simple one liner in the database initialization code (potentially worth making it controlled by an environment variable incase there is issues).
