### ISSUE TITLE
Trigger re-scan with webhook

### ISSUE THREAD

**Issue by oscarcarlsson** [photoview/photoview#848]
**Describe the solution you'd like**

I'd like to have a way to trigger a re-scan of my library (if possible, per user!) after running a Lightroom export.

**Describe alternatives you've considered**

I'm currently using the periodic scanner and if I'm in a hurry, I can just login as admin and run the scan.

**Additional context**

I'd just like to have a webhook/similar to trigger a re-scan at the end of a Lightroom export (triggered with curl/similar). I have a few different export setups (low-res, backup exports...) and like the idea of triggering the re-scan only when needed, like after an export.

I guess it's more complex to implement than I think, tho. :-)

**Comment by tymmej** [comment]
I'm using this script:
```
#!/bin/sh

token=$(curl 'http://172.10.0.190/api/graphql' \
        -X POST \
        -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0' \
        -H 'Accept: */*' \
        -H 'Content-Type: application/json' \
        -H 'Origin: https://photos.domain.pl' \
        -H 'Referer: https://photos.domain.pl/settings' \
        -H 'Connection: keep-alive' \
        -H 'Cookie: csrftoken=some-tokendmIeL' \
        --data-raw '{"operationName":"Authorize","variables":{},"query":"mutation Authorize {\n  authorizeUser(username:\"USER\", password:\"PASSWORD\") {\nsuccess\nstatus\ntoken\n__typename\n  }\n}\n"}')

token=$(echo $token | awk -F\" '{print $14}')

curl 'http://172.10.0.190/api/graphql' \
    -X POST \
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0' \
    -H 'Accept: */*' \
    -H 'Content-Type: application/json' \
    -H 'Origin: https://photos.domain.pl' \
    -H 'Referer: https://photos.domain.pl/settings' \
    -H 'Connection: keep-alive' \
    -H "Cookie: csrftoken=some-tokendmIeL; auth-token=$token" \
    --data-raw '{"operationName":"scanAllMutation","variables":{},"query":"mutation scanAllMutation {\n  scanAll {\nsuccess\n    message\n    __typename\n  }\n}\n"}'
```

Change USER, PASSWORD, `Origin` and `Referer` headers.

**Comment by oscarcarlsson** [comment]
Thank you! Until a webhook is (ever) implemented I think that is good enough for me. :)
