### ISSUE TITLE
"File is not a supported media" when uploading .CR3 files

### ISSUE THREAD

**Issue by fowlerc74** [photoview/photoview#859]
**Description**
During a scan, .CR3 (Canon Raw) files are not processed. The docker-compose logs say "File is not a supported media." Other file types like JPG are processed correctly. The logs also say that darktable is found (Darktable-cli 3.8.1). 

**To Reproduce**
1. Have .CR3 files in a directory accessible by photoview
2. Run a scan

**Expected behavior**
.CR3 files are supported in darktable, so they should be processed and show up in photoview with a thumbnail. 

**Screenshots**
<img width="753" alt="Screenshot 2023-06-24 at 9 36 00 PM" src="https://github.com/photoview/photoview/assets/70218012/fb2f866d-c5a5-44d7-91ce-9ad8a07d18d6">

<img width="794" alt="Screenshot 2023-06-24 at 9 31 22 PM" src="https://github.com/photoview/photoview/assets/70218012/00ecf070-e257-444e-a97b-cd7f614ecf84">

**What I'm Using** 
 - Docker
 - MariaDB 10.5.20
 - Version 2.0.0

**Comment by kkovaletp** [comment]
@fowlerc74, CR3 files processed correctly after upgrading the Darktable version in the #863.
