### ISSUE TITLE
Support Uploading/Moving/Deleting

### ISSUE THREAD

**Issue by CEbbinghaus** [photoview/photoview#864]
**Is your feature request related to a problem? Please describe.**
I don't want to use more than one application when dealing with photos. Not having the ability to upload via the UI means I have to either deploy photoview alongside something like FileBrowser or require that other people are on the same LAN with the ability to upload to the NAS share (which is not going to be possible)

**Describe the solution you'd like**
An easy method to Manage my photos from the Photoview UI.

**Describe alternatives you've considered**
use a different offering. Nothing else feels quite as sleek as photoview which is why I would like to see this functionality

**Additional context**
I have already read the section [here](https://photoview.github.io/en/docs/#aim-and-values) outlining the aims and values. 
> meaning that you don't have to trust Photoview to keep your media safe

doesn't mean I can't trust it and as long as the file system remains the "database" of images I am happy with this. Just because I can (and this should be kept possible) set the filesystem to ReadOnly doesn't mean I shouldn't be able to change my files through photoview

**Comment by viktorstrate** [comment]
There's already a thread open for this issue here #216 :)
