### ISSUE TITLE
Provide a docker container for development, or at least update doc

### ISSUE THREAD

**Issue by kindlydodo** [photoview/photoview#876]
**Is your feature request related to a problem? Please describe.**
I try to dig into this project. The very first thing I need is an environment. What I have found is:

https://photoview.github.io/en/docs/installation-manual/

To keep my system clean, I would appreciate to use a docker container for development.

**Describe the solution you'd like**
Provide a dockerfile, or image with an setup development environment for photoview, or at least update the documentation

I’m trying to set up this but I am failing.

Thank you

**Comment by kkovaletp** [comment]
@kindlydodo I've updated my PR #863 with Docker dev env setup. Please try. Is it what you need?
You could start by reading the comment at the beginning of Dockerfile-dev

**Comment by kindlydodo** [comment]
Looks awesome, thank you!
What I try to achieve is to have a container where the ui/ and api/ folder and the uncompiled source files are. This way I can change code and try it out live in my browaer

**Comment by kkovaletp** [comment]
@kindlydodo Mapping the source code inside the container is easy by adding a new volume to the Photoview service in the docker-compose. However, now it is pretty useless, as you anyway need to recompile the code and reload it on the web server. Right now the code compilation and web server building are done in the same way, as for the production image (at the time of building the image). 

To let you see the result of modifying the code on the fly, the development container should run the development web server. For the frontend code, the [nodeamon](https://nodemon.io/) or [webpack](https://webpack.js.org/) can be used. For the Golang [Realize](https://github.com/oxequa/realize) or [Air](https://github.com/cosmtrek/air) could be used.

I'm not a developer, so I don't know how exactly to configure these servers to work with this project. The additional challenge might be to make them work together, as now everything is served by the same server, while in this development setup, there should be separate processes (ideally different containers) for the frontend and backend.

So, if you can configure that and make it work, provide me the detailed guide to replicate that in the PR or step in and commit there your working config/

**Comment by cicadabear** [comment]
**If you only want to modify the front end, maybe using a reverse proxy server can be a choice.**  

    npm start -- --port 8003

```
nginx-1.24.0\conf\nginx.conf

http {
    include       mime.types;
    default_type  application/octet-stream;
	include "D:/code/nginx-1.24.0/sites-enabled/*.conf";  # add this line

nginx-1.24.0\sites-enabled\localhost_8002.conf 

server {
        listen       8002;
        server_name  localhost;
        location /api {
			proxy_pass http://localhost:8000/api;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}
	location / {
			proxy_pass http://localhost:8003/;
	}	
}
```

**Comment by kkovaletp** [comment]
@googollee, I guess that this issue might be relevant to our recent conversation inside the #981: 

I just thought that simply converting some actions into scripts wouldn't help much to simplify the development workflow. Instead, providing a separate compose file with the frontend and the backend dev services, running a dev-server inside and with source code being mapped as an additional volume (of course, with the DB services as well) would be a better solution. Having that solution ready we might think on how to simplify local tests and checks execution based on that solution.

What do you think?

**Comment by googollee** [comment]
@kkovaletp we should think about dev env. I'm working progress on https://github.com/googollee/photoview/blob/scripts/docker-compose.yaml, which could enter an API env by `docker compose run -it api /bin/bash`, or launch an API server by `docker compose up api`. UI env is similar.

For testing, launching a DB and running `go test` in the env with a proper `.env`.

**Comment by kkovaletp** [comment]
@googollee, on my previous closed-source projects we had docker compose dev environments, like:
- an image with the frontend, running by `nodeamon` with the additional volume of the project's source code from the host (dev system) to the service, so that the `nodeamon` could watch and rebuild on changes in the source code
- a similar backend image with `nodeamon` (when the backend was in NodeJS) or an alternative dev server, watching for changes in the source code
- all other services, like in the PROD environment to make sure we're as close as possible to PROD.

Having this setup, devs were able to develop on their physical systems and see the result immediately (in a few sec to let rebuild the code and serve it). Also, with the Docker plugin for the IDE, they were able to run tests and debug running code from the IDE inside the running dev. container.

Hope, this use case description would help to design a better possible solution for our project)

**Comment by googollee** [comment]
I didn't use `nodeamon` before. I can try it with the backend, but I don't know how the frontend development works now.

**Comment by kkovaletp** [comment]
@googollee, as far as I see, there is no active development from the frontend side (unfortunately)

Regarding `nodeamon`, it should support Go, but I think that it is better to try a native to Go server. AI recommends https://github.com/air-verse/air - I don't know whether this is the best option or not, just mention it)

**Comment by kkovaletp** [comment]
@googollee, it looks like this issue is already handled by 1 of your previously merged PRs, right?
Please check that all the aspects are handled and if that is the case, feel free to close this issue as completed and close the linked PR #650 as rejected.
Or let me know and I'll do that)

**Comment by googollee** [comment]
It's done by #1003
