### ISSUE TITLE
Something went wrong Server error: Error 1390: Prepared statement contains too many placeholders at (myFaceGroups)

### ISSUE THREAD

**Issue by muyd** [photoview/photoview#877]
**Describe the bug**

url http://ip:port/albums

Something went wrong
Server error: Error 1390: Prepared statement contains too many placeholders at (myFaceGroups)

url http://ip:port/people

Something went wrong
Server error: Error 1390: Prepared statement contains too many placeholders at (myAlbums)

select count(*) from albums;  --116534
SELECT count(*) FROM `user_albums`; --116534

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [yes]
 - Database [5.5.5-10.3.7-MariaDB]
 - Browser [chrome]
 - Version [2.3.9 (72cb02d9)]

**Additional context**

**Comment by kkovaletp** [comment]
@muyd, Can you please describe your setup in detail? You have 116 534 albums. What is inside: only pictures, only videos, a mix of both? How flat is the album's hierarchy: how deep is the deepest folder? How many faces do you have? Did you merge them or didn't touch at all?
Do you still see this issue or managed to fix it? How?
Is there something else to help us understand and reproduce it?
