### ISSUE TITLE
when installing photoview i get error 

### ISSUE THREAD

**Issue by perhorst** [photoview/photoview#882]
**Describe the bug**

**To Reproduce**
1. Go to 'the installer site https://photoview.github.io/en/docs/installation-manual/'
2. install on 'install everything until i cant, and thats on "go build -v -o photoview .'
3. and the response is 'go: cannot find main module, but found .git/config in /opt/photoview
        to create a module there, run:
        cd ../.. && go mod init'

**Expected behavior**

![image](https://github.com/photoview/photoview/assets/92875489/fe0ddf9a-c7c4-4063-8401-8452702b79ad)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [ no] ( using unbuntu
 - terminal ssh 
 - Version latest

**Additional context**

**Comment by kkovaletp** [comment]
most probably the documentation is outdated and not relevant... did you try to repeat the same steps, as in the Dockerfile?

**Comment by kkovaletp** [comment]
@jordy2254, can you please look into this issue? Was it an actual issue or user misunderstanding, is it still relevant or can be closed?

**Comment by jordy2254** [comment]
Based on the logs I believe this was because they didn't cd into the api directory and where trying to build the api from the root folder. The documentation looks correct on this correctly stating to cd into the api directory so I don't think anything needs to be updated here and we can close it.
