### ISSUE TITLE
Add cross compile support for arm64-amd64

### ISSUE THREAD

**Issue by cicadabear** [photoview/photoview#887]
## I'm using a free Oracle Cloud Arm64 instance as the building platform, with this error ```E: Unable to locate package libdlib-dev:amd64 ```,  solved like this. 

<img width="966" alt="Weixin Image_20230903102832" src="https://github.com/photoview/photoview/assets/9974073/197d2224-a15b-48ac-93fb-8d1d2689ada6">

**Comment by kkovaletp** [comment]
Why not a PR? You already did the code change)

**Comment by cicadabear** [comment]
@kkovaletp ok
