### ISSUE TITLE
Stand alone program

### ISSUE THREAD

**Issue by thewh1teagle** [photoview/photoview#890]
It will be much more useful if users can use `photoview` as standalone program, so they just install it and use it without require to run it on server / on `docker`

What do you think about that?
any way, I investigated it a bit on windows, it looks like it's not designed with cross platform orientation so there's some issues with `paths` and things like that but in general it worked.
I produced single binary on windows which uses `sqlite` as the database driver

**Comment by kkovaletp** [comment]
As you can see in the Readme's list of supported platforms, we don't support hosting Photoview on Windows natively. It is designed to run on a Linux environment. You still can run it on Windows but with Docker or Cygwin \ WSL (the last 2 are not supported as well, but there are high chances to make it work there).

I don't think that we're going to support the standalone client app scenario, as you've described it. You can still set up the Photoview server on your local OS and access it through PWA or browser on `localhost` address. I think that this would be the closest possible alternative to your request.
