### ISSUE TITLE
Fix pipelines

### ISSUE THREAD

**Issue by eerison** [photoview/photoview#896]
I'm trying to see the errors in the pipeline,  but the icon is not clicable,  maybe one of maintainers could post here what is the pipeline output

**Comment by eerison** [comment]
Ok sorry,  it wasn't possible just in mobile version,  in the desktop yes I can see ;)

**Comment by jordy2254** [comment]
Closing this as it looks like everything was sorted. If you have further issues please feel free to open a new issue.

**Comment by jordy2254** [comment]
Closing this as it looks like everything was sorted. If you have further issues please feel free to open a new issue.
