### ISSUE TITLE
Folder view request

### ISSUE THREAD

**Issue by ambarusa** [photoview/photoview#898]
**Is your feature request related to a problem? Please describe.**
I originally started to manage my photos and videos manually,  so albums mean the folders on the drive to me.

**Describe the solution you'd like**
It would be great to have a folder view next to the album view, for faster navigation. In Photoprism it also helped me to check whether all the files were discovered. It would be catchy for those users, who want to try out the app, without creating albums in a new application again.

**Describe alternatives you've considered**
Couldn't find alternative without making a huge effort of making albums.

**Additional context**
This is my opinion after clicking around on the demo page. It is such a nice and simple application, can't wait to give it a try.

**Comment by kkovaletp** [comment]
@ambarusa, Maybe I didn't get your point, but PhotoView is actually designed to respect the user's folder structure and automatically create albums based on that.
Could you please provide an example of your folder structure with images and how it looks in PhotoView after the scan? What do you need to change exactly in that PhotoView structure?

**Comment by ambarusa** [comment]
Ooh, I see, physical folders become an album... That sounds great. Let me make a test soon, and come back to you.
