### ISSUE TITLE
Allow setting GPS coordinates to pictures

### ISSUE THREAD

**Issue by Bouni** [photoview/photoview#902]
**Is your feature request related to a problem? Please describe.**
I have literally thousends of pictures from a time when automatically geotag them was not a thing.
So I would really like to tag them now in order for them to show up on the map in the rigt spots.

**Describe the solution you'd like**
I think selecting on or more pictures and assign a location to them via a map in the sidebar or sime kind of map modal would be ideal.

**Describe alternatives you've considered**
I looked into a lot of tool ourt there but no one really solves this problem.

**Comment by kkovaletp** [comment]
While I see a benefit from such feature, it requires changing the architecture and the idea behind the product: now it is designed to be a read-only frontend on top of the user's media library.

I guess, there should be some media editing solutions on the market, which provide the ability to populate existing media files with additional metainformation, including geotags and other useful info.

**Comment by viktorstrate** [comment]
I will close this as it's currently outside the scope of the project, see also #919
