### ISSUE TITLE
The second user has a different root with the same settings

### ISSUE THREAD

**Issue by attikov** [photoview/photoview#913]
The second user has a different root with the same settings.
Very annoying.

**Comment by kkovaletp** [comment]
@attikov, please give some more details on what exactly is configured on the Settings page for users and what is the final goal, you'd like to achieve.
For me it works fine with an empty username and path for every new user, I create.

**Comment by attikov** [comment]
following the instructions "The default location is /photos"
both for admin and for a new user was set up the "/photos" dir, the admin had a timeline, the user had an albun "photos".
can't help further, already deleted the container

**Comment by kkovaletp** [comment]
If you'd like both to see the same media, you need to set the same root path (as you did with setting the `/photos`). Then you need to scan the media library for all users by pressing the button `Scan all users` in the Scanner section or the `Scan` button in the new user's row in the table.

Once the scan is complete, the new user should see the same media structure, as the previous one.

**Comment by attikov** [comment]
this is ridiculous, the scan was running for several hours

**Comment by kkovaletp** [comment]
it is only for the 1st time. subsequent scans process only new changes

**Comment by attikov** [comment]
i see. in this case I did not find the corresponding entry in the documentation

**Comment by kkovaletp** [comment]
yeap. documentation is incomplete and sometimes a bit outdated

**Comment by viktorstrate** [comment]
It seems like this issue can be closed, if I misunderstand please reply why and I'll reopen it.
