### ISSUE TITLE
Lots of vulnerabilities in UI

### ISSUE THREAD

**Issue by tazio** [photoview/photoview#932]
**Describe the bug**
After running:
`photoview/ui $ npm install`

at the end of the process there is this report:
```
256 packages are looking for funding
  run `npm fund` for details

41 vulnerabilities (15 moderate, 22 high, 4 critical)
```

I am using a more modern version of node.js that the one supported, but still this does not look good.
[I am following this link for installation.](https://photoview.github.io/en/docs/installation-manual/)

**Comment by kkovaletp** [comment]
Yes, we have a lot of vulnerabilities because of outdated dependencies in the project. You can see a more detailed report at https://github.com/photoview/photoview/blob/ece1de2370f1c03e4ad870b96ea957d1e8fc02b5/vulnerabilities/code/grype-CVEs.html (part of the #910)

**Comment by jordy2254** [comment]
Hi @tazio thanks for the report. In this situation this is a duplicate of #920 I will close this issue for that reason. I plan to tackle that issue after I finish up the permissions system stuff unless someone in the comminity takes a look
