### ISSUE TITLE
Darktable is out of date on edge docker image

### ISSUE THREAD

**Issue by vbabiy** [photoview/photoview#935]
Can we get an updated release with an updated darktable, the latest version is 4.6.1

https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable

The version that photo view ships with doesn't support the new sony cameras.

**Comment by kkovaletp** [comment]
Actually, after some deeper investigation, I was able to install the latest Darktable version into the Photoview image and I'll update my PR #863 with the fix, so once it gets merged, this issue should be solved

**Comment by vbabiy** [comment]
Until #863 is merged the docker image is not useable for newer cameras, I get only white boxes and no images like those described in #757

**Comment by kkovaletp** [comment]
> Until #863 is merged the docker image is not useable for newer cameras, I get only white boxes and no images like those described in #757

Unfortunately, this is how open-source projects work: we're not getting money from it and contributing for fun in our free time, so we need to wait for the code review process to complete (in particular, when all other project maintainers including the repo owner will review it with at least owner's approval), and it will happen when there is a free time slot for them.

Until that if you don't want to wait, you could fork the PR and build the image from it locally in the same way, it is configured in #910.

**Comment by vbabiy** [comment]
has the docker edge image been updated?

**Comment by kkovaletp** [comment]
> has the docker edge image been updated?

I'm not sure, but the `master` was.
Make sure to read the `Getting Started` section of Readme to set it up correctly, as the old config is not compatible with it
