### ISSUE TITLE
Can't access phototview web ui with k8s configuration.

### ISSUE THREAD

**Issue by googollee** [photoview/photoview#950]
**Describe the bug**
Can't access phototview web UI with k8s configuration.

The configuration:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photos
  labels:
    app: photos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photos
  template:
    metadata:
      labels:
        app: photos
    spec:
      containers:
      - name: photos
        image: viktorstrate/photoview:2
        imagePullPolicy: IfNotPresent
        env:
        - name: PHOTOVIEW_DATABASE_DRIVER
          value: sqlite
        - name: PHOTOVIEW_SQLITE_PATH
          value: /home/photoview/db.sqlite
        - name: PHOTOVIEW_LISTEN_IP
          value: 127.0.0.1
        - name: PHOTOVIEW_LISTEN_PORT
          value: "80"
        - name: PHOTOVIEW_SERVE_UI
          value: "1"
        - name: PHOTOVIEW_UI_PATH
          value: /home/photoview/ui
        - name: PHOTOVIEW_MEDIA_CACHE
          value: /home/phototview/cache
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /usr/share/zoneinfo
          name: zoneinfo
          readOnly: true
        - mountPath: <hidden media path>
          name: photos
          readOnly: true
        - mountPath: /home/photoview
          name: data
      volumes:
      - name: data
        hostPath:
          path: /mnt/data/config/photoview
      - name: photos
        hostPath:
          path: /mnt/data/media/photos/Googol图库
      - name: zoneinfo
        hostPath:
          path: /usr/share/zoneinfo
      - name: localtime
        hostPath:
          path: /etc/localtime
```

The pod launches succeeded. When I try to access web UI, photoview server returns `404` with`unauthenticated` log:

```
% kubectl logs svc/photos
2024/05/20 12:09:41 Starting Photoview...
2024/05/20 12:09:41 No .env file found
2024/05/20 12:09:41 Opening SQLITE database: /home/photoview/db.sqlite?cache=shared&mode=rwc
2024/05/20 12:09:43 Migrating `media_exif.flash` from string to int

2024/05/20 12:09:43 /app/database/migration_exif.go:122 no such table: information_schema.columns
[0.054ms] [rows:0] SELECT data_type FROM information_schema.columns WHERE table_name = 'media_exif' AND column_name = 'flash';
2024/05/20 12:09:43 Failed to run exif fields migration: migrating `media_exif.flash` failed: read data_type of column media_exif.flash: no such table: information_schema.columns
2024/05/20 12:09:43 Initializing scanner queue with 1 workers
2024/05/20 12:09:43 Queue waiting
2024/05/20 12:09:43 Periodic scan interval changed: disabled
2024/05/20 12:09:43 Scan interval runner: Waiting for signal
2024/05/20 12:09:43 Scan interval runner: New ticker detected
2024/05/20 12:09:43 Scan interval runner: Waiting for signal
2024/05/20 12:09:43 Found executable worker: darktable (this is darktable-cli 3.8.1)
2024/05/20 12:09:44 Found executable worker: ffmpeg (ffmpeg version 5.0.1-3+b1 Copyright (c) 2000-2022 the FFmpeg developers)
2024/05/20 12:09:44 Found exiftool
2024/05/20 12:09:44 Initializing face detector
2024/05/20 12:09:45 Photoview API endpoint listening at http://127.0.0.1:80/api
2024/05/20 12:09:45 Photoview API public endpoint ready at /api
2024/05/20 12:09:45 Photoview UI public endpoint ready at /
2024/05/20 12:10:06 Did not find auth-token cookie
2024/05/20 12:10:06 GET 404 hidden.domain/ 5.537762ms unauthenticated
2024/05/20 12:10:06 Did not find auth-token cookie
2024/05/20 12:10:06 GET 404 hidden.domain/favicon.ico 332.179µs unauthenticated
2024/05/20 12:10:08 Did not find auth-token cookie
2024/05/20 12:10:08 GET 404 hidden.domain/ 824.516µs unauthenticated
2024/05/20 12:17:36 Did not find auth-token cookie
2024/05/20 12:17:36 GET 404 hidden.domain/ 2.9433ms unauthenticated
```

**To Reproduce**
Not a UI issue.

**Expected behavior**
I can access web UI with k8s deployment.

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? Yes and no. It's k3s with `runc`.
 - Database: sqlite
 - Browser: chrome
 - Version: 2.0.0

**Additional context**

**Comment by kkovaletp** [comment]
Hi @googollee, thanks for your report.
We do not officially support k8s, as (as far as I know) nobody has tested the deployment of Photoview onto k8s.
However, I noticed a few things in your config:
- you use SQLite DB and it is a strange choice (as to me) for k8s deployment. Currently, we have limited support of SQLite for really small deployments with rare access from users (as it is connected to the backend in exclusive mode using a single connection). I'd recommend you switch to PostgreSQL, as this is the most performant DB and fits the best to a k8s setup, where a higher-than-usual load is expected.
- you've mixed paths inside the container: you used the release image while setting paths from the `master` branch. I'd suggest you switch to the `viktorstrate/photoview:master` to be consistent and get the latest fixes and improvements.
- make sure that the value of the `PHOTOVIEW_UI_PATH` points to the folder inside the container, where the UI files are located. For the `master` image that should be the `/app/ui`

Please try these (at least the last 2) suggestions - hope that they will help. If not, please share what has changed in the app behavior after these changes were made.

**Comment by googollee** [comment]
Hi @kkovaletp,

Thank you for the quick response.

It's working with `viktorstrate/photoview:master` and `PHOTOVIEW_UI_PATH=/app/ui`. I didn't know that `viktorstrate/photoview:2` is a 2-year-old image. I followed with [docker compose example](https://github.com/photoview/photoview/blob/master/docker-compose%20example/docker-compose.example.yml#L3) and it should be updated. I'll see if I can do that later.

Now from the log, it keeps complaining that the database is read-only. I hope to keep it simple as a single instance.

**Comment by kkovaletp** [comment]
> I followed with [docker compose example](https://github.com/photoview/photoview/blob/master/docker-compose%20example/docker-compose.example.yml#L3) and it should be updated

Actually, this is a tricky moment, as this is the default branch, the example should refer to the released image, however, until the current `master` image is not released, there is this inconsistency.
I don't think that updating the example to refer to the unstable version of the image is a good idea, but I confirm that there is inconsistency, which leads to user misunderstanding and product misconfiguration.

**Comment by googollee** [comment]
Thanks for the confirmation. I already launched `photoview` with k8s and it works well. Thank you again for your hard work.
