### ISSUE TITLE
Create CONTRIBUTING.md document

### ISSUE THREAD

**Issue by blakeschafer** [photoview/photoview#952]
### **Feature Request: Contributing Document**

I'm always frustrated when new contributors struggle to understand how to make changes in the code due to the lack of a comprehensive guide. This often leads to confusion and hinders the efficiency of contributions to the project.

I propose creating a contributing document for this repository. This document would serve as a resource file for any developer who wants to contribute to this open-source project. It should provide more details than what is currently available, offering a detailed walkthrough for newcomers on how to make changes in the code. The goal is to make it as clear and concise as possible, ensuring that even those new to the project can easily understand and follow the steps.

As alternatives, I have considered referring contributors to external resources and guides, hosting periodic onboarding sessions for new contributors, and adding brief comments and guidelines directly within the code. However, these alternatives do not provide the same level of detailed, centralized guidance that a dedicated contributing document would offer.

Creating this document will enhance the onboarding experience for new contributors, making it easier for them to get started and contribute effectively. This could include step-by-step instructions, screenshots, and examples of common tasks, ultimately improving the overall contribution process and project development.

**Comment by kkovaletp** [comment]
@blakeschafer , thanks for creating the issue. I've linked it with your PR for traceability
