### ISSUE TITLE
Docker image `master` doesn't link to the latest commit hash `ddacba8`, but `6693920`.

### ISSUE THREAD

**Issue by googollee** [photoview/photoview#956]
**Describe the bug**
Currently, the docker image with `master` tag links to the commit hash `6693920`, but not the latest commit `ddacba8`:

<img width="536" alt="Screenshot 2024-05-31 at 21 58 43" src="https://github.com/photoview/photoview/assets/496526/218e20ca-f5c2-4676-844b-d7bb40371c30">

In the screenshot above, digests of `sha-6693920` images are the same as digests of `master` images.

In the repo, the hash `ddacba8` is the latest commit:

<img width="1327" alt="Screenshot 2024-05-31 at 22 00 24" src="https://github.com/photoview/photoview/assets/496526/6436da03-5b5f-411f-8897-f6c987984cb7">

I think it's a race condition in CI action that the commit `6693920` finished later than the commit `ddacba8`.

**To Reproduce**
1. `docker pull viktorstrate/photoview:master`
2. `docker pull viktorstrate/photoview:sha-6693920`
3. `docker pull viktorstrate/photoview:sha-ddacba8`
4. `docker images ls`

```
✓22:08:40 [googol@Googol-MBA:~] 
% docker pull viktorstrate/photoview:master
master: Pulling from viktorstrate/photoview
09f376ebb190: Already exists 
35472eeb5ed8: Pull complete 
4f4fb700ef54: Pull complete 
1555b4773bab: Pull complete 
8c54d24c03ac: Pull complete 
38a87d7dd930: Pull complete 
Digest: sha256:ff25b3de6612a8066d396456aa3da9658779270322e1b9634e9156ff57fe1617
Status: Downloaded newer image for viktorstrate/photoview:master
docker.io/viktorstrate/photoview:master
✓22:13:30 [googol@Googol-MBA:~] 
% docker pull viktorstrate/photoview:sha-ddacba8       
sha-ddacba8: Pulling from viktorstrate/photoview
09f376ebb190: Already exists 
d5b0c0001497: Pull complete 
4f4fb700ef54: Pull complete 
7b221c417ffc: Pull complete 
394ec8c8024b: Pull complete 
dffa66d8bd93: Pull complete 
Digest: sha256:773f59f817e912e6ab3e36cc53cf16656b1568cf032fcd61430206bf98f25b2d
Status: Downloaded newer image for viktorstrate/photoview:sha-ddacba8
docker.io/viktorstrate/photoview:sha-ddacba8
✓22:17:56 [googol@Googol-MBA:~] 
% docker pull viktorstrate/photoview:sha-6693920
sha-6693920: Pulling from viktorstrate/photoview
Digest: sha256:ff25b3de6612a8066d396456aa3da9658779270322e1b9634e9156ff57fe1617
Status: Downloaded newer image for viktorstrate/photoview:sha-6693920
docker.io/viktorstrate/photoview:sha-6693920
✓22:18:09 [googol@Googol-MBA:~] 
% docker images
REPOSITORY               TAG           IMAGE ID       CREATED         SIZE
viktorstrate/photoview   sha-ddacba8   3a939ff9ddb8   12 hours ago    1.3GB
viktorstrate/photoview   master        b1996ea55c83   12 hours ago    1.3GB
viktorstrate/photoview   sha-6693920   b1996ea55c83   12 hours ago    1.3GB
```

`viktorstrate/photoview:master` has the same digiest with `viktorstrate/photoview:sha-6693920`.

**Expected behavior**
`viktorstrate/photoview:master` has the same digiest with `viktorstrate/photoview:sha-ddacba8`.

**Screenshots**
Not a UI issue.

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? yes
 - Database n/a
 - Browser n/a
 - Version master

**Comment by kkovaletp** [comment]
@googollee , thanks for the report! Good catch)
This happens when merging several PRs at the same time without canceling jobs in `master` for older merges.
I've restarted the build image job and now I see the correct tag being mapped to the `master` image.
