### ISSUE TITLE
Docker - cant connect to database 

### ISSUE THREAD

**Issue by Surrealcrow** [photoview/photoview#96]
Using the provided docker-compose file with any changes:
`
2020/10/11 23:04:17 Connecting to database: photoview:photo-secret@tcp(db)/photoview?multiStatements=true&parseTime=true
2020/10/11 23:04:17 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.21.0.3' (using password: YES), Will retry after 1 second
2020/10/11 23:04:18 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.21.0.3' (using password: YES), Will retry after 1 second
2020/10/11 23:04:19 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.21.0.3' (using password: YES), Will retry after 1 second
2020/10/11 23:04:20 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.21.0.3' (using password: YES), Will retry after 1 second
2020/10/11 23:04:21 Could not connect to database: Could not ping database, exiting: Error 1045: Access denied for user 'photoview'@'172.21.0.3' (using password: YES)
panic: Could not connect to database: Could not ping database, exiting: Error 1045: Access denied for user 'photoview'@'172.21.0.3' (using password: YES)
`
Tried to change passwd to the database however root can't access the database as well

`~/apps/photoview$ docker exec -it photoview_db_1 /bin/bash
root@b7f44e91ca1f:/# mysql -root
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
root@b7f44e91ca1f:/# mysql -root -p
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@b7f44e91ca1f:/# mysql -root -p
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@b7f44e91ca1f:/#`

**Comment by Surrealcrow** [comment]
After using the mariadb compose format in the official page the connection was successful however, no thumbnails are created, in webconsole i can see:

failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by viktorstrate** [comment]
Make sure that the PUBLIC_ENDPOINT variable in the docker compose is set correctly.
It should be set to the same url as the one you type into the address bar of the browser to access the site.
Eg. for the demo site it would be `PUBLIC_ENDPOINT=https://photos.qpqp.dk/`

**Comment by yllekz** [comment]
Adding some commentary to this, I couldn't get this to work if "photo-secret" was the password. When I changed the password both in the DB and MYSQL_URL variable specification to just "photoview," it worked. It doesn't like the hyphen.

**Comment by viktorstrate** [comment]
@yllekz thank you for your comment, the example config should probably be changed then.

**Comment by viktorstrate** [comment]
Solved in 5b8660c
