### ISSUE TITLE
Scanning issues

### ISSUE THREAD

**Issue by kanwarplaha** [photoview/photoview#971]
Often photoview "ignores" photos in certain sub-directories and then there is no way to force it to rescan them. No matter how many times i rescan the parent directory, the photos never appear.

Other than adding each sub-dir separately for scanning (which it does not allow if the parent is already in the list), what other way can I force it?

**Comment by kkovaletp** [comment]
@kanwarplaha, thanks for the report, but we need to know your setup details to understand the problem.
To better understand your case, please share:
- do you use docker or host directly? do you use something on top of docker or just regular docker-compose?
- what is your server's architecture and OS? Is it some proprietary system?
- which version of Photoview do you run: the latest `master`, or the release?
- what are the permissions of the media folder and all its sub-folders? please share the result of [this script](https://sl.bing.net/dNfH0v50DxQ), executed from the media root folder
- please share the `photoview` log, which includes the service start and complete scanning job

**Comment by kanwarplaha** [comment]
Hey @kkovaletp thanks for the quick reply. Here's my environment:
- I used regular docker. I used docker-compose to start the containers. No changes to config except the location of the photos themselves
- I am running it on openSUSE tumbleweed. It is an x86_64 build.
- Photoview Release Version: 2.3.13 ([446ef9a4], Build date: 2022-07-26T18:26:27Z
- It appears the script checks permission of each file. I have more than 100,000 photos. Do you want output of all of them?
- Same for photoview log. It's humongous. However, I can share that when I add individual sub-dirs for scanning, there is higher success rate. However, that is cumbersome and time-consuming. When I provide the top-level directory, some sub-dirs are skipped and then never scanned again.

**Comment by kanwarplaha** [comment]
@kkovaletp I had a question on your last reply. How can I update photoview version when I'm using docker-compose? I just downloaded the yaml file and ran `docker-compose up -d`

**Comment by kkovaletp** [comment]
@kanwarplaha, thanks for your reply with the details.
I guess that at this point there is no need to share your logs and permission-check-script results, as you use a 2-year-old version with a lot of bugs, being fixed in the `master` version.
So, please try the latest `master` version: you need to download the examples of the configuration setup from the `master` branch and follow the step-by-step guide in the Readme. In addition, you'd need to replace the `image: viktorstrate/photoview:2` with the `image: viktorstrate/photoview:master`.
As the new image runs under a non-root user, please make sure to add read and search permissions for `others` to the files and folders in your media location. It is part of the configuration, but I'd mention it here additionally)

Hope that this will fix your issue after the next full scan. But if not, please make sure that skipped files and folders have read and search (for folders) permissions for others group and share the complete photoview log with the scan job - in particular, I'd like to see the start of the service, start of the job, the places, where it skips the files or folders (are there any mentions of them, unexpected messages, errors, warnings, anything else), and the job finish.

The other possible cause is partially corrupted DB. To check that, having the setup with the `master` version, you might backup it and move the content of the DB volume somewhere else, so after start, it will create an empty DB and the next job will populate it with media from scratch. If only this helps and not the previous scenario, depending on the efforts needed, you'll need to deep-dive into your original DB and try to manually find and fix all the inconsistencies (potentially by searching for and removing all mentions of the files and albums from the skipped folders) or performing the same product configuration on the new DB.

**Comment by kanwarplaha** [comment]
Thank you @kkovaletp. However, when I'll do docker-compose down and up again, does it blow away and restart from scratch all scanning?

**Comment by kkovaletp** [comment]
@kanwarplaha, no. The `docker-compose down` command just shuts down all the services from the compose and removes corresponding containers and the virtual network between them. If you run the `docker-compose down -v`, then, in addition, it will remove volumes registration, keeping all the data in the corresponding folders on the host.

The results of previous scans are still stored in the Photoview cache folder and in the DB files: both are mounted as volumes on the host, so next time you spin the compose up with the same volumes mapped, this data is loaded to Photoview.

**Comment by kanwarplaha** [comment]
Hello @kkovaletp ,

Here's what I did:
1. Used `docker-compose down -v`
2. Removed the database and storage sub-directories
3. Changed image to master
```$ cat docker-compose.yml                               
services:
  photoview:
    image: viktorstrate/photoview:master
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: photoview
    container_name: photoview
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - "8000:80" ## HTTP port (host:container)
```
4. Ran `docker volume prune`. I don't have any other container and wanted to be sure.
5. Started the containers with `docker-compose up -d`

After startup, I noticed two things:
1. It did not go to first setup and I could login with existing username/password
2. While scanning it gave `lstat` and `cache` errors

So, are there other locations I have to cleanup before restarting?

**Comment by kanwarplaha** [comment]
@kkovaletp I did some more troubleshooting but did not help.

I checked the user when logged in to photoview container. It has id 999/groupid 999. So, I created a new group on my host with gid 999. Then, I changed the group on the photos/media directory (recursively) to photoview (id: 999):
`drwxrwxrwx 104 kanwar photoview      20480 Jun 20 15:59 Pictures`

Then, I basically flushed everything and recreated the containers. Yet, I get the lstat error with permission denied on one of the sub-dirs.

**Comment by kkovaletp** [comment]
@kanwarplaha, thanks for the new details.
- as after you removed the DB volume and started the compose, but were still able to log in with the original creds, it means that the DB volume wasn't cleared and it still runs your old DB. Please share your compose yaml so that I can tell you where it is located and you can remove it.
- the media cache folder on your host has to have `rwx` permissions for others (or for group 999, however, please don't rely on this GID, as it is not hardcoded in the Dockerfile, so after future rebuilds, it might change)
- as you'd like to clean up your DB and start from a clean environment, you are free to remove the content of the media cache folder as well - anyway it is useless after you remove the DB.
- I don't get which exact errors you mean by mentioning the:
> While scanning it gave lstat and cache errors. Note I had changed allowed rw access to "others" on my photos directory (recursively).
But please read the "Getting Started" guide in the Readme and all the config examples (including the Makefile, even if you don't use it: it contains a sequence of commands for use cases, which are recommended to be used, like the `chmod` command for the media cache folder on the host before the compose starts)

**Comment by kanwarplaha** [comment]
Here's my `docker-compose.yml`:
```
 cat docker-compose.yml
services:
  photoview:
    image: viktorstrate/photoview:master
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: photoview
    container_name: photoview
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - "8000:80" ## HTTP port (host:container)
    ## This ensures that DB is initialized and ready for connections.
    ## Comment out the entire `depends_on` section if PHOTOVIEW_DATABASE_DRIVER is set to `sqlite` in the .env
    ## Or comment out the `mariadb:` and uncomment the `postgres:` if PHOTOVIEW_DATABASE_DRIVER is set to `postgres`
    depends_on:
      # postgres:
      mariadb:
        condition: service_healthy
    ## Security options for some restricted systems
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOVIEW_DATABASE_DRIVER: ${PHOTOVIEW_DATABASE_DRIVER}
      ## Comment out the next variable in the case PHOTOVIEW_DATABASE_DRIVER is set to `sqlite` or `postgres` in the .env
      PHOTOVIEW_MYSQL_URL: "${MARIADB_USER}:${MARIADB_PASSWORD}@tcp(photoview-mariadb)/${MARIADB_DATABASE}"
      ## Uncomment the next line if PHOTOVIEW_DATABASE_DRIVER is set to `sqlite` in the .env
      # PHOTOVIEW_SQLITE_PATH: ${PHOTOVIEW_SQLITE_PATH}
      ## Uncomment the next line if PHOTOVIEW_DATABASE_DRIVER is set to `postgres` in the .env
      # PHOTOVIEW_POSTGRES_URL: postgres://${PGSQL_USER}:${PGSQL_PASSWORD}@photoview-pgsql:5432/${PGSQL_DATABASE}?sslmode=${PGSQL_SSL_MODE}
      PHOTOVIEW_LISTEN_IP: "photoview"
      ## Uncomment the next variable and set a different value to change the port photoview uses inside the container.
      ## If you change this, remember to update the port mapping (under the `ports:`) above!
      # PHOTOVIEW_LISTEN_PORT: 80
      ## Uncomment the next variable and set a different value to set the location of the media cache inside the container.
      ## If you change this, remember to update the right side of the storage volume mount (under the `volumes:`) below!
      # PHOTOVIEW_MEDIA_CACHE: "/home/photoview/media-cache"
      ## Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      ## Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1
      ## Optional: To enable map related features, you need to create a mapbox token.
      ## A token can be generated for free here https://account.mapbox.com/access-tokens/
      ## It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      MAPBOX_TOKEN: ${MAPBOX_TOKEN}
    ## Share hardware devices with FFmpeg (optional):
    # devices:
      ## Uncomment next devices mappings if they are available in your host system
      ## Intel QSV
      # - "/dev/dri:/dev/dri"
      ## Nvidia CUDA
      # - "/dev/nvidia0:/dev/nvidia0"
      # - "/dev/nvidiactl:/dev/nvidiactl"
      # - "/dev/nvidia-modeset:/dev/nvidia-modeset"
      # - "/dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl"
      # - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      # - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
      ## Video4Linux Video Encode Device (h264_v4l2m2m)
      # - "/dev/video11:/dev/video11"
    volumes:
      ## Example:
      ## - "/host/folder:/container/folder"
      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
      ## Uncomment the next line if PHOTOVIEW_DATABASE_DRIVER is set to `sqlite` in the .env
      # - "${HOST_PHOTOVIEW_LOCATION}/database:/home/photoview/database"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
      ## Change This in the .env file: to the directory where your photos are located on your server.
      ## You can mount multiple paths if your photos are spread across multiple directories.
      ## The same path as the container path set here, you'll need to provide on the Photoview's init page (the one between the ':' chars).
      ## If you mount several folders, provide the path to the parent one on the init page.
      ## If you mount several folders, make sure that there are no direct mappings to the media root folder.
      ## This means that you need to also modify the container path of the HOST_PHOTOVIEW_MEDIA_ROOT
      ## to something like '/photos/main'. Note that this new name ('main' in this example) will become an album in Photoview.
      - "${HOST_PHOTOVIEW_MEDIA_ROOT}:/photos:ro"
      ## *Additional* media folders can be mounted like this (set the variable in .env file)
      ## Note that a mount cannot be located in a subfolder of another mount.
      # - "${HOST_PHOTOVIEW_MEDIA_FAMILY}:/photos/Family:ro"

  ## Watchtower upgrades services automatically (optional)
  watchtower:
    image: containrrr/watchtower:latest
    hostname: watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      ## Comment out the next variable if you want Watchtower to auto-update all containers, running on the host,
      ## while now it will update only those with the label "com.centurylinklabs.watchtower.enable=true"
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP}
      WATCHTOWER_POLL_INTERVAL: ${WATCHTOWER_POLL_INTERVAL}
      WATCHTOWER_TIMEOUT: ${WATCHTOWER_TIMEOUT}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.docker/config.json:/config.json:ro" ## optional, for authentication if you have a Docker Hub account
      - "/etc/localtime:/etc/localtime:ro"      ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"        ## use timezone from host

  ## Comment out the `mariadb` service if PHOTOVIEW_DATABASE_DRIVER is set to `sqlite` or `postgres` in the .env
  mariadb:
    image: mariadb:lts
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: photoview-mariadb
    container_name: photoview-mariadb
    restart: unless-stopped
    stop_grace_period: 5s
    ## Optimized MariaDB startup command for better performance and compatibility
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    security_opt: ## see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    ## Uncomment next 2 lines if you want to access the database directly
    # ports:
      # - "3306:3306"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      ## Example:
      ## - "/host/folder:/container/folder"
      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
      - "${HOST_PHOTOVIEW_LOCATION}/database/mariadb:/var/lib/mysql" ## DO NOT REMOVE
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 3m

  ## Uncomment the `postgres` service if PHOTOVIEW_DATABASE_DRIVER is set to `postgres` in the .env
#  postgres:
#    image: postgres:16-alpine
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
#    hostname: photoview-pgsql
#    container_name: photoview-pgsql
#    restart: unless-stopped
#    stop_grace_period: 5s
#    ## Security options for some restricted systems
#    security_opt:
#      - seccomp:unconfined
#      - apparmor:unconfined
#    ## Uncomment next 2 lines if you want to access the database directly
#    # ports:
#      # - 5432:5432
#    environment:
#      POSTGRES_DB: ${PGSQL_DATABASE}
#      POSTGRES_USER: ${PGSQL_USER}
#      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
#      ## See other optional variables in the https://hub.docker.com/_/postgres
#    volumes:
#      ## Example:
#      ## - "/host/folder:/container/folder"
#      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
#      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
#      - "${HOST_PHOTOVIEW_LOCATION}/database/postgres:/var/lib/postgresql/data" ## DO NOT REMOVE
#    healthcheck:
#      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
#      interval: 1m
#      timeout: 5s
#      retries: 5
```

So, I created a user called `photoview` and changed ownership of `media-cache` to that user. Now, scanning works. I found that some scanner errors are due to invalid image files and inaccessible directories.

For now, it seems to be working but I'll let you know if there's anything else that comes up.

Thanks for your help.

**Comment by kkovaletp** [comment]
@kanwarplaha, thanks for sharing your compose file.
You DB files are located in the `${HOST_PHOTOVIEW_LOCATION}/database/mariadb` folder, where the `${HOST_PHOTOVIEW_LOCATION}` resolved to the path, set in your `.env file, located next to this compose file.
To remove the DB you need to run the `sudo rm -rf <the actual value of the ${HOST_PHOTOVIEW_LOCATION}>/database/mariadb`. The `sudo` is required, as DB runs under root and creates its files on the volume with the root ownership.

Unix-based OS rely on UID and GID values when deal with FS permissions. It means that it doesn't matter what is the user or group name of a user until its UID and GID remains the same. And in opposite, even if you created a user with the same name and group name, but having different UID or GID, the resulting permissions won't match. So, please don't rely on your `photoview` user on the host, as the name means nothing to the system. So far, you can only rely on the permissions for the `others` group. I'll investigate how to make sure the `photoview` user inside the image always has the same UID and GID.

**Comment by kkovaletp** [comment]
I've created a PR #972 to address these issues with the permissions

**Comment by kanwarplaha** [comment]
Thanks for the PR @kkovaletp.

For the permissions, I did use the same id/gid (999) from the docker container to create user/group on my host. Only issue was when creating user with id 999. The system complained it is below 1000.

**Comment by kkovaletp** [comment]
@kanwarplaha, does it work now? can we close the issue?

**Comment by kanwarplaha** [comment]
@kkovaletp yes this can be closed. Thanks for your help.
