### ISSUE TITLE
Album cover for multilevel folders

### ISSUE THREAD

**Issue by gpopesc** [photoview/photoview#977]
### improvement ideas:

When I have 2 or more subfolders (/folder1/folder2/folder3/pic1.jpg) I cannot assign album cover photo for folder1 or folder2, only it can be done for folder3 [from here](https://github.com/photoview/photoview/issues/765)

**Comment by kkovaletp** [comment]
Thanks for submitting this issue separately, but I just found the same request #89 with a better description, so I'm closing this issue as a duplicate
