### ISSUE TITLE
Supports Android

### ISSUE THREAD

**Issue by hausen1012** [photoview/photoview#994]
This program is very concise and I really like it. Thank you to the author for their efforts.
May I ask when can the Android client be launched? I think this is a demand for a large portion of people

**Comment by kkovaletp** [comment]
@hausen1012 this is great that you like Photoview. Welcome to the Community)

We have the dedicated issue #701 for this topic, so I'll close this one (even though it is not an issue, but just a question)
BTW, we have the Discord server (the invitation link is in the Readme) to chat within the Community and ask such (and other) questions. I think that the Github Issues is not the best place for this type of communication.
